# 前言 {-}

本书收录的文章都是以我自身为材料，写我的生活经历、兴趣爱好以及思想观念。我写这本书是为了忠实地记录自己的青春时代，将其作为一份人生的纪念，送给家人朋友，还有将来老去的自己。

这些文章多带有私人性质，并且缺少文学修饰，我不奢望会引起他人的注意。如果侥幸得到读者关注，我可以为您想出一个读下去的理由：人生经历是时代和环境的产物，在中国尤其如此，发生在一代人身上的故事总是那么雷同；我的经历是普通的，也是普遍的，我的回忆也许能为您的回忆做一个注脚。

标题受奥威尔《如此欢乐童年》的启发，是否欢乐就由读者自行评判吧。

# 卷一 生活点滴 {-}

# 管中窥世

我向来对历史小有兴趣。在读史的时候，我往往发现，同一段历史，因为立场与角度的不同，观察出来的结果可能会大相径庭。作为历史的旁观者，我们俯瞰纵览，总是从全局出发，把纷扰世事都分析出个起因经过结果来。有时难免会「手里有个锤子看什么都像钉子」，用自己的一套理论来强行解释。而且能算作历史事件的，牵涉到的都是大人物，没看到哪部史书是为小人物编年纪传的。所以我会好奇，想跟亲历历史的小人物聊一聊，问问他是怎么想的。转念再一想，干嘛一说历史就想到希腊罗马、秦汉唐宋呢？我自己，当今世上的一个普通人，不就是亲历历史的小人物吗？于是乎，在这篇小文章里，我想聊聊自己是怎么看待自己所处的时代的，想到什么就写什么，只求真实诚恳。

回顾过往，我最庆幸的就是生活在一个相对和平的年代。全球各地的殖民战争，两次世界大战，美苏冷战——这之前的世界实在太可怕了。我的亲人中有战争的亲历者，我从小受的教育也深刻揭示了战争的残酷，所以我对战争还是心有余悸。比我年纪更小的下一辈人，因为离战争太遥远，恐怕不会有这么切实的感受了吧。没有稳定的社会，一切个人幸福的追求都无从谈起。真希望有生之年世界能一直和平下去。

可这世上是不存在永久的和平的，就在我安然闲适地写这篇文章的时候，某个角落正有人遭受战火煎熬，只是我看不到罢了。恐怖主义正是用最丑陋的方式让我看到世上的恶，原来人心中有这样的仇恨。2001年九一一事件发生时我还在上小学，即使年幼无知，也隐约发觉世界慢慢变了，这之后的恐怖事件就没有断过。我去法国留学后，感受就更强烈了。2015年年初的查理周刊事件、年底的巴黎恐怖袭击，2016年尼斯恐怖袭击，让我发觉仇恨与恐怖就在身边。现在小规模的恐怖袭击已经成为日常事件了，甚至成不了什么大新闻。尽管如此，我还是乐观的，这类暴力事件并不会干扰社会整体的发展。我认为加强管制治标不治本，解决仇恨根源才能彻底消灭恐怖主义。国家、民族、宗教、意识形态之间的冲突，成了我非常关心的一个课题，当今世界急需找到一条和平共处之路。

如果有一天人类灭亡，最可能的原因就是破坏了赖以生存的自然环境。环境保护是二十世纪的焦点，近几十年来更为迫切。臭氧层空洞、温室效应，都是人类自己一手造成的。如果说这两者还是温水煮青蛙，一时半会儿看不出对日常生活的影响，从雾霾这件事就能直接感受到环境破坏的恶果。最近十来年，中国的雾霾问题极其严重，很多城市已经看不到蓝天了，永远是灰蒙蒙的，出门就得戴口罩。

再有就是能源问题。我从小就反复听到石油还有若干年就会耗尽的传闻。就目前来看，真正能起到替代化石燃料作用的大概只有水能和核能。前者依赖水流，破坏生态，后者则有安全隐患。2011年福岛核电站事故之后人心惶惶，给核能发展造成很大冲击。当时国内谣传碘盐能防辐射，还造成了抢盐事件。虽然有安全上的顾虑，但是长久来看，估计核能还是大势所趋。

在科技方面，对普通人影响最大的莫过于互联网的普及。在我看来，互联网是可以与造纸术、印刷术相比拟的伟大发明，彻底改变了信息传播的方式。我小的时候连手机都没有普及开，还在用传呼机。现如今电脑、手机甚至眼镜、手表都可以连接网络，可以随时随地与世界任何一个角落交流。信息产业毋庸置疑是近二十年来最兴盛、最热门的行当。九十年代以来涌现出大量的互联网公司，谷歌、亚马逊等等成为了科技企业的巨头。苹果公司因为生产最受欢迎的互联网终端设备，即智能手机iPhone，一跃成为世界上市值最高的公司。我自己便是跟随大势，选择了几十年前闻所未闻、现在却供不应求的信息工程师职业，加入了信息科技的大军。

互联网让人能以快捷、低廉的方式获取信息，同时也造成了垃圾信息的泛滥和信息安全隐患。现在当真是娱乐至死的年代，比起用互联网获取知识，更多人是藉此关注名人的一举一动。在信息时代，所有事都容易被关注，也容易被遗忘。引导公众注意力成为了利益丰厚的产业。如何掌控信息，而不是被信息掌控，应该是所有现代人的必修课。

谈完了这些普遍话题，再说说中国特有的现象。最近三十年是中国崛起的时代，从封闭落后变为开放发达，正式转型为现代化国家。这期间让我印象最深的几个标志事件是：1997年香港回归，1999年澳门回归，2001年申奥成功、中国加入世贸组织，2008年北京奥运会。现如今中国经济腾飞，成为世界的加工厂。我刚到法国时发现超市里的很多商品都标有中国制造，颇为感慨。

伴随着经济发展，中国也出现了众多社会问题。环境污染，高房价，食品安全，医患关系，应试教育，数不胜数。一些恶性事件造成了难以弥补的影响，甚至于使政府丧失了公信力。依照我的观察，这些五花八门层出不穷的问题大致有三个根源：

第一是贫富差距。中国是变富了，但真正的财富只掌握在一小部分人手中。中国各城市发展相差太大，发达地区与贫困地区完全像是两个不同的国家。即便是在北上广深这些花团锦簇的国际大都市，上层与底层的差距也是惊心动魄的。高楼大厦耸立云霄，而那些修建高楼大厦的农民工却饥寒交迫，可能连应得的工资都拿不到。因为要争夺资源，所以要铁了心往大城市挤，大城市再糟糕总归对未来有个念想，小地方根本看不到未来。在这一过程中，就有了各种悲欢离合、人间惨剧。最可怜的就是留守儿童，中国有五分之一的儿童得不到良好的照顾和教育。

第二是法制不健全。在光鲜的表皮下，中国还是守旧落后的人情社会。立法不健全，执法不到位、不透明，充斥官僚腐败，老百姓不懂法也不信法。恶劣事件并不是最可怕的，真正可怕的是得不到正确合理的处理。因为网络时代信息传播快捷，一桩案子很容易引起全社会的关注，一旦处理不当就使得人们更加丧失对法制的信心。

第三是与传统文化的割裂。经历过二十世纪的风风雨雨，尤其是文化大革命，中国人在文化上与过去几千年的传统割裂开来了。传统这东西好处坏处都有，在转折期免去过往的桎梏未必就是坏事。但是，人民总要有一套积极向上的价值观，这样社会才有好的风气。中国人是世俗的，本来就不信宗教，再没有了对传统道德的敬畏，结果就是清一水的入世务实、争名逐利。假使整个民族都只看得到眼前的利益，没有牺牲小我为国为民的精神，将来如何不言而喻。

以上就是我对过去三十年社会各方面的一些看法。我自认是个小人物，未曾妄想能对社会造成什么影响，只是随波逐流。不过，所谓社会，所谓人民，终究是一个个人。如果每个人都能施加自己那一点点微小的力量，最终就能推动历史的车轮。

# 迁徙的人

## 一

曾听朋友讲起，他从小到大没搬过家，和街坊邻里的同龄人情同手足。我听过后很是感慨。自打懂事起，我们家就一直搬家，过去的邻居我连姓甚名谁都想不起来了。偶尔在夜深人静辗转难眠的时候，我会假想自己躺在当初睡过的另一张床上，甚至能清晰地记起房间的细节，过去的回忆也一点一滴地涌上来。

说起来很有趣，人的记忆是不由自主的，有些东西，比如应付考试的课本知识，拼命去记还是记不住；一些无关紧要的小事，说不清是什么缘故，却莫名其妙地在心里扎了根。当我整理过去的记忆时，像是看一部胡乱剪辑的影片，看不太明白拍摄者的主旨。尽管如此，一些片段还是深深打动我。人心真是奇怪又有趣。

我的老家在辽宁，是个典型的东北能源城市。我的祖辈父辈基本都在矿厂工作。小时候我们和爷爷奶奶一起住在小镇上。家里一共四间房，一个小院。爷爷奶奶住一间，我和父母住一间，另外两间没人住，用作储物间。那时我正处于最无忧无虑的年纪，父母身上还有着年轻人的朝气，爷爷奶奶也身子硬朗。不知是不是记忆的美化，在我的印象里，那时一家五口其乐融融，每天都很快乐。有一个片段一直铭刻在我脑海里。那是在某个夏日午后，父亲和另外几个亲戚一起干活，大概是在修葺房屋吧。看着大人们忙忙碌碌，我好奇地东瞅瞅西看看，像调皮的小猫小狗一样跑来跑去。架梯子爬屋顶尤其令我感兴趣，我心里跃跃欲试很想爬梯子，但是又怕高。工作忙完已经临近傍晚，正是一天里最宜人的时候，凉风吹走了暑热和疲惫。适度的体力劳动既活动了身体，又带来完成事务的满足感。大人们挥洒汗水之后有说有笑，沉浸在愉悦的气氛中，这气氛把我也感染了。母亲用一口大铁锅炖了一锅菜，不过是茄子土豆之类，吃起来却格外美味。这样普普通通的一天，一直默默地、牢牢地占据了我记忆的一个角落，陪了我二十几年。

八岁那年，我父亲从矿上辞了职，到市区和我二伯合伙做起了出租车生意。二十年前个体营业还算是件稀罕事，事后想想，正是由此没受到下岗潮的冲击，家里无形中躲过了一劫。我在大姨家暂住了一段时间，随后被父母接到市区。我对搬家的事充满了不安和抗拒，住在大姨家时一直闷闷不乐，还曾在夜里偷偷落泪。搬家之后不仅要和一直照顾我的爷爷奶奶分开，还要告别小学里刚相处半年的同学和老师。那时父母怎么劝慰我，我已经记不太清了，只记得「人往高处走，水往低处流」、「树挪死人挪活」这几句话。

刚到市区时，我们借住在二伯家。二伯一家三口住在正房，我们家住在门房。即便是亲兄弟，做生意也难免产生龃龉，借住又平添了寄人篱下之感，久而久之越来越难相处。我一个小孩子都觉得不愉快，父母只会感受更深吧。住了大概一年多，为小事起了些争执，我们家就搬出去了。再过了一年多，两家就把车卖掉散伙了。

从二伯家搬出去后，开始了几年的租房生活。租的第一间房坐落在城市与乡村的交界处，窗外是一片宽阔的农田，越过农田可以望见我读的小学。一个院里两间房，房东住后院，我们住前院。那时我父亲常上夜班，白天睡觉，三口人住这种一室户很不方便。平时上学还好，周末在家时，为了不影响父亲休息，整天一点声音不能出，像是在练哑剧。我们家在这儿住了也就一年吧，印象不是很深，到现在还能记起来的只有几件小事。比如说，这家房东太太人很好，夏天里经常请我吃雪糕。再有，我曾经周末睡昏头，从下午睡到傍晚，醒来后误以为已经是第二天早上。

租的第二间房十分宽敞，比之前舒适多了。这回是独门独院，正房是一室一厅，有个小院，还有间门房，三口人住绰绰有余了。童年好多愉快的回忆，例如第一次看《灌篮高手》，第一次看金庸剧（古天乐、李若彤版的《神雕侠侣》），第一次去逛旧书摊，都是在这里发生的。

我们刚搬过去时还是夏天，等到冬天顿时画风一转，立即变成了最惨痛的租房回忆。原来正房的供暖有问题，冬天时我们只好去门房住，三口人挤在十平米的小屋。父亲上夜班的时候，白天还要门窗紧闭，拉起窗帘，屋里黑洞洞的。平时上学的时候还好，周末就很难熬了。有时我实在无处可去，只能呆在黑漆漆的房间里，我就把窗帘掀开一小角，借着微弱的光线读书。那时买书不易，我读书都很珍惜，舍不得太快读完。时隔多年，我依然记得当初蜷缩在窗边读书的情景。记得那时买过一本叫做《魔鬼出租车》的科幻短篇集，我原本每次只读一篇，有个周末实在太难过，就任性地一口气把后半本读完了，真是奢侈到心酸。好不容易熬过冬天，房东突然说不租了，我们只好搬家。

接下来租的房子是临时找的，条件不怎样，是只有二十来平米的一居室。印象很深的是漆成红色的木地板，这颜色感觉不像是普通住房，倒像是体操房。房东是个老太太，脸上有烧伤的疤痕，在小孩子眼里看起来很可怕，性格似乎倒还不错。在这里住的时间不长，天冷了就搬出去了。

再后面租的是一间耳房，面积也不大。好在院子很大，就我一个小朋友，可以随便玩耍。旁边一户人家是开铲车的，平时铲车就停在道边。一开始觉得巨大的铲车很帅气，可是后来常在早上被铲车发动的声音吵醒，柴油味更是可怕。

又过了不到一年，大概在我小学五六年级的时候，我们家终于买房子了。前后算下来，我小学六年里一共搬了六次家，几乎每年都要搬一次。因为学校调整合并的关系，从镇上搬到市里之后，我的小学校址也变了三次。这样一想，我的童年可以说是在搬迁中度过的。亏得是小城市，搬来搬去其实都没多远，但心态上始终免不了受影响。

这种童年时期受到的影响，直到现在仍可从我身上清晰辨认出来。比方说，我喜欢扔东西。有一种强迫行为叫囤积癖，不由自主地囤积物品，家里堆满毫无用处的东西。而我恰好是这种行为的反面，特别喜欢清理物品，每次扔掉东西都给我一种快感。我喜欢房间井井有条，清楚每件物品的摆放位置。抽屉、收纳盒、文件夹，每样都要有专门的用途，让我能立马知道里面装了什么。我喜欢控制物品的数量，恨不得全部家当都能塞进一只行李箱，长期不用的东西就送人或者扔掉。我从来不买纪念品，房间里几乎没有装饰品。这都是常常搬家所导致的习惯，因为这样一来就可以轻易搬迁、快速安顿。有朋友说我的房间太像旅馆了，真是一针见血的评价。

## 二

初中平平稳稳地在同一个地方住了三年，这是我稀少地体验到邻里生活的日子。当时住的是平房，邻里间低头不见抬头见，往来比较密切，经常一起吃饭喝酒、唱卡拉OK什么的，有时傍晚还一起打打羽毛球。后来家里趁便宜又在近旁买了间小屋，给我一个人住。不过饮食起居当然还是和父母一起。从小到大，这是我第一次有了独自的空间。自己一个人的时候，虽说也不过就是看看书、听听音乐，却渐渐地觉醒了独立的意识，从童年走向青年。有的人喜欢热闹，身边不能离了人，做什么都要有人陪着。我则是喜静不喜闹，很明白独处的好处。生活中精深微妙的乐趣，往往都是一个人独处的时候才能体会出来。读书、写作、思考等需要专心致志的事自不用说，即便是些琐碎小事，呼吸雨后湿润爽朗的空气、欣赏路边兀自开放的花朵，终归也是要一个人去感受的。这段独居的经历，让我天性中静谧的一面自由舒展开来，在我成长过程中有不小的影响。

升到高中之后，为了上学便利，我们家搬到了学校旁边。新家在市中心，比之前住的地方要繁华热闹，刚搬过去时颇有些兴奋。我还记得搬家的当天，和帮忙的亲朋吃过饭后，我到附近转了一圈，找到一家书店翻翻漫画杂志。晚上回来看看动画节目，觉得还是挺开心的。那时我还不知道，好日子就要到头了。

高中三年是我生活中最痛苦、最难熬的一段。首要的理由当然是严酷的学业，早上七点上学，晚上十点半放学，每周只有周末下午休息半天。当时总是睡不够，简直站着都能睡着。比起沉重的课时安排所造成的生理压力，更可怕的是考试排名所造成的心理压力，每次都是心惊胆战。还有家里不顺，搬家前一年父亲患了心脏病在家养病，家里一下子少了经济支柱。人到中年遭遇挫折，父亲内心的苦闷可想而知。母亲做了多年的家庭主妇，这时突然要去打工赚钱。因为没有一技之长，母亲做的都是些体力活，所受的辛苦我都看在眼里。全家人各有各的难处，家里的气氛很压抑。因为教育背景的不同，我和父母间有鲜明的文化代沟，加上我当时处于叛逆期，彼此间矛盾冲突不断。我知道争吵没有好结果，后来就开始冷战，回到家都不说话。到后来连冷战都不能了，只好独自生闷气。

我从小到大都是模范生，一向严格要求自己。父母的学历不高，在我课业方面从不过问，也没因为我考试考得好有过什么奖励，只是习以为常罢了。我就读的是全市最好的重点高中，藏龙卧虎能人辈出，省状元都出了好几个，我虽然仍处上游，可是自然不像在初中时那么突出了。考试本已艰难，试后排名更加无情，优等生的成绩都是伯仲之间，一次马虎大意、发挥不佳就可能导致名次大幅下滑。考试失意造成的那种懊恼、悔恨，时至今日仍常常在我的噩梦中出现。记得有次考得不好，家长会后母亲板起脸来教训我成绩下降如何如何。明明自己已经付出全力了，却要被平时不关心我学业的人指责，真是使我出离了愤怒。当时我并没有发作，反而和颜悦色地接受批评，还信誓旦旦地说下次努力。我知道家里的苦处，也知道代沟导致沟通困难，说也说不清楚，吵架一点好处都没有。随后我说要出去走走，一个人跑出去很远，到了一处没有人的河边静静地坐着，告诉自己一定要熬过去。

生活中的很多事，就是这样的无可奈何，只能忍过去。最悲伤的一瞬间，就是明白了这些不开心不是某个人的错，而是社会现实所造成的。我知道父母的出生年代和生长环境，我不能要求他们既开明又睿智。由于中国历史发展的特殊性，短短百年里从封建社会变到现代社会，文化传统剧变，其中几代人的差异是巨大的。比如说，我曾因为关卧室门与父母产生过冲突。中国的传统家庭是不注重隐私的，父母不会把子女当成独立的人，更像是依附于自己的所有品。我强调自己的隐私权，在父母眼里就成了对他们的冒犯。再比如说彼此间的交流，我总觉得与父母沟通不顺，因为他们根本不习惯这种沟通。我的父母和祖父母一辈的关系就有着缺憾，这缺憾又传到下一代。在传统观念里，「父亲」的形象就是一家之主，生活的重心是赚钱养家，无暇与家人沟通。爷爷去世后，父亲就曾多次表示后悔当初没跟他好好聊过天。而在我的整个青少年时代，父亲忙于工作，我们彼此间相处的时间极为有限。姥爷去世的早，母亲从小在继父家长大，形成了坚强独立的性格。在我的成长过程中，母亲只有辛苦劳作默默付出，却没有什么情感的表达，极少向我表现温柔的一面。这些生活的缺憾，又能怪的了谁呢。

小时候觉得父母像天一样，无所不知无所不能；上学之后才知道，原来父母能力有限，很多问题都答不出来；青春期时觉得父母站在自己的对立面，有时甚至面目可憎；长大之后终于明白，父母不是超人，也不是恶人，只是普通人罢了，像芸芸众生一样，会做对事也会做错事。更可悲的是，人是环境的产物，逃不过社会的摆布。

好在故事有个好结局。谢天谢地，我终于成功地把高中熬过去了，而且成了高考的得利者。高考是残酷无情的，同时也给了所有人一次公平竞争的机会，成功的人就能享受到最好的教育，换取一个好前程。对于我来讲，高考最直接的好处就是给了我离开东北的机会。

我长大的过程中，眼睁睁地看着东北一步步跌入谷底。东北衰败的原因很多，我对经济只有一知半解，不妄图透彻分析，只说说显而易见的几点。东北有天然的地理劣势，气候寒冷，交通运输不便。建国以后，东北以重工业为主，产业结构单一，一旦支柱产业遇到问题，比如资源枯竭，经济就迅速崩溃。东北多是国有企业，依赖政府投资，工作效率低、官僚主义、贪污腐败、不切实际的计划经济，各种毛病都占全了。在这种环境下，企业缺少市场意识，竞争力低下。经济走下坡路后大量人口流出，出生率降低，人口老龄化，造成恶性循环。现如今东北各项经济指标逐年下滑，将来恐怕会越来越糟。

所以，但凡有些危机意识的人，都主动从东北逃出来了。我刚上高三时，父亲就转行去唐山做生意。我高考时只有母亲陪着，直到大学入学时父亲才回来给我送行，这就是后话了。

选大学是一个艰难的决定。选什么学校，选什么专业，我都一片茫然。国内的应试教育使得学生都成了考试机器，只知道要考个好分数，根本没机会发展自己的喜好、考虑将来到底想做什么。这时突然让我自己为人生做主，就像是突然把常年卧床、肌肉萎缩的人扔到野外生存一样，每迈出一步都心惊肉跳。最可怕的就是输不起，错不得。我那一届是要在高考成绩出来之前报考，需要自己估计分数，高估了可能考不上，低估了又浪费分数。学校的报考分数变来变去，每年都有浮动。一旦第一志愿录取失败，第二志愿被名校录取的几率是很低的，只能去低一档的学校。所以即使有心仪的学校和专业，报名也是带有风险的博弈。

父母什么都不懂，老师们也只能给出参考，最终还得要我自己拿主意。临报考那几天，我从早到晚在网上查资料，比对历年分数线，想尽办法找到最优方案。母亲一直催促我，让我早点给身在外地的父亲一个说法，更加让我心烦气躁。到最后，我用了最保险的办法，按照分数高低，填了上海、北京、大连的三所高校，彼此之间拉开了相当的分数差，以确保无论最终分数如何都能有个可以接受的结果。专业也是按照录取难度，从高到低填的，没有太多考虑个人喜好。更确切地说，我对各项专业缺乏足够了解，根本谈不上什么个人喜好。最终我被第一志愿的上海高校录取，专业则是第四志愿，学了计算机。

这个结果，无论当初还是现在，我都相当满意。多年的辛苦学习，终于有了回报。有时我会感慨，要是当初考试发挥失常，或是报考时一念之差，又或是运气有变，我的人生轨迹就要大变样。我是喜欢控制风险、总要给自己留条后路的人。把人生押在一场考试上，赌注实在太大了。大概从这时起，我就有了一个想法，希望人生中接下来的选择都有周转余地，而不是大起大落、成王败寇。

## 三

书归正传，去上海这件事，既有偶然性，也有必然性。偶然性是由于高考的不确定，必然性则是由于中国现阶段的发展状况。中国各地区贫富悬殊，分成明显的层级。北上广深这四大城市，尤其是北京上海，繁华程度与世界上任何大都市相比都毫不逊色。中国的贫困地区，尤其是西北的一些乡村，艰苦程度比起世界上任何贫民区也是不相上下。这之间的差距之大触目惊心，而且由于经济、教育资源的垄断，看不出一丝能弥补鸿沟的希望。高考中的佼佼者最终集中在了北京上海，也就理所当然了。

在去上海之前，我从未离开过辽宁。在父母的陪同下，第一次坐上去上海的火车，我的兴奋难以抑制，半夜里还在火车上和父母聊天。南北方遥远的距离，在接下来的几年里让我吃了不少苦头。当年第一次经过时觉得转瞬即逝，之后每次却都显得愈加漫长。当时未曾想到，此后多年我再也没回过辽宁。之前是在同一个城市里搬来搬去，这之后则是在不同城市间迁移。

我对上海最初的印象，是来自于大城市与小城市间的强烈对比。耸立的高楼大厦，繁华的商业街区，便利的交通设施，都给我直观的冲击。刚到上海时，我和所有的游客一样，去豫园吃小笼包，去东方明珠看夜景，被淹没在人山人海；第一次坐地铁，感叹现代交通的方便快捷；去福州路逛书店，被书店的规模、种类繁多所折服。可这些并不是上海独有的特色，而是大城市的特色。要用一句话来概括上海，就是现代化、国际化的大都市。上海的中国味道已经被国际化冲淡了，和纽约、巴黎、东京并没有什么本质的不同。这里的好处，其实就是国际都市的好处：完善的基础设施，应有尽有的商业服务，从全球汇集而来的金钱、人才、机遇；这里的坏处，其实也就是国际都市的坏处：环境污染，噪杂，生活成本高，人情冷漠。和国外的大城市相比，上海的治安更好，人力服务更低廉，美食更合中国人的口味，缺点则是环境差，空气污染严重，其它都大同小异。

在上海那几年我一直住在学校宿舍，前后住过三间，有过九个室友。学校宿舍价格低廉，只提供最基本的住宿条件，特色是冬冷夏热，断网停电。集体住宿多有不便之处，室友间作息习惯不同，上厕所、洗澡都要排号。即便如此，我还是非常喜欢大学的住宿生活的。同龄人天天在一起，分享喜怒哀乐，很容易形成深厚的友谊。我和历任室友都成了好朋友，有的至今仍保持联系。现今已然踏入社会，愈加发觉学生时代没有杂质的纯粹友谊的珍贵。

前面提到父亲去了唐山做生意。我去上海读书之后，母亲随即搬到唐山，父母两人此后在唐山生活至今。我大学期间的寒暑假基本都是在唐山度过的。唐山在首都旁边，按说处在一个显著的地理位置上，可是存在感却不强。提到唐山，人们的第一反应就是唐山大地震，其次是赵丽蓉（其实她是天津人），别的就没什么了。我对唐山的印象并不好，这一方面是源自与上海之间的落差，另一方面则是因为唐山和东北太相似了。唐山是资源型城市，经济完全依靠钢铁煤矿，环境污染严重，在刚刚逃出东北的我看来，这里不过就是条件好一点的东北。

就这样，我在上海、唐山两地辗转。大学那几年，我一直处在迷茫的状态。中国的应试教育，只是填鸭式地灌输知识，起不到多少育人作用。大学时我已经是二十出头的年纪，对自己将来何去何从却没有方向，甚至没有认真思考过。这之前我只知道努力学习，通过中考考上重点高中，通过高考考上重点大学，可是进了大学之后要做什么呢？应试教育已经把我对学习的热情磨灭了，大学的课程只要合格就好，考得好坏都没差。除了每学期期末考试前紧急突击一两周，我对学业毫不在意。随着年级升高，我越来越老油条，迟到、翘课都是家常便饭，后来甚至好几门科目不合格，又要去补考、重修。我身边的同学也都半斤八两，所谓的「学霸」也不过是拿出高中十分之一的精神，对待考试更认真些，真正扎实求学的人是极稀少的。而且扎实求学又如何，难道要去搞科研吗？我在学校的实验室呆过一段时间，足以让我见识到科研圈的怪现状，真正热爱科学而且适合科研的只是极少数，我是绝对没有精力和热情走这条路的。

到了毕业前的倒数第二年，我终于开始考虑毕业后的去向，第一个否决掉的就是读研。国内的研究生太偏向于科研了，并不适合我。余下的两条路，一是找工作，二是出国留学。找工作是大多数人的选择，我内心却有所抗拒。如果要找工作，回东北和唐山都是不可能的，这两个地方科技产业贫瘠，根本没有足够的工作机会，合理的选择就是留在上海。我对上海的感情是复杂的。一方面，我深切体会到大城市的好处，不单单是生活上的便利，还有现代化的文明建设。中国很大程度上还是保守落后的，在契约精神、开放包容、尊重个体等各方面都做得不好，上海则是国内出类拔萃、甚至是唯一真正与国际主流文化接轨的现代化城市。另一方面，我也明白在大城市生存的艰难。在国内大城市打拼的人被称为「北漂」「上漂」，一个「漂」字道出多少辛酸。我这样的外地人，就像是风中浮萍，扎不下根。在政策上，中国有严格的户籍制度，外地人遭到法律硬性歧视。没有当地户口，就没有当地居民身份，在就业、医疗、教育方方面面都不能享受当地居民同等待遇。我作为外地人，居然从一开始就比上海人低了一等。在经济上，上海的房价高到恐怖，当真寸土寸金。即便是重点大学的毕业生，工作一年哪怕不吃不喝，攒下的钱也不够买个卫生间。外地学生能赶在结婚时买房，都是要倾尽全家所有，砸锅卖铁付首款，再背上几十年的房贷。没错，上海的机会多，可是抓住机会也要努力拼搏。为了体面的生活，要辛苦地工作，计算机这一行的加班更是出了名的，近年来更是搞出九九六的说法（从早九点工作到晚上九点，每周六天）。如果我是有钱人，我会很喜欢在上海定居。可惜我是外地底层出身，要生活在这里就意味着接下来几十年的辛苦人生。

还剩下一条路就是出国留学，也是我最终作出的选择。为什么选择留学？面对父母、签证官、国内外的朋友，我都各有一套说辞。面对我自己，我却发现这些说辞有些含糊无力。比方说，对外国文化的向往。我从小喜欢世界文学，对外国的文化确实非常有兴趣。不过，假如只是喜欢外国文化，可以去旅游啊，不一定非得要花上几年时间留学。再比如说，追求国外的高质教育。我对国内的应试教育深恶痛绝，想尝试外国教育，这的确是事实。但是，我对自己的专业喜好有限，不一定非得要继续深造。还有就是在国外的职业发展。中国经济发展迅速，机会很多；在国外发展受各方面限制，不一定会比国内好。更何况，毕业之后是要留在国外，还是回国找工作，我并没有一个明确的目标。考虑到国外求职状况、签证政策，即便我有预定的计划也不保证能实现，很大程度上还得看运气。我是有考虑在国外工作，可是一旦不顺利就回上海也是一开始就有的打算。

我的种种官方说法都是真实的，却都不是决定性的。坦诚地讲，我选择出国包含着逃避的心态。实事求是，最根本的原因，就是我还没有准备好迎接人生的下一阶段。留学可以给我两三年的时间深思熟虑，琢磨清楚自己到底想要什么。

下决心留学后，很快就选定了法国。法国的文化传统、生活环境都很吸引人；欧洲特色的工程师教育重视实践，多与企业合作，符合我的需求；免学费，生活成本相对低廉，以及教学计划中安排的长期带薪实习，使我免受过多的经济负担。与这些客观的好处相比，我曾学过一年法语这件事倒只是次要的理由了。

大学最后一年非常忙碌。学法语，语言考试，申请学校自不用说，办理签证也是手续繁多。我身为学生常年生活在象牙塔里，第一次在社会上办事难免受挫。很多事都是公文里一个说法，实际上却是另一个说法，各部门之间又互相推诿，我曾为一纸文件跑遍了上海。权力使人腐化，我去过的所有机关，无论大小，但凡有一丁点权力，都要用这权力难为人，摆出一副令人厌恶的嘴脸，而我也只能满脸赔笑。与此同时，我还要忙着写毕业论文。导师神出鬼没，不知道在忙什么项目，平时根本见不到，只是偶尔象征性地在会议上露个面。导师派他的博士生来「指导」我，这个博士生总是找我茬，每次开会都说我做的不好。当时室友们因为实习或是课程安排的缘故，全都搬出去了，宿舍就剩下我自己一个人，一到晚上就觉得格外孤单，后来甚至有了失眠的困扰。父母什么都不懂，帮不上什么忙，连体贴关心都是有限的。如此这般，我每天的情绪就在忧虑、寂寞、烦躁、愤怒之间来回波动。

那时给我最大安慰的，居然是一部电视剧。因为偶然的契机，我看起了《深夜食堂》。各色的人物，带着各式喜怒哀乐，汇聚在深夜的小饭店里，通过夜宵串联起一个个人生小故事。故事的好处在于恬淡，无论怎样的人生波折，最后总之是平静地接受，被时间淡淡地打发了。第一次看的时候恰巧正是深夜，看完一集不但感动到落泪，而且突然感觉饿的不行。后来我都会预先准备好汤汤水水作夜宵，在夜深人静的时候，边看边吃、边哭边笑。酒足饭饱，哭哭笑笑之后，整个人都轻松了很多。我明白了情绪这东西不释放就会越积越重，压到心里受不了的时候，一定要找个缺口发泄出来。

最后一切有惊无险。我的论文最终得到了优良的成绩。赶在机票到期的前一周，我终于收到了签证。经过一番短暂急促的行李准备，父母陪我到北京为我送行。这是我第一次出国，行程细节我还记得起来，先从北京飞到法兰克福，再飞往尼斯。下飞机后学校人员来迎接，当天办了各种手续，住进昂蒂布的一间学生公寓，从此开始了留学生活。

## 四

到法国最初的半年是段非常愉快的时光。第一学期主要是学习法语，课程安排很轻松。比起读书，更像是一段长期的度假。蔚蓝海岸是著名的旅游区，碧海蓝天与国内糟糕的环境形成鲜明对比，感觉身心都焕然一新了。这里的城市风貌也与国内截然不同，布局紧凑而又散漫，随心所欲没有一定规律。昂蒂布这样的小镇自不必说，尼斯、戛纳的热闹市区也是更有生活气息和复古风味，而不是摩登现代的钢筋丛林。我晚饭后常常去海滩散步，吹着海风，听海浪起伏，看海鸟翱翔。对于住惯了工业城市、商业都市的我来说，这种悠闲平静的生活是新鲜而又舒适的，我真想提高感官的敏锐，充分感受每一分每一秒的愉悦。

第一次独立生活也是很有意思的经历。当初住家里是全由父母照顾，在上海住学校宿舍也是集体式管理，从来没有为衣食住行操过心。一个人住，又是异国他乡，从水电网到米油盐都要自己打理，重新学习生活常识。最有趣的是下厨，有动手的乐趣，还有实际的好处。

可惜好景不长。半年过后，开始了正式的专业学习，时间一下子排满了。白日整天上课自不用说，课后还要忙着做项目，写报告。法国教学特色，没有教材，上课要自己记笔记。一开始法语不够好，记笔记很困难，上课和复习都多了一层麻烦。与国内大学期末考试一锤定音不同，这里平常小考很多，让我回想起了中学月考的恐怖。

现在想想，搬出学生公寓，标志着留学蜜月期的正式结束。在学生公寓住了一年后，我搬到了一幢海滨小别墅，那是我迄今住过的环境最好的地方，却在那里度过了心情最差的一段时间。别墅分两层，楼下有宽敞的客厅和数间卧室，可以住四五个人。楼上两个单间，一间是房东假期时住的，另一间则租给了我。这里宽敞明亮，面朝大海，确实是个好住处。缺点则是交通略不便，远离其他中国留学生。刚开始时不在意，后来逐渐感到有些孤单，课业压力大、拼命复习写作业的时候更是难过。

有过海外经历的人大概都对孤独深有体会。这首先是由于语言交流的困难。刚到法国时我的法语不是很好，日常交流还能勉强应付，深入一点的话题就没办法了。作为一个伶牙俐齿的人，一下子变得结结巴巴，满脑子的想法却说不出来，这种感觉很不好受。等到法语水平提高了，我发现文化差异才是了人与人之间更深入的隔阂。我去法国留学时年纪已经不小了，已经形成了自己的一套生活习惯和思维方式，不容易也不愿意改变自己去迎合他人。比方说，外国学生最主要的社交方式就是派对，我却很不喜欢。我楼下住的是商学院的学生，他们经常举办派对，饮酒作乐。有时来聚会的人有好几十，极为吵闹，平常工作日也能闹到凌晨，甚至被邻居报过警。我在楼上被吵到不行，又无力阻止（这些荷尔蒙爆炸的年轻人是连警察的话都不听的），有时只好被迫加入聚会，凑个热闹。派对的内容不过是饮酒和跳舞，几杯酒下肚，在昏暗的房间里，伴着闪烁的灯光、动次打次的电子舞曲乱扭。这种极其噪杂的环境下，连自己的讲话声音都听不清楚，没办法进行有意义的交流。

没出过国的人可能会有错误的认知，以为欧美国家，尤其是在法国这样「浪漫」的国家，娱乐生活会比国内更丰富。实际上娱乐服务是要靠人流量支撑的，世界上绝大多数地区都不可能比中国更热闹。当初在上海，不仅有各式夜宵，网吧，KTV，甚至连水果店、杂货店都有通宵营业的，这样的情形在国外是极难看到的。曾有一次我在巴黎错过最后一班地铁，又嫌打车太贵，想找个地方呆到早上，结果尴尬地发现酒吧都只开到凌晨两点，市中心的大街一片寂静。巴黎尚且如此，其余城市更不用说。昂蒂布这样的小镇，非旅游季晚上九点就见不到人了。再提一个曾让我很惊讶的事，法国的店铺周末关门，去银行、邮局都要平时规划好时间。总而言之，国外生活有平淡无聊的一面。当地年轻人热衷于聚会，也是缺少其它娱乐方式所造成的吧。

留学生间有「好山好水好寂寞」的说法，恰当地描述了我当时的心情。再美好的环境，住久了也就习以为常了。每天面对大海，让我对美景麻木了，大海的泡沫似乎也变得脏兮兮的。那段时间里，我最大的娱乐就是打电子游戏，用一张张游戏光盘缓解寂寞。电子游戏紧张刺激，能一下子抓住注意力，是快速释放压力的好方法。然而关掉游戏机的那一刹那，重回现实生活，一股强烈的空虚感会油然而生。

学业压力大，朋友少，缺少娱乐，我因此陷入了低潮。我整天都高兴不起来，把生活中的困难都放大了。我有段时间非常担心会挂科留级。法国工程师学校是宽进严出的，每年都有至少一成的学生进不了下一年级，需要重读。实际上我的成绩排名中上，完全不需要担心，这都是状态不好时的胡思乱想。后来到了要找实习的时候，我内心压力也非常大，对自己没有信心，总担心找不到。暑期三个月的实习去了学校实验室，我自觉有取巧的嫌疑，又继续担心毕业实习找不到企业里的实习岗位。在学校最后半年遇到了有种族歧视倾向、处处为难中国学生的一个老师，更是雪上加霜。做毕业项目的时候也遇到了诸多不顺，每天身心俱疲。直到最后顺利完成学业，来到里昂进行半年的毕业实习，才结束这段苦涩的历程。

我几乎立刻就喜欢上里昂了。有一部分的原因，可能是因为我刚从压抑的状态中走出来，有着展开新生活的喜悦。更客观的原因是，里昂符合我对城市的需求。这里在我看来是一个规模适宜的中型城市，有充足的工作机会、便利的公共交通，有着种种现代化城市的好处，不像昂蒂布那样过于狭小单调；同时，这里又不像上海、巴黎那样喧哗，生活节奏相对缓慢。在我居住过的几个城市里，里昂各方面处在一个合适的平衡点。里昂的城市面貌是平凡的，没有什么特点。我刚来时就有种已经住很久了的错觉，什么都是似曾相识。我倒并不认为这是个缺点，我到里昂是为了生活工作而不是旅游，这熟悉又平凡的感觉让我觉得更放心。

在里昂的这段生活，是我人生的又一次重要转折。

在软件公司实习半年后，我正式入职，结束了长达二十年的学生生涯。前面提到过，我当初是调剂到计算机专业的，对编程没有什么热情，大学基本是混过来的。来法国留学的两年半，我的专业水平有了显著提高，但是仍然没有太大兴趣。直到去公司实习，接触到具体的企业项目，才有了学以致用的感觉，重新萌发了对信息科技的兴趣。经过了多年的科班教育，直到毕业后才意识到自己喜欢并且擅长这一专业，真是件令人感慨的事。或许是我自己脑筋糊涂，可是教育系统也要承担相当的责任吧。

第一次领到薪水是件鼓舞人心的事。比起具体的金钱数额，更重要的是其象征意义。我终于从家庭中独立出来了，自己把控自己的生活。我的职业生涯正式起步，有了奋斗的目标和希望。

在搬了二十次家，换了五个城市之后，我终于有了驻足之处。世事难料，无法预知未来变化。无论将来会是怎样，我非常珍惜当下平静、自由的生活。

## 五

我曾经想过，如果人生能够重来，会变成什么样呢？思前想后，恐怕十有八九还是老样子，免不了要经历中考、高考、出国留学，即使有变化也无非是上海换成北京，法国变为美国。人的迁徙，就像大雁南飞、鲑鱼洄游一样，是为了适应环境。人是环境的产物，人生的主要脉络早早就定好了，大多数人都逃不出时代、社会和家庭共同预设的框架。

就说高考这件事，我能成为家里第一位大学生，自然少不了个人的刻苦努力。但是，更加起到决定作用的是国内高校扩招。从1999年起，高校招生规模大幅增长，参加高考的人数也随之增多。2008年考生数量达到历史顶峰，共1050万人，录取人数为599万人，录取率57%。作为对比，扩招前的1998年高考人数为320万人，录取人数108万人，录取率34%。2008年金融危机之后，因为经济状况、就业问题，高校扩招幅度减缓，考生数量也开始下降。可以说我们八零后这一辈人恰好赶上了高考蓬勃发展、社会对高考最有信心的年代。在我所处的时代环境里，高考是所有人认定的最高效的成功途径，我免不了要走上这条路。

我上大学时遇上了国内房价暴涨，房奴、蜗居成了最热门的话题。到我毕业时，大城市房价已经到了恐怖的程度，一栋房子可以榨干一家三代人的积蓄。高考把我送到了上海，巨大的生存压力又把我赶出上海。上海高校有着高比例的留学率，中国的崛起、与国际的频繁交流使得留学成本降低。这样一来，对于追求自由、不甘心回归小城市的我来讲，出国留学就成了实际合理的选择。

这样事后诸葛地分析下来，不由得感概人生的局限性，以及人的生而不平等。当我还在踌躇迷惘、看不清未来时，命运早已经布好了局，等着我像牵线木偶一样走上确定的道路。

我的人生态度可以概括为「乐观的悲观主义」。一方面我是悲观的，总能看到人生灰暗的一面，为未来做最坏的打算；另一方面我又是乐观的，敢于面对惨淡的现实，相信否极泰来。对于能够改变的，我努力去改变；对于无力改变的，我坦然去接受。回首过往，最令我欣慰的是，我并没有什么后悔莫及的遗憾。我已经尽力而为，打好命运发给我的每一张牌。

如果要从过去的经历中总结一些经验教训，第一就是做人要开心。曾经的那些忧愁烦恼，今日看来无足挂齿；今日的纠结苦闷，未来又未尝不会一笑置之呢。第二就是活出自我。我已经熬过了人生最初的阶段，走向独立，可以开始为自己而活了。我要活成自己想要的样子，而不是别人期待的样子。这些都是最浅显的大道理，却往往被人忽视。知行合一，做到了才是真懂了。

# 童年记趣

不知从何时起，快乐变成一件奢侈的事了。要问我上一次发自内心地感到快乐是什么时候，我真不知道如何回答。这倒不是说我的生活中充满苦恼；客观来说，我认为自己的生活很顺利，时不时会有令人开心的事。可是身为成年人，肩负着各种各样的责任，总有那么一两件事让人放不下。我的快乐总是混入了杂质，无论多么晴朗的天空也总飘着一两朵没来由的乌云。

仔细回想，我人生中最快乐的时光是童年，那时快乐是件多么简单的事啊。

曾经，快乐可以是一片菜园。老家曾有一片菜园，小时候我常陪爷爷一起去。菜园子不大，可以种些土豆，大葱，韭菜。种田这件事，比起自给自足，更主要是老人家的娱乐。中国人大概多多少少都有颗务农的心，从古时的「种豆南山下，草盛豆苗稀」到现在的阳台种菜，动手劳作自有一份闲情逸趣。爷爷耕作的时候，我东跑跑西看看，有时捡石子，有时摘狗尾巴草，自娱自乐不亦乐乎。偶尔干些农活，我也是添乱多过帮忙。忙活一阵子之后，在井边闲坐着，让清风吹干汗津津的身子，凉爽又惬意。

曾经，快乐可以是一堆石头。小时暑假去乡下亲戚家住，跟明明同龄却大我一个辈分的表舅一起漫山遍野乱跑。我们去小河边捡鹅卵石，意外发现了有着树木纹理的石头，以为是树木化石，当成宝物捡了一大堆。现在想想，不过是普通的木纹砂岩罢了。等暑假结束，父母来接我的时候，自然不能把这些石头都搬回家，只好选几颗小的做纪念，和我的宝贝「化石」告别。

曾经，快乐可以是一只小虫。小时候特别喜欢昆虫，帅气的刀郎，活泼的蚂蚱，吵闹的蛐蛐，潇洒的蜻蜓......捕到一只就能开心半天。再不济可以玩蚂蚁，用樟脑丸在地上画个圈，蚂蚁就跑不出来了。有次遇到蚂蚁搬家，看到工蚁们拖着肚子硕大的蚁后缓慢前行，真是惊人的奇景。

曾经，快乐可以是头上的天空。看云，千变万化，一会儿是崇山，一会儿是奔马；看星，漫不经心地洒满天空，却又编织成一个个星座，每个都有名字和故事；看月，阴晴圆缺周而复始，温柔皎洁的光芒把大地洗的干干净净。

曾经，快乐可以是心中的想象。我的每件玩具都是有生命的，每每在房间里展开波澜壮阔的冒险，桌子、窗台都是神奇的大陆，椅子、柜子都是高耸入云的雄伟建筑。再有，夜里乘车出行时，四下里一片漆黑，听着引擎稳定的低吼，看着闪烁的仪表盘，我会想象自己是在太空中航行，潜入到一望无际的宇宙深处。

这些天真无邪的乐趣，现如今早已一去不复返。即便是持续至今的，也都打了折扣。

比方说吃。小时候攒下一角一分的硬币，凑够了钱去买支巧克力脆皮雪糕，每一口甜腻都要细细品味。还有曾经最爱的荔枝味汽水，喝汽水喝到打嗝是最奢侈的享受。逢年过节家人团聚，桌子上摆满美味佳肴：酸菜炖排骨，拔丝地瓜，锅包肉，红烧带鱼，干炸丸子……当然也少不了各式饺子，羊肉芹菜馅儿的，猪肉酸菜馅儿的，韭菜鸡蛋虾米三鲜馅儿的……东北菜就是讲究一个大气豪爽，保管吃到撑肠拄肚。现如今想吃什么吃什么，想怎么吃怎么吃，却没了当初那种乐趣，甚至于为了健康特意去吃些清汤寡水。

比方说看电视。电视曾是家庭娱乐的中心，无论怎么搬家，始终稳稳地端坐在客厅最显著的位置。小时候家里电视还是用天线的，只能收到中央台和本地电视台的信号，而且时不时信号差画面抖，要用力拍一下才能接着看。每晚五点半播一集动画，八点播一集电视剧，周末有综艺节目，偶尔会播老电影，这就是全家共享的娱乐。现如今有了电脑、手机、平板，床上、车上、厕上随时随地都可以看自己喜欢的各类节目，却没了当初的那份劲头。

比方说听评书。小时候常听些广播节目，音乐、相声、评书、访谈等等。最喜欢的要数单田芳的评书，《三侠剑》《龙虎风云会》《铁伞怪侠》《明末遗恨》……听了一部又一部。评书虽不算是什么高深的艺术，但是既然能够长久地在民间流行，自有独到之处。比如节奏的把握，语气的控制，用不同的腔调来表现人物的对话，细节做得到位才能引人入胜。我每日按时收听，生怕落下一集。现如今我已经好多年没听过评书了，偶尔怀旧找来听听，也是几分钟就没了耐性。评书日渐凋零，说书人和听书人都断了档，下一代人恐怕都不知道有评书这么回事了。

比方说棋牌。我小时候一度痴迷象棋，跟街坊邻里的退休老人杀个天昏地暗。堂姐送过我一套迷你军棋，装在小小的盒子里，可以挂在钥匙链上。有次匆忙躲雨时不小心把棋子散落一地，有几颗棋子不见了，让我懊恼了好久。和家人朋友一起下跳棋、五子棋、打纸牌也都曾给我带来好多乐趣。如今我连充满声光震撼的电子游戏都玩腻了，更别提这些朴素的棋牌了，只有社交聚会时才偶尔碰一碰。

比方说读书。自打我识字以来，读书一直是我最主要、最持久的爱好，二十多年不曾间断。现在读书的深度广度远超儿时，不可同日而语。可要是纯论阅读快感，小时候的快乐要胜过现在十倍。那时读书囫囵吞枣，来者不拒，什么书都能读的津津有味，贪婪地汲取每一点养分。每本书都被我视为珍宝，一点损坏都不能有，理所当然概不外借。如今读书是稀松平常的日常活动，只剩下细水长流的平淡，再没有当初那么强烈的刺激了。

由于时代的剧变，我这一代人尤其喜欢怀旧。我在社交网站上时不时会看到追忆童年的帖子，常看到儿时流行的零食、玩具的照片。一开始会很有感触，看多了就逐渐不以为然。没错，童年幸福又快乐，可这幸福快乐并不是真的来自于这些旧日的事物。真正给童年带来快乐光环的是儿时的心理状态，一来是无忧无虑，二来是懵懂无知、看什么都新鲜。

无忧无虑真是最美好的状态。小时候衣来伸手，饭来张口，每天什么都不用想，只要开心就好。唯一要动脑筋的就是怎么找事情解闷，一分钟都闲不下来。没有不开心的事，不就只剩下快乐了嘛。可是人活在世上总有许许多多的难处，哪能一直无忧无虑呢。小时候无忧无虑，是因为忧虑都被父母承担了。自己最没心没肺的日子，也正是父母最苦最累的日子。同时，这份无忧无虑也是有代价的，儿童很大程度上是成人的附属品，没有权利也没有能力去享受自由。

新鲜感是快乐的另一大根源。小时候头脑是一页白纸，什么经验都没有，做什么都是第一次。有了新鲜感，平平无奇的事物也自有一份乐趣在。第一次走路，第一次说话，第一次听故事，第一次读书……妙就妙在「第一次」。正因为是从无到有，每天都要输入大量的信息，所以小时候觉得时间过得特别慢，现在却觉得时间转眼即逝。这样看来，想要像孩子一样快乐就要保持住好奇心。可新鲜刺激总归是有极限的，追求极端的事物难免有害身心。更何况随着年龄增长，我希望人生是稳定的、可以把控的，不想生活在新奇变换的马戏团里。

所以，童年的乐趣只属于童年，再也追不回来了。这份遗憾也使得童年更加珍贵。古诗云「夕阳无限好，只是近黄昏」。反过来说，正因为「近黄昏」，所以才更应该珍惜夕阳的无限好啊。现在的孩子们也过的越来越累了，小小年纪就要为课业发愁，还要学钢琴学奥数，把时间排得满满的。人生就这么一次机会，让童年一掠而过太暴敛天物了。已是大人的我，也要把童年的记忆好好收藏。我会永远记得，曾经有一个孩子，是那么的纯真快乐。

# 职业考生

当写简历或是做自我介绍的时候，一般都会提及自己擅长的事情。那些常见的说辞，比如说什么擅于交流之类的，实在过于表面，还有自我吹捧的嫌疑；说什么吹拉弹唱之类的，也不过是些私下里自娱自乐的爱好，没必要放在台面上来。要我诚恳地说出一件自认擅长，并且有实打实证据的事，那就是考试。我做了近二十年的学生，更确切地说，是做了二十年的考生。审视我之前的人生，会发现我大部分的正经心思都耗在考试上了。经历了无数的大小考，不含糊地说，我对于考试是经验丰富的高手。尤其是从初中到高中这六年，我付出的心血之多，足以称自己为职业考生了。

考试这件事，原本是用来考验水平的。考验一项具体的技术，通常可以搞得清清楚楚。比方说学炒菜，学得好不好只要炒盘菜试试就行了。但是在现代社会中，学习的内容五花八门，考生的数量庞大，考虑到效率和成本，不可能全靠实践来考验。无论是升学、入职还是各类证书，最普遍的考试方式就是笔试。只要准备好试卷，安排好时间地点，就能统一高效地测试一批考生，没有比这更方便的了。中国高考人数几度逾越千万，除了笔试别无他法。在笔试中，无论需要考验的究竟是什么，最后全都转变为一道道选择题、填空题、简答题。在这个过程中，考试的本质也就悄悄地产生了变化。

我是理工科的学生，中考、高考的科目、形式基本相同，都要考数学、语文、英语、物理、化学，高考比中考多了一门生物。乍一看，考试就是检验这几门科目的学习水平，其实则不然。下面逐一分析。

首先是数学。究竟什么是数学能力，这是个复杂的问题，我并没有明确的答案。但我很确定，想要在中高考数学考试中得高分，只要记忆与计算能力强就足够了，而且这两项能力都是可以通过后天训练的。数学考试需要记忆能力，因为考试中最基本、比重最大的题目都是检验是否记得课本中的内容，比如各类公式、性质、例题。只要把这些都背下来，即便头脑一塌糊涂，也能混个及格分数。计算能力不用多说了，数学题自然是要计算的。国内的数学考试把计算能力强调到极致，题量大而且步骤复杂。比起聪明才智，更考验计算的精准与熟练，力求让考生变成人形计算器。国人总将心算能力引以为傲，喜欢嘲笑外国人不会算数，恐怕根源就在这里。

比起实打实的数学题，语文题就有些虚无缥缈了。我上了十多年的语文课，除了识字和一些古文常识以外，几乎没能从中学到任何东西。语文课的内容基本就是读一些课文，然后教条式地分析文章结构和主题思想。课上的内容与考试没什么关系，不去听课也无所谓。语文考试实际上考查三种能力，记忆、写学生作文和揣测出题人的心理。记忆就是记住汉字正确的读音书写（因为各地方言问题，发音一字不差比想象中困难的多）、熟知成语、背诵古诗文等等，这只占了语文考试的一小部分。占比重最大的分别是作文和阅读理解。学生作文，尤其是这种考场上写出来的作文，是一种独特的文体，唯一的用处就是用来考试。除了少数剑走偏锋的勇敢考生，绝大多数考生写出来的作文都是议论文。开头一段说明自己的论点；之后分成几个分论点分别阐述，每段还要举一个名人事迹作例子；结尾重述论点，总结全文。写一篇作文的时间大概要限定在半小时，超过这个时间就有写不完的风险。因为大型考试试卷量大，阅卷教师不可能仔细阅读，只是大略浏览一下，给一篇作文打分平均只要一分钟。实际来讲，对作文分数影响最大的恐怕是书法水平，所以语文老师总是督促勤练字帖。阅读理解就更加玄妙了，几乎是一种心理游戏，目标在于揣测出题人的心理，到底想让人说什么。比如说一篇散文中描写了某处景色，题目问这段描写意义何在，出题人等待的「正确」答案可能是借景生情，可能是前后呼应，可能是升华主题，诸如此类。这种题目本应是开放式的，却限定了唯一答案，猜错了出题人的意图就会答错。有些原文作者心血来潮去答题，发现根本答不对，让人啼笑皆非。

英语考试相对比较单纯，就是检验英语水平，不过也很走极端。我在初中、高中学的都是哑巴英语，只注重读写，更确切地说是只注重语法与词汇，英语考试真正测试的也就是这两项。只要牢记各种词组搭配、动词变位，认得试卷上的单词，就能考高分，说不出、听不懂英语也没关系。在国内，即便是学了十多年英语的大学毕业生，大多数也都无法用英语交流。

物理、化学、生物这三门可以放在一起来讲。考试内容一言以蔽之，就是记忆科学常识和数学应用题。化学考试的一类经典题目就是往某某溶剂里加入某物质，再加入某液体，结果一会儿变颜色，一会儿变浑浊，问这些都是什么化学物质。化学就这样变成了一系列需要死记硬背的知识点。生物考试就更加死板了，比如简答有丝分裂过程，纯粹是背课文，以至于我和当时的同学一致认为生物应该算作文科才对。物理考试同样要牢记各种定律、现象，但比重更大的是数学应用题。比方说两个球形物体相互碰撞，电子在电场磁场里飞来飞去，然后问速度、加速度、位置等等，简而言之就是把物理定律作为隐含条件的计算题。

经过分析之后会发现，无论什么科目，想要通过考试说穿了就是记忆加上计算，有时再配合一些特殊的套路，至于科目本身学得怎么样并不重要。如果不重视考试的套路，往往力倍功半。比如说刻苦钻研文学，做生化实验，这些固然有益于专业技能，对考试却没什么帮助。作为一名职业考生，基本素养就是看穿了考试的本质，一切努力都为考高分服务。

没错，这种应试态度背离了教育的初衷。我自称职业考生而不是职业学生，正因为目标是「考」而不是「学」。这是应试教育的必然结果，可谓是求仁得仁了。在我的成长过程中，父母、教师、乃至整体的社会舆论，都在不断向我灌输考试的重要性，高考更是「一考定终身」。我的脑海中根植了一组逻辑清晰、不容置疑的观念：中考是为了考上重点高中，高考是为了考上重点大学，上重点大学是为了找好工作赚大钱。很明显，这其中并没有教育上的考量，没有思考过想要通过教育习得哪些技能、成长为什么样的人。因为要考，所以才学，不考的就不学，就是这么简单。我是理科生，不考政治、历史、地理、美术、音乐、体育，所以这些课都用来写其它科目的作业了。学校默认或说是鼓励这样做，后来就干脆把这些课都取消了，全换成语数外理化生，这简直再合理不过了。

初中高中的时间资源既充裕又稀缺。说充裕，是因为教学时间居然足够把同一套教材教两三遍；说稀缺，是因为再多的时间也应对不来无穷无尽的题海。乍看上去题海战术很盲目，是不可取的做法。可如果一个学生没日没夜拼命地做题，积累到一定程度之后就量变产生质变了。假如考卷上每一道题都见过，甚至做过十遍，还怕考不好么。当然这是件说起来容易、做起来极难的事情，靠个人意志是无法坚持的。国内的重点中学，师资质量是一方面，更重要的就是提供一个努力的环境。用监狱式管理，维护钢铁一样的纪律，使得学生别无他法，只能努力、努力、再努力。学校里周而复始地学习、做题、考试，在所有人心中树立统一的价值观，考试分数就是一个学生的存在意义、生命尊严。

一旦有了唯一确定的、而且是能用数字衡量的标准，生活一下子就变得艰难严苛了。每次考试都是一次折磨，考试之后公布分数排名更让人提心吊胆，一旦考砸了就如同公众羞辱。初中、高中时要月考，每次考试都是中高考的提前预演。我常在考前一周就陷入焦虑，每天忧心忡忡。上考场如上法场，仿佛就要英勇就义了。考场上最愁人的还不是难题，实在做不出来就算了。最讨厌的是看上去似乎能做出来，偏偏一时又想不出，想多琢磨一会儿又怕耽误时间，真是进退两难。步骤繁琐的题目更是揪心，生怕哪一步算错了，要是恰巧在考试快结束时发现计算错误，一霎那天崩地裂。考试全部结束之后，我开始为分数担忧。跟同学交流发现自己做错题目时，悔恨贯彻全身，像是被雷劈被雨淋，好久都缓不过来。等分数真的公布了，考得差自然难过，考得好也不由得心虚，平复心情又要好几天。等风平浪静了，下一轮月考差不多又要开始了。

我常常觉得，国内中高考考生与运动员颇有相似之处。都要艰苦训练，都要经受成王败寇的考验，都只有少数才能成功。在小小年纪便能承受这一切，并最终幸存下来的，都要有强壮的神经。最基本的就是吃苦耐劳，再枯燥的练习也能坚持下来。还有些具体的用来应对考试的技巧。举例来说，因为常常多门课连着考，我练就了用于调整心态的「切断」技能，一门课目考完之后无论好坏都再也不想，专心考虑下一门。再有就是，在紧张的时候也能正常发挥。所谓紧张，不就是心跳加速、呼吸急促、面红耳赤吗，只要这些生理反应不足以让我停止思考、写不了字，我就能继续考下去。每次考试都是一次脱敏治疗，让自己对考试越来越麻木，最后成功地变成一台考试机器。

我辛苦练就的考试本领没有白费，让我从小城市考到了大城市。大学毕业之后，又借学校声誉的光拿到了国外大学的录取。这些实打实的好处，是我所不能否认的。人生中的每件事，明里暗里都标着价码，没有白白得来的。为了这好处，我当然也牺牲了很多。

青春一去不复回。明明是朝气蓬勃、青春年少的年纪，却只能日复一日从早到晚伏案苦读，搞到眼也花了背也驼了，没有一点年轻人的样子。回想当初，我总是困倦，总是乏累，只要醒着就要为作业考试烦恼，每天真正属于自己的私人时间连一小时都不到。所以我总是对青春题材的文艺作品别有一种情结，那些热血的浪漫的青春故事只能发生在我的幻想中了。

除了这种显而易见的损失，这段经历对我性格、观念上的影响是更隐蔽也更持久的，直到现在也不能完全扭转过来。

我少年时好奇心强，渴望知识，对数理文史都极有兴趣。严苛的应试教育打击了我对学习的兴趣，让我条件反射式地把学习与考试连结起来。在习惯压迫式学习之后，一旦没有了考试目标，我就失去了学习的源动力。大学科目只要考个及格分数就能毕业，学那么好图什么呢？我对所有的功课都陷入深深的厌恶，整个大学阶段都是功利式地应对各项课程，没对自己的专业用过多少心。大学毕业之后我才渐渐地在实践中找到学习知识的乐趣，慢慢恢复到少年时的状态。

从少年到成人，最重要的是养成健全独立的人格。这本该是教育的职责，教育者要引导学生思考探索，逐步形成自己的世界观、人生观、价值观。而国内的应试教育在这方面完全是失职的。只有一个标准答案的填鸭式教育否定了独立思考，只要把正确答案记住就好了，没有什么好想的。暂且不提人生目标这样宏大的命题，我当初连高考之后要做什么都不知道。我只知道要考高分，考上名牌大学，可是进大学到底要学什么、将来要从事什么工作，我脑海里一点概念都没有。报考大学选择专业时，我只是按照录取分数高低，写了几个热门的专业，然后随机地进入了其中一个专业学习。那时我已经接受过十二年的教育，并且是同龄学生中的佼佼者，却这样糊里糊涂，难道不是一个荒谬的悲剧吗？这之后我用了几年的时间，才意识到要把控自己的人生，向着自己的目标前进，可时不时还是被旧日阴影笼罩，迷失生活的方向。

分析过得失之后，我思考假如能够重来，我有没有别的选择。思来想去，很遗憾地得出结论，重来一次还是会这样。人生就是有各式各样无法抵抗的苦难，不正确不合理的事多了，十之八九都只能强忍着。刚上大学我就发现了人生的不公平。我曾以为苦读是难免的，考大学就是要历经千辛万苦。谁知道上海本地的高中生根本不上晚自习，不用熬夜做题，只要学习水平中上就能考入外地顶尖学生才进的去的好大学。反过来说，比我更惨的也有的是。我读书时衣来伸手饭来张口，只要考虑考试学习。而穷苦人家出身的学生要先克服生活的苦，再挑战学习的苦。这还是在国内做对比，要是在世界各国之中做比较，高低差异会更悬殊。有多少骄奢淫逸，就有多少饥寒交迫。那是天堂地狱的差别，教育方式的不同简直微不足道。我处在这样的时代，这样的环境，这样的家庭，就是要经受这一遭考验，我没有足够的力量去反抗命运。

我自己只能如此这般，过去的事就过去了。将来的人能不能好些呢？国内教育的问题，明眼人都看得一清二楚，精研教育的人也不在少数，在理论上肯定能提出一套更好的教育方案。可是究其根源，中国教育的问题在于资源不足，没有那么多的好学校好教师，想接受好教育就得挤破头。中高考是人为设立的一道门槛，就是为争夺教育资源规定一套低廉高效、公平性高的游戏规则、筛选手法。只要国内承担不起因材施教的素质教育，应试教育就是所有学生躲不过的一劫。而且经过长年积累，整个教育产业链牵涉无数人的利益，应试教育本身就像一头匍匐在中国大地上的巨兽，让人无可奈何。退一步说，让无数孩子为了教育资源厮杀我都忍了，只当是国情如此，可能不能让规则不要那么残酷呢？能不能在大逃杀之余让学生真的学有所得呢？我只能盼望中国会越来越好，能给孩子留一条生路。每个大人都曾经是个孩子，少年们能茁壮成长，中国才会繁荣富强。

# 生于忧患

孟子云「生于忧患，死于安乐」，当代国人把这句话贯彻到了极致。中国人口众多，资源有限，分配不均，贫富悬殊，为了活下去就要拼要抢。要想赢过对手，最稳妥最直接的办法就是比对手付出更多。无论处于人生哪个阶段，都要殚精竭虑，忍辱负重，不敢有一丝松懈。

比如教育资源的争夺，为了获得良好的高等教育，就要和千千万万考生在高考考场上一拼高下。名义上是高中毕业时的一场考试，而真正的竞赛早就提前开始了。想要高考大捷，先要中考成功；想要中考成功，先要进重点中学；想要进重点中学，先要进对口小学；想要进对口小学，先要买学区房。如此种种，愈演愈烈，高考成了从出生开始倒计时的军备竞赛。家长们耗尽积蓄，孩子们从早到晚学到眼花背驼成了小老人，就为了那一场考试。

再比如工作机会的争夺。能不能找到好工作，首先要看你的学历和人脉背景。不用说，这两样事等到找工作时再下功夫已经太迟了。身为普通人，能做的就是压低身价，把自己贱卖出去。别人领一分钱做一分工，我领一分钱做三分工；别人吃不得苦受不得罪，我甘心吃苦受罪。明明是被压榨，还要美其名曰奋斗。如此恶性竞争，工作环境自然越来越恶劣。国内现在流行「九九六」制度，从早上九点工作到晚上九点，每周六天。如此做法明目张胆地违反劳动法，资本家还要说漂亮话：「年轻人就该奋斗」，「九九六是修来的福气」。

中国流行「成功学」，随处可见成功学的书籍、讲座，好像学会了诀窍就能脱颖而出了。那些宣传成功学的大师，有的是纯粹的骗子，指望着靠出书和演讲发大财；有的是自我吹捧的企业家，把成功都归因于自己的「优秀」。无论成功学说的多么天花乱坠，归结起来就是要人努力上进；如果你不成功，说明你还不够努力。我是想不出来，到底要努力到什么程度才算合格。更有甚者，干脆鼓吹社会达尔文主义，说什么优胜劣汰适者生存，将人类堕落为野兽了。

如此问题，大家都看得清清楚楚。要说解决办法，最简单的就是逃跑。人生这场游戏，从一开始就不公平。出生在安稳富裕的国家，从小就注定衣食无忧；出生在兵荒马乱的国家，从小就要为生存担惊受怕。如果环境实在太差，那就争取换个地方重新来过吧。最困难的办法就是迎难而上，改造环境，这需要莫大的勇气和智慧，而且不知道何年何月才会成功。

如果逃不掉又斗不过，那该怎么办？如果不想越陷越深，那就不要和同胞恶性竞争。

第一，放过自己，就是放过别人。从前面教育和工作的例子中可以看到，大家都是普通老百姓，被圈起来笼斗，互相竞争的实质是互相折磨。如果大家都不去砸锅卖铁买房，不削尖了脑袋往大城市、大公司钻，房价也就不会那么贵，加班也就不会那么狠。自己人团结起来，不自相残害，才能将利益最大化。博弈论里有「囚徒困境」的研究，对此分析得明明白白。

第二，降低欲望，可以让你活得更自由、更幸福。国内生活压力大，但是对于大多数人来说，还不至于吃不饱穿不暖，想活下去还是不难的。可是如果追求名利，非得「成功」，那就别怪求仁得仁了。把自己逼到绝处的，就是自己。放弃一些体面，就多得一些快活。

第三，人容易受环境舆论影响，追求的未必是自己想要的。弄明白自己到底想怎么活，不要盲目跟随大众。任凭他人争得头破血流，自己逍遥自在不是更好。

回到开头引用的孟子这句话。所有的格言警句都有两面性，不能一概而论。比方说，劝人谦虚，劝人自信，都没有错。但如果劝骄傲的人自信，劝自卑的人谦虚，那就错了。我以为，中国人已经够兢兢业业勤勤恳恳，不必再提醒「生于忧患」了。老子说「知足者常乐」，或许更贴切，愿与君共勉。

# 卷二 读书与写作 {-}

# 当我谈论读书时，我谈些什么

## 一

人无癖不可与交，这句话我深以为然。倘若一个人真的毫无癖好，多半是对生活缺少热情，和这样的人交往是乏味的。有癖好，却深藏起来，这样的人戒心强，难以拉近距离。通过一个人的喜好，可以深入了解这个人。一个人的读书清单、音乐列表、旅行足迹有时比一席长谈更能显露心迹。

我是个不爱出门的人，对社交的兴趣也有限。我最主要的兴趣爱好几乎都是室内的、一个人做的事情。年轻人的心性容易朝三暮四，好多沉迷一时的事物转而就抛掷一旁了。仔细想想，我从小到大一直都喜欢的，就是读书。

五六岁识字之后，我开始看一些童话故事和少儿科普读物。《格林童话》和《安徒生童话》都是早教的必读书了。上小学后我订了一些以童话为主的少儿杂志，里面的一些小故事现在还有印象。记得有一篇讲的是一头鲸鱼喜欢上了一艘轮船，误以为这轮船是自己的同类，可是不管怎么表达情感都得不到回应。就像这个小故事一样，不知怎的，美好的过了头的童话总会给我一种寂寞悲伤的感觉。与此相比还是科普书更能满足我的求知欲，这类书里的科学乐观主义总是鼓舞人心。从老家旧物堆里翻出来的《十万个为什么·地质篇》在很长一段时间里都是我的最爱，我从中学到了不少科学常识。童年学到的东西印象深，过了好多年还记得住。初中上化学补习班的时候，有一次我答出老师没有教过的内容，大概是黄铁矿是用来提取硫而不是炼铁，还让补习老师吃了一惊。这种知识就是从这本书里得来的。

读《十万个为什么》这些书，主要是满足了少儿的好奇心。第一本让我真正体会到文学趣味的书是《西游记》，初读时大概八九岁。《西游记》是幻想小说，情节生动有趣；加之我之前看过电视剧版，理解起来比较容易。所以年纪尚小的我能啃下这样一本大部头。

说到《西游记》，这确实是对我影响很大的一本书。随着年龄增长，小时喜欢的东西可能长大后就不以为然了，而《西游记》却是名副其实常读常新的经典著作。小时候读的是其中的妖魔鬼怪魔法神奇，长大后读的是其中辛辣的讽刺，乃至自我的修养。孙悟空的形象更是影响了我的性格。现在好多外国人对于中国人都有着保守内向的刻板印象，鲁迅更批评中国人有奴性，而实际上中国人的民族性格有着不畏权威、自由潇洒的一面，齐天大圣就是典例。

回归正题，我对读书的热情日渐增高，父母带我去书店购书成了最让我高兴的事。现在网购盛行，书店生意凋零，半数都停业了。可是实体书店有一个好处是网购比不上的，那就是对书籍的展示。那些五花八门的封面、漂亮的装帧很能激起我的好奇心，我每每靠着封面和标题来设想书中的故事，买回来一读才发现差了十万八千里。那时我最喜欢的是幻想、冒险题材，最早买的几本书我现在还记得起来：马克·吐温的《汤姆·索亚历险记》和《哈克贝利·芬恩历险记》，儒勒·凡尔纳的《十五岁的船长》，斯蒂文森的《诱拐》，赫伯特·乔治·威尔斯的《世界大战》和《莫若博士岛》……现在想想似乎有点奇怪，读的几乎都是外国作品。这其实是有客观原因的。由于之前社会的动荡，中国当代的通俗小说发展非常孱弱，像样的青少年文学更是几乎没有，这就使得我从小习惯了读外国小说。

小时零用钱有限，感觉书价颇贵，我每次只买一本，购书的速度远比不上读书的速度。我总是俭省着读，生怕太快读完了。记得曾读过一本名为《魔鬼出租车》的小说选集，其中收录了二十篇左右的科幻短篇，我原本每次只舍得读一篇，因为某次心情实在难过，就狠下心来把后半本书一口气读完了。对于童年的我来说，这已经是件奢侈的不得了的事了。

因为买书贵，我会想其它的办法来找书看。按说最容易想到的是借书，可惜我身边几乎没有爱读书的人。小地方文化建设也差，没有太像样的图书馆。这样一来，旧书就成了很好的选择。

爷爷家仓库里有些旧书，很快被我搜刮一空。这些旧书不知多少年没人碰过了，纸张焦黄，装订开裂，缺篇少页，还有股特殊的味道，习惯了之后居然觉得挺好闻。其中大多数是繁体竖排，我会认繁体字就是这时学的。此外标点符号特别多，有些像是专名号之类的，现在基本已经消失不见。这些书中有几本是旧小说，《西游记》《水浒传》《呼家将》等等，更多的是革命小说，《钢铁是怎样炼成的》《小矿工》《风云岛》之类的。我曾经很喜欢《小矿工》这本书，里面一些十来岁的孩子们搞革命的故事冒险色彩很浓，意外地和我的口味，可惜结尾处书页残缺，不知道结局如何，成了我童年的遗憾。这类政治味道浓厚的革命小说是特殊时期的产物，文学价值不高，现在很少有人读了。除了最有名的几本，多数早已绝版，想购买都困难。尽管是小时候饥不择食才读的，作为童年回忆，还是有些感情的，有时偶然想起，挺想找来看看的。

这点稀少残缺的旧书只能作为点缀，真正的满足我读书瘾的是旧书摊。我家附近有个旧书摊，小时候觉得有点远，现在想想其实也就是步行一刻钟的距离吧。一开始是父亲领着去，后来路走熟了就自己去；随身携带个小板凳，一看就是一天。因为我是小孩子，虽然一直光看不买，书摊老板也没说过什么。书摊不大，也就几百本书吧。这书摊的生意应该不是太好，每次去里面的书都差不多，没见卖出去过几本。里面的书五花八门，既有小说漫画杂志，还有辞典、工具手册，唯一的共同点就是一个「旧」字。一开始我看了不少漫画，《龙珠》《拳皇》之类的。后来发现小说太长还是得买来看，好在都不贵，我平常积攒的零花钱都用在这上面了。我买过的旧书包括大侦探波罗系列的《鸽群中的猫》《高尔夫球场的疑云》，梅格雷探案的《她是谁杀的》《梅格雷与疯子》，还有《基督山伯爵》。

在旧书之外，盗版书也是迫不得已的一种选择。我当时买的一些金庸古龙的武侠小说、卫斯理系列，还有《福尔摩斯探案集》都是盗版。这类广泛流行的通俗读物最容易盗版横行。盗版书纸张差，印刷差，看完一本书手指都染上了墨黑，更恼人的是排版错误，错字错到语句不通。除了最初贪图便宜买了几本，很快就下定决心这辈子都不要碰盗版书了。

说到金庸，我读的第一本是《射雕英雄传》。我有次和大姨一起租影碟来看，看的是《午夜凶铃》。大姨一边看一边织毛衣，看的哈欠连连，看完什么反应都没有。我则是吓得不行，连着一个星期睡不好觉。后来买了这套《射雕英雄传》，读到废寝忘食，很快就把贞子这个女鬼忘到九霄云外了，再提起也是当成笑话。要不是有射雕，搞不好我会多一个童年阴影。这也正证明了《射雕英雄传》有多么好看。

流水账似的写了这么多，把书目都列出来，是想强调下小时读书的影响。与成人后把读书作消遣、读完转眼就忘不同，小时读的书过了十几、二十年后依然留有印象，而且影响了审美趣味。因为从小读的熟，即便现在眼界不同了，还是对通俗小说别有一番感情。通俗小说有低级无聊、追求刺激的一面，同时也有对小说的源头、最本质的传统——也就是故事——的深刻挖掘。所以后来读到张爱玲对通俗小说的喜爱和借鉴，我是很能感同身受的。

## 二

小时候读小说是以故事情节为主，对文学技巧没有多少体会，大多数时候都是囫囵吞枣不分好坏。从表面上看，读小说是件再容易不过的事，只要识字就行。而实际上，一个人鉴赏力的高低，影响了他对一本书的认知。最早让我意识到艺术水准差异、将我引入新境界的，是《简爱》和《呼啸山庄》之间形成的对比。

两者相比较，《简爱》是更易读、更讨喜的一本。《简爱》充满激情，富有感染力，使读者陷入到女主角的情绪波涛中，为她的爱与恨所感动。而《呼啸山庄》是本神秘的书，虽然其中的情节也不过是爱恨情仇，却仿佛有种超自然的力量，奇特甚至恐怖。这大概因为，夏洛蒂·勃朗特再怎样感情真挚、敢爱敢恨，仍不过是个平凡的人，她所表达的没有超出她生活的范围。刻薄一点地说，《简爱》只是本高级的言情小说。而艾米莉·勃朗特是真正独树一帜的艺术家，《呼啸山庄》没有被题材所局限住，隐含着更广阔、更深远的意旨，充满象征的意味，里面的爱情超出了世俗的琐碎，更着重于人性奇妙难解的部分。

就像绘画和音乐一样，文学的精妙处也是难以用理性来客观分析的，短短几句没法说清《呼啸山庄》的好处。重点在于，《呼啸山庄》提高了我的审美趣味，使我对小说的理解更深了，不再停留于故事情节。我在法国读书时，曾有一位法语教师提到他认为《基督山伯爵》是世上最好的小说。单以故事情节而论，他或许是对的。可是小说的内涵太丰富了，真正的伟大之处耸立于故事情节构建的地基之上。

在这之后，我的阅读范围大大扩展，不再局限于有趣刺激的故事情节。我读了不少文学史和评论集，对世界文学的发展脉络有了认识，如同手持航海图的船员，兴致勃勃地四处探险。

就像很少旅游的人只喜欢去最著名的景点，我头脑稚嫩时读的书是最声名璀璨的，几乎囊括人类文明的最精华：唐诗宋词，莎士比亚戏剧，《浮士德》，《红与黑》，《安娜卡列尼娜》……这些古老的经典，总有让我感到莫名其妙的地方。古典诗词主题狭窄到令我震惊，为什么诗人总是怀才不遇？一旦得了功名为什么又总是羡慕田园生活？为什么总是在送别、思乡、伤春悲秋？我当初根本不懂得，并不是诗词总在表达同样的情感，而是人类共通的情感变成了诗。莎士比亚戏剧在我看来情节胡闹，语言造作。罗密欧与茱莉亚的形象不比童话故事中的王子公主更可信，哈姆雷特简直是个病入膏肓的拖延症患者。或许是翻译家的过错，莎剧台词总是夸张肉麻。好笑的是，好多年后我得知托尔斯泰对莎士比亚深恶痛绝，竟与我小时的观点不谋而合。

由于心智和经验的限制，青少年时读经典收获有限。然而，经典的影响是潜移默化的，在无意识中已经转化为成长的养料。这一点是我很久以后才意识到的。

如上所述，这些古典与我距离太远，并没有抓住我的心。随着青春叛逆期的开始，对我影响比较大的几本书是《我是猫》《围城》《第二十二条军规》以及《麦田里的守望者》。

《我是猫》虽然是小说的形式，但是故事没头没尾，打乱顺序来读都无妨。《我是猫》借着猫眼看人来评判世事，对我而言可以说是讽刺小说的启蒙。恰巧我读的第二本夏目漱石的小说是《哥儿》，也采用了类似的手法，以至于在很长一段时间里我误将夏目漱石与马克·吐温归为一派。

《围城》在文字辛辣幽默上更胜一筹，我曾经非常喜欢。但是《围城》过分追求佳句，没有一处甘心平铺直叙，读起来像是小品文大杂烩，在格调上落了下乘，长大后就很少再读了。

有了前面两本有趣读物的铺垫，我轻而易举地爱上了《第二十二条军规》。这本书技法高超，几乎令人眼花缭乱，从开篇第一句就辉煌灿烂，独特的风格贯彻始终，像台风般袭卷肆虐。直到若干年后我读到《百年孤独》，才重新感受到这样强烈的体验。同样是幽默讽刺，这本书讽刺的对象不是一时一事，而是战争、国家、社会乃至人类的生存境遇。这本书也是我与怀疑论和存在主义的初次接触。

相比之下，《麦田里的守望者》更简单直白，更贴近青少年，对我的影响也更直接。在懵懵懂懂的年纪，我就对校园中官僚、形式主义的那一套不以为然。读完这本书，我更是打从心底蔑视道貌岸然、虚伪浅薄的种种人物与现象。

青少年时期的阅读经历和我的性格形成互为因果：我的性格使我偏好某类书，阅读这类书又强化了我的这种性格。我所读的书，最终导致我之为我。

## 三

升入初中之后，我开始阅读哲学书籍。两本起到入门引荐作用的书是罗素的《西方哲学史》和冯友兰的《中国哲学简史》。这两本书深入浅出，是极好的启蒙书。同时这两位又都是大哲学家，自然不会满足于简单的介绍，借由评判各家，也间接地阐释了自己的思想。

以此为指南，我陆续读了一些哲学著作。读文学的时候，我是旁观者的心态，读之前也不会有太多成见。哲学涉及到许多具体的问题，我自己早已有了一套观点，阅读过程更像是一场对话，有时聊得很愉快，有时则是激烈的争吵，这是很有意思的体验。我读《论语》这样的书，有时会觉得索然无味，因为其中的观点已经深深植入到中国传统之中，我在潜意识里已经默认是正确的了，读起来像是重复啰嗦一些理所当然的事实。而读《理想国》的时候，我却觉得很多观点都难以接受，真希望能加入到对话中，直接对苏格拉底发出质疑。

初中时我最感兴趣的两位哲学家，一位是弗洛伊德，另一位是柏格森。这两位都对现代文学有深远的影响。作为文学爱好者，我偏好他们也是理所当然吧。我买到过一本影印版繁体竖排的《梦的解析》，仔细研读后还试着对自己的梦进行记录、分析。柏格森薄薄的小册子《形而上学导言》对我造成很大的影响，使我第一次认真思考理性与本能、时间与空间的关系。有趣的是，罗素与柏格森的思想是完全对立的，在《西方哲学史》里对柏格森大力批判，未料到我却喜欢上了后者。我当年一直很希望读《创造进化论》，可惜一直找不到；现在很容易买到，却没有兴趣读了。好多年过去了，在我眼里精神分析已经成了伪科学的代表，弗洛伊德的理论大半是错误的。柏格森的理论是动人的，文笔又极好，当成文学来读是很好的，但是他的糖衣包装下的哲学观点是有漏洞的，他对数学与逻辑的理解不够深，对理性的批评并不是很有力。

限于年龄与学识，我阅读哲学著作都是浅尝辄止，甚至不确定自己到底读懂没有。比起具体的哲学思想，我最大的收获还是尝到了思考的乐趣，获得了抽象思维的训练。通过柏格森，我接触到了威廉·詹姆斯的实用主义思想，后来成了我思想的重要来源。

再回到文学方面。我中学时读的作品基本都是二十世纪的现代派小说。这些风格前卫、特立独行、晦涩难懂的作品正好符合了我青春期时的心态：心高气傲，总喜欢故作深沉，表面扮酷又暗中想要引人注意。回想年轻时的样子，真是既可气又可笑。

第一位引我上路的标志性作家是卡夫卡，人变甲虫的故事恐怕是很多人对荒诞小说的第一印象。他的写法是奇特的，对于不久之前还在读古典的我来说尤为惊人，原来小说还能这么写。卡夫卡的小说在细节上努力保持理性客观、语言平铺直叙不做雕饰，整体上却荒诞不经。他的小说就像是对梦的描述：当我们从梦中醒来，回忆梦的内容，努力寻找逻辑线索把梦中混乱的内容串联起来，却始终无法挽回梦境的荒谬。弗洛伊德的理论在这里派上了用场，我像侦探一样搜寻线索，卡夫卡和他父亲的紧张关系、三次解除婚约都是解谜的重要提示。后来我终于放弃了这种探索，原因在于，我相信作品是独立于作家的。当我开始阅读一本书，它就成了独立的存在，允许我做出自己的诠释。作者何许人也、本意如何，对读者来说并没有那么重要。对我来讲，卡夫卡小说就是对极权尖锐的讽刺和批评，是充满现实意义的，与我几年后读的《一九八四》异曲同工。

另一位奇特的作家是卡尔维诺。读他的书像是一场幻想冒险，又像是在做游戏，新奇有趣。《命运交叉的城堡》用塔罗牌来构建叙事，一副牌组就成了一个故事；《看不见的城市》像是一组寓言诗；《宇宙奇趣》以科学理论为基石大开脑洞；最有意思的还是《如果在冬夜，一个旅人》，做足了与读者的互动。有趣归有趣，我的欣赏之情还是点到为止。我对卡尔维诺，以及其它千奇百怪的现代派文学的看法始终是形式大于内容，过于执着于表面上的创新。

与前面两位相比，博尔赫斯是更学者式、书斋式的。他博览群书，知识渊博，复杂的思考对于他是精致的娱乐。读他的书，总是联想到他在书海中轻松自如、游刃有余地徜徉，总能体会到其中散发出的一种知识分子式的闲情逸趣。据说他曾研读《庄子》，这件事完全符合我对他的想象。我不是闲适阶级的人，更没有出世的思想，虽然读他的小说每每觉得隽永精悍、饶有趣味，却总是有一层隔膜，像是双脚悬在空中踩不到实地。

我当时读书多数是出于好奇心，想看看文学到底有多少种不同的面貌，结果读完像是擦肩而过，没在我心中留下一点痕迹。比方说以色列作家阿格农的《大海深处》，我现在一点内容都回想不起来，只记得这个漂亮的标题。还有法国新小说派娜塔莉·萨罗特的《天象馆》，我如今只记得四处泛滥的省略号了。我试图挑战《尤利西斯》，一开始虽然读得不明不白，好歹对话和人物塑造都是中规中矩的，随后一章一个写法，越来越混乱，越来越奇怪，直到每一段、每一句话都撕裂变形成毕加索的抽象画，一点都读不下去了。

我没有书友交流，没有前辈引导，只是从一本到另一本书，自由野蛮生长。这种布朗运动式的四处乱撞，加上年纪小缺乏生活经验，自己搞出来的书单必然是奇形怪状的，把自己弄得好像是研究方向刁钻古怪的文学博士。很多时候，既没有多少精神上的收获（有些书压根一点都没读懂），也没有多少阅读的乐趣（合不合口味全凭运气）。年轻时好高骛远，走些弯路是难免的吧。这是我阅读纯文学最频繁的时期，接触了好多人一辈子都不会碰的书，最起码也算是见识了文学的多样性。

在这种广撒网的策略下，我还是遇到了心仪的作家，当时最喜欢的是纪德和茨威格。这两位都可以称之为古典与现代交界处的作家。他们成长于十九世纪末，深受欧洲古典传统的影响，甚至可以说他们的代表作没有超出传统小说的范围；与此同时，作品的内核又拥有现代精神。比起奇奇怪怪的现代派，我还是更认同这种有继承又有发展的做法。同时，纪德既反叛又传统的矛盾性，茨威格对心灵微妙处细致入微的描绘，正好与我青春期躁动敏感的状态相契合。

这时我也开始尝试写作。读的书很杂，写出来的东西自然也很乱，有时是仿卡夫卡的荒谬故事，有时是象征主义的散文诗，有时是颠三倒四的意识流。我热衷于搞些愚蠢的小把戏，考虑过通篇不用标点符号，或是每句都反过来写——总之就是些青春期荷尔蒙作用下搞出来的、长大后再看会很尴尬的东西。

即使是最头昏脑涨的时期，我也是缺乏浪漫气质的，甚至对浪漫化的事物持有警惕、反对的态度。我很少读诗，尤其不喜欢宗教式的、神秘主义的作品。究其原因，我从小就是个理性派。中国最占主导地位的传统儒家思想是非常务实的。中国现代教育中贯彻的马克思主义，也是推崇客观理性，反对一切唯心主义、虚无主义、神秘主义的。人的心理是非常复杂难解的，没有简单的因果关系。最起码，我相信文化传统和学校教育都是我偏向理性的重要原因。

所以，我做了所有「文艺青年」做的事，却没成为一个「文艺青年」。无论是现代文艺青年们所热衷的流浪远方，还是古代文艺青年们所热衷的田园归隐，在我眼中都有浅薄、自我感动的嫌疑。幻想流浪的最终还是在职场朝九晚五，幻想归隐的最终还是领着朝廷俸禄，或者更惨只能抱怨怀才不遇。真正贯彻理想主义的人是勇敢的，沉溺于幻想中的人则是可耻的。

## 四

从初中升入高中，第一件事就是文理分科。我初中成绩最好的科目是物理和数学，老师家长们的普遍看法也是男生就要选理科，所以我高中就选择了理科。之后好多年，我偶尔会跟父母、朋友们谈起，既然我的爱好集中在文学、哲学方面，如果当初选择文科也许会更适合我。现在想想，选择专业要经过多方面的考虑，学校提供的文科教育并不与我的个人喜好相吻合。我相信理科是正确的选择，后来的工程师教育也符合我的期待。

我在全市最好的高中度过了人生中最痛苦的三年。我在国外讲起中国高中生的地狱式生活，很多人都不相信。除非亲身经历，外人恐怕难以想象其痛苦的程度。早上七点上学，晚上十点半放学，中间只有一小时的午休和傍晚四十分钟的晚饭时间。周末也得不到休息，每周只有周日下午半天假，这半天还要应对各科老师留下的作业。总之是永远上不完的课，写不完的作业，考不完的试。每次月考之后的排名更是比考试还可怕，学生由人变成了一个数字，只靠这个数字被人评判。

我每天的私人时间是极其有限的，一定要精打细算。家里在学校附近买了房子，走过去只要十分钟，我午饭晚饭都可以回家吃，这是个巨大的优势。中午休息一个小时，除去来回路上二十分钟，吃饭用十分钟，还剩下三十分钟。同样的，晚饭四十分钟休息，除去赶路吃饭还剩下十分钟。这两项加起来就有四十分钟了。晚上放学后还有一段时间，不过那时我整个人已经差不多被榨干了，睡眠时间是更稀缺的资源，我顶多拿出半个小时的时间。每天加起来一个多小时的私人时间，就是我生存下来的精神支柱。周末除去作业能有几个小时的自由时间，是每周最快乐的时光，如同久旱逢甘霖。

在这种情况下，我当然不能像初中时那样着了魔似的博览群书。我选择了更轻松、更娱乐的爱好来减压，读书在我的爱好排位中跌落至第二甚至第三位。那时我最大的娱乐是看漫画（广义来讲也算是读书了），漫画里的日本高中生总是无所事事，生活总是以学生社团和恋爱为重心，在我眼中简直比星球大战还要梦幻。后来又喜欢上看美剧，电视剧可以边吃饭边看，比其它娱乐方式更加节省时间。

即便如此，读书对我还是很重要。阅读带来的深度快感，不是动漫影视能替代的。如果说初中是我的摸索期，高中则是逐渐确定自己的口味，虽然读的少了，但是每一本书的分量却更重了。

值得一提的是，高中时家里终于安装了网络。在我心目中，互联网是可以与造纸术、印刷术相比拟的伟大发明，彻底颠覆了信息传播的方式。感谢互联网，我有了更大的阅读自由。

这段时间里对我影响最大的应该是《一九八四》。这本书与我的思想十分契合，像是帮我把我想说的话说出来。书里对极权主义的批判是如此深刻有力，时至今日仍然发人深省。不过比起小说，这本书更像是篇政治论文。这也引起我的思考，文学的内容有多重要？中国的文学传统讲究文以载道，雕饰华丽流于表面的作品难登大雅。而西方的文学有为艺术而艺术的倾向，似乎只要艺术水准高超，内容其实是无所谓的。对于这个问题，当时我没能给出答案。

《一九八四》的思想性占了很大比重，在艺术上也是出色的，我尤其欣赏其中客观冷静的文字风格。另一位作家的文风与其颇有相似之处，那就是毛姆。我连着读了毛姆的三本书，《月亮与六便士》《人性的枷锁》和《刀锋》，全都非常喜欢。《麦田里的守望者》中有一段提到，「我」(主人公)最喜欢的是这样一类书，读完之后会想要给作者打电话，成为要好的朋友，随后就说不想打电话给毛姆。如果可能，我倒是非常想给毛姆打电话。在我眼中，毛姆是个风趣幽默、通情达理的人，要是能和他一起结伴旅行一定很有趣。这也意味着毛姆是个常人，因为真正的天才都是很难相处的。毛姆的观察力非常好，可是碍于自身的高度，写出来的小说没能到最好那一档，跟伟大艺术家始终有差距。讨人喜欢的不一定好，好的不一定讨人喜欢，很多事情都是这样。

再有一位我颇为喜欢的作家是约翰·勒卡雷，他的《冷战谍魂》（也有译作《柏林谍影》）是我读过的最好的悬疑小说，水准已经大大超出通俗小说的范畴了。威廉·戈尔丁的《蝇王》的写作风格也十分符合我的审美，不过里面的性恶论令我难以苟同。

前面提到的几位全都是英国作家。各国文学都有自己擅长的文体。比如中国的诗是顶好的，小说方面除去少数几本佳作，总体来说乏善可陈。客观来说法国小说和俄国小说要比英国小说成就高，我却更喜欢英国小说，这纯粹是个人偏好。

我也读了很多流行小说。越临近高考，我读的书就越轻松，到考前几个月只读的进去《哈利·波特》了。当时最热衷的作家是斯蒂芬·金，他的小说我读了十来本，其中《宠物公墓》是第一本吓到我的恐怖小说，《秘密窗》是我第一次读英文版小说。那时英文不够好，边读边查词典，很费了一番功夫。长达七部的宏编巨制《黑暗塔》是他最杰出的代表作，可以说是通俗小说中的丰碑，唯一的遗憾是结尾有些唐突。我高中毕业时中文版才出到第六部，最后一部是到大学才读的，结局让我恼火了好一阵。

单从文学水准上来讲，斯蒂芬·金只能算一般。他文笔啰嗦，塑造的人物也很有限。主角一般都是个普通的、关键时刻却能拿出正义感的中年白人男性，每部书里都有个善良、早熟的小孩子，邪恶的大反派更是所有通俗小说的标配了。依我看他在艺术上的巅峰就是《肖申克的救赎》《尸体》《亚特兰蒂斯之心》这几个中篇，长篇只有娱乐性而已。但是，为什么要低估娱乐的价值呢？为什么一本书能给成百上千万的读者带来快乐，在文学评论家眼里却完全不入流呢？高雅与通俗、艺术与娱乐之间的关系，也是我后来常思考的一个问题。

回过头来继续说斯蒂芬·金，虽然他的小说艺术价值有限，娱乐性却极强。我有一个关于通俗作品的想法，无论文学影视，通俗作品的娱乐性都是旧不如新。跟纯粹的艺术创作不同，娱乐元素是像工业产品一样不断发展的。一个成功的手法被发明出来，就会被之后无数的作品模仿借鉴。福尔摩斯和华生的形象不断地在侦探作品里出现，希区柯克式的悬疑手法被反复借鉴，一个成功的娱乐元素会被不断地打磨完善。早期的侦探小说里死个人就算很刺激了，现在的日本推理小说不花样齐出死上四五个人都不算凶杀案。斯蒂芬·金能成为当代畅销小说之王，一个重要的原因就是他站在了美国娱乐产业的基础之上。根据他文章中的自述，他的阅读量是非常大的，跟影视界也走的非常近，代表作《黑暗塔》混合了科幻、奇幻、西部、冒险、恐怖、悬疑种种要素，可以说是通俗文化的集大成。当然只有这点还是不够的，光靠模仿借鉴只能写出流水线式千篇一律的娱乐小说。斯蒂芬·金有惊人的想象力，出色的故事天赋，几十年来一直有新创意，这是非常了不起的。

斯蒂芬·金是综合式的通俗小说作家，不局限于某一分类。专注于特定类型的小说家，往往走上更狭隘的道路，和艺术的距离更远。阿瑟·克拉克是我高中时很喜欢的作家，此前我对科幻小说的认知还停留在《海底两万里》和《世界大战》，他的《童年的终结》和《2001太空漫游》都令我耳目一新。他的小说几乎没有人物塑造，所有人物都是功能式的，纯粹是为了推进故事发展，故事情节也相当简单。他的小说好就好在「科学幻想」这四个字上，靠着细致入微的技术描写营造真实感，通过与外星高等文明接触这类情节让读者思考宇宙的宏大、人类的渺小。有时我会觉得，不如直接写成科技读物算了，没必要非得写成小说。有没有可能一本书不是好小说，却是好的科幻小说？同样的，侦探小说是不是只要想出一个好诡计就行了，文笔什么的无所谓？通俗小说很大程度上是以大众的接受程度为评判标准的，如果足够受欢迎，满足了一部分读者群体的需求，其余的或许怎样都无妨。但我始终还是希望一本小说是广义上的好小说，不单单是某一特定标准下的佳作。

总的来说，我高中时的阅读生活还是很充实的。因为是在夹缝中挤出时间、甚至是牺牲睡眠换取读书的机会，那时读的书对我来讲有种共患难的情谊，是格外宝贵的回忆。

## 五

高考顺利考入一所上海名校，离家去上海的情形我还记得清清楚楚。这是我第一次出远门，临走时最惦记的还是家里的一柜书。我把书细心整理好，撒上樟脑丸，叮嘱家人注意不要让书籍受潮。未曾料到，好多年过去了，我再也没见过这些书。我到上海后，父母随即搬到唐山，书籍难搬，都留在了东北老家。大学期间我一直没回过东北，毕业后又去了法国留学。前阵子母亲告诉我说老家楼房要拆了，跟我商量要不要把那些书卖掉。曾经珍贵的收藏，或许就要永别了。

话虽如此，我内心并没有多少伤感。我最近几年形成的一个观念是，不要为一件物品赋予过多的意义。既然这些书我都读过不止一遍，它们的价值已经实现了。而且这些书版本都很普通，若有需要随时可以重新购买。我承认这种想法是有些不近人情，我自己也并不能完全遵循。拥有一件物品时间久了，哪怕只是一支笔，一个杯子，总会投入情感在里面。物质的东西有始有终有生有灭，早晚会消失。从小物件着手，我希望自己少些牵挂。

小时候我嗜书如命，与现在的想法截然不同。那时我对书籍极为珍稀，从不会折页或是在书上写字，恨不得读完之后还像本新书一样。小学毕业时得到校长赠书，她在扉页写上「君子博学而日参省乎己」，我心里还嫌她字丑弄脏了书。我的书自然是概不外借。曾一时兴起跟同学谈到某某书如何如何好，同学提到跟我借这本书时我就后悔了，最后想出来的馊主意是声称根本没读过只是在瞎吹牛，现在想想真是尴尬。这种爱书的心情，和小孩子对心爱玩具的重视是一样的。就像儿时的玩具最终往往会无缘无故地消失不见，这种心情也不知不觉地消退。

再继续说上大学这件事，我学的是计算机专业，还辅修了法文。进入计算机学院是有些偶然的。高中教育一切为了高考，根本没有考虑过将来的专业选择和职业发展，学生报考专业都很盲目。我按照热门程度，由高到低填了六个选项，计算机是第四个。学法文也是兴之所至，没经过深思熟虑。我们大学有和欧洲交流的传统，一直有开设丰富的外语课程。学外语是件费力的事，不经过正规的课程很难学好。我想假若在大学时不抓住机会，将来恐怕再也没有学成一门外语的可能了；欧洲文学中，英国之外我最偏好法国，于是就选了法语。当时法语班里的同学都比我年纪大，都是快毕业了打算出国留学的。结果这群人里只有我最终来了法国，人生真是难以捉摸。

大学是我人生中最快乐的时光。从高中监狱式的生活解放出来，又是第一次离开父母，刚入学时整个人都浸没在兴奋的情绪里。住宿生活也让我觉得新鲜，好像是野营一样，每晚和室友们谈天说地到凌晨。每天早上醒来都觉得充满了昂扬的斗志，有耗之不尽的精力。

中国大学的特色是严进宽出，一旦跨过高考这道坎，大学里的课程是非常轻松的。只要期末考试那一周努努力，就能混个不错的成绩。我平时闲得很，除了和朋友出去玩，其余多数时间都泡在图书馆里。学校的图书馆有十几层，藏书百万册，宽敞明亮，是个舒服的所在。图书馆的人流量是极其规律的，平时很空旷，每逢考试则人满为患。我反其道而行之，正好避开人潮。每学期开学一个月之后，补考陆续结束，开学时许下努力学习的宏愿的人也都倦怠了，图书馆也就门可罗雀，这时最适合去读书。抱上几本书，随意找个清静的角落，我常常一读就是一整天。

我的专业是胡乱选的，课程又不紧张，自然懒得用功，读书依然以文学为主。大学里我读了三百多本书，结合图书馆档案记录和自己的笔记，我手上有一份完整的读书清单。浏览下这份清单，审视自己读书的思路，是很有意思的一件事。

最开始我选书的方针是对过去的补完，通读喜欢的作家。纪德，毛姆，还有奥威尔，能找到的书我都找来读。芥川龙之介和茨威格的短篇小说，综合几个不同的选本，差不多读全了。特别值得一提的是夏目漱石。夏目漱石的小说我之前只读过《我是猫》和《哥儿》，其它都求之不得。图书馆里夏目漱石的作品收的很齐，我从《三四郎》一路读到《明暗》。按照创作顺序挨个读下来，能从中发觉作者风格的演化，这种研究非常有趣味。夏目漱石的写作笔调从轻松到严肃，心理描写越来越细致深入，早期作品还给我马克·吐温式幽默小品的感觉，后期笔法越来越浓密沉重，《明暗》已经完全是法国心理小说的路数。只有一直以青年为主人公这点是前后贯通的，可以说是个青春小说家啊。

一个作家读多了总是会腻味。夏目漱石前后风格不同，我当初恰好只熟悉一种风格，于是有了重新挖掘的机会。而其他作家都是都是直接从代表作开始读，起步就是最高峰，之后每况愈下。再好的作家，读过五六本之后，也很难再发掘什么新的东西了。反复读同一个作家，沉溺于熟悉的感觉中，有种旧地重游的轻松感。曾有一段时间，每当我想要舒缓压力的时候，就找本毛姆的散文游记来读。这种放松的心态给我一种不求上进的感觉，让我最终放弃了这种读法。

这时我忽然发现，自己不知不觉中读了很多日本文学。就像收藏者的心态一样，一类事物收藏得越多，就越想要集齐，我也就有意地去读日本作家。明治维新以来的现代文学，战前的森鸥外、岛崎藤村、武者小路实笃，战后的太宰治、坂口安吾，往后一些的远藤周作、司马辽太郎，再到当代的村上春树，我都是在大学时期读的。日本文化自古以来受到中国的影响，审美上与中国文化比较接近，读起来比欧美文学更亲近，少了一层隔膜。又因为日本和中国一样都经历过从传统到现代的文化剧变，新文学上的一些探索是共通的，中国受到日本文化的反哺。现代汉语有很多借自日语的词汇，以鲁迅、周作人为首的一批作家都有日本留学的经历，这些就不深入说了。总而言之，读日本文学，无论是为了阅读趣味还是学习借鉴，都很有价值。随着了解的深入，我逐渐发现中日文化表面上相似，实际上有很大差异，很多时候似是而非，慢慢地兴趣就淡了。

在补课式的阅读熟悉作家和集邮式的阅读日本文学之外，我精挑细选经典名著，希望能在思维、艺术审美上有所提高。之前小学、初中、高中这几个阶段，总会有几本书让我豁然开朗，对我的成长施加很大的影响。升入大学之后，我主动地寻找阅读生涯中新的里程碑，却一直事与愿违。当我抱着「这本书要促使我成长」这样的功利心态，很容易期望过高，读完之后感觉不过尔尔。个人的成长不是升学考试，没有办法提前规划。依照我的个人经验，读书是成长的催化剂，这催化剂要如何发生作用却只能听凭机缘巧合。我读《第一哲学沉思》，读《金刚经》，读《战争与和平》，读《百年孤独》，老实讲都没受到什么影响。小时出现类似的情况是因为没读懂，这时则更多是由于志趣不相投。

大学时真正影响我的书，总共有两部半。

半部是威廉·詹姆斯的《实用主义》。我的思想有四个主要来源：长年、系统的科学教育；深入骨髓的中国传统文化；以中日欧美为主的近现代文学中蕴含的人本主义、自由主义精神；最后是自己切身的生活经验。在接触了各式各样的哲学理论之后，与我既有思想最契合、最能够付诸实践的就是实用主义。说是半部，因为读之前我对威廉·詹姆斯的思想就有所了解了，最早在初中就读过《实用主义》的选段，于我而言并不完全是新书。

另外两部书是《卡拉马佐夫兄弟》和《红楼梦》，这两部书是我心目中文学艺术的最高峰。

在诸多文学形式中，我最推崇小说。诗，以及各式各样的韵文，是纯粹的文字艺术。单以美学价值而论，诗或许是最高级的文学形式。诗的弱点是受到形式的禁锢，是带着镣铐的写作，能表现的内容是有限的。严谨的逻辑分析，细致入微的现实描绘，是难以套入到格式和韵脚中的，即使能做到也是削足适履。散文与小说的区别其实只在于内容是否虚构，因为不能发挥想象力，散文的意义体现在内容本身，比如叙述了有价值的事实或是阐述了一种观念。在我看来，最好的散文是哲学和历史著作，而这些著作有自己的学术目标，并不会以身为文学为荣。戏剧的完成体在舞台上，剧本只是戏剧的基础。作为文学而发表的剧本，在数量上要远低于其它文学形式，这是有客观必然性的。小说可以追求文字美，可以探讨理念和事实，可以有戏剧冲突，集合了众家之长。在经历过二十世纪的现代派探索后，小说更是扩展到更远的范围，不拘于任何形式和内容。

什么样的小说才是最好的呢？故事是小说最基础也是最粗糙的一面，设置悬念、情节起承转合、保持读者的好奇心，这些比起艺术来说更像是一门手艺；漂亮的文字是表面上的美丽装饰，只有有限的价值；形式的探索实验，像是一个工匠对锉刀、钻头的兴趣大过了工艺品本身，在我看来不是条正路；哲学思想可以作为小说的创作方针，统领主题，但小说家毕竟不是思想家，阐述思想也没必要套一个虚构的外壳。人的艺术始终是以人为核心。在我看来，最好的小说是传达了为人的体验。阅读这样的小说，间接扩展了人生的宽度。

很多人觉得陀思妥耶夫斯基的书艰涩难读，我却很容易投入进去。陀氏小说的故事情节很受哥特、浪漫主义的影响，他的四大名著（《卡拉马佐夫兄弟》再加上《罪与罚》《群魔》《白痴》）都可以概括为「凶杀始末」。他的小说有很强的戏剧性，可以套入多幕剧的结构。开场时人物很有神秘感，中场必有一次人物间的激烈碰撞，结尾总以犯罪或救赎收场。他笔下的人物总是处在崩溃边缘，总是有剧烈的内心挣扎，痛苦和悔恨贯彻全身。他的小说有巨大的感染力，把灵魂深处最阴暗、最痛苦的一面展示给世人，再祈求通过宗教的力量得到拯救。他对人生和社会的想法我基本全盘否定，觉得过于消极，但这无损于小说的价值。这也应了我前面的说法，小说家没必要是思想家，小说也没必要包含对人生的解答。能够传递对善恶的思考，对灵魂的拷问，让我怜悯为人的苦难，让我思考要怎样生活，这就是一本伟大的小说。

《红楼梦》是中国传统美学的集大成，历朝历代文人的情趣都包含其中，这自然已经是极伟大的了。更了不起的是《红楼梦》对人生的描绘和提炼。由于艺术水平所限或是创作需要，多数小说中的配角只不过是充当背景陪衬，甚至连主角都可能是扁平干瘪的。《红楼梦》中的人物，无论戏份多小，却都是立体鲜活的。虽然我们跟随者作者的叙述视角，只能用余光看到这些配角，却意识到这些配角也是活生生的人，也会有可歌可泣的故事。这是人生的客观描绘，真实的人生是不分主角配角的。再有，《红楼梦》是反戏剧化的。《红楼梦》里的悲惨情节与《卡拉马佐夫兄弟》相比有过之而无不及，却都轻飘虚幻地一笔带过了。无论美丽的还是丑恶的，最终不过是梦枕黄粱一场空。时间是中立的，无情的，人生最终会变成一段往事。《红楼梦》耐咀嚼的程度是令我惊叹的，每次读都会有新的感受，仿佛有真实人生的容量和深度。可惜这本书没有写完，否则就是当之无愧最伟大的小说，而不是最伟大的小说之一。

## 六

读过《卡拉马佐夫兄弟》和《红楼梦》之后，很有种曾经沧海难为水的感觉，对其它小说的兴趣都淡了。从大学后期到留学法国这几年，我很少认真研读严肃文学，多数时候是读通俗小说来消遣。

更重要的是，这几年是我踏入社会的重要转折，现实也不允许我寄居在象牙塔里了。

先是毕业的日子临近，无论求职还是继续升学都至少要提前一年准备，我怎么能安心去啃大部头的文艺著作呢。

选择留学之后，学外语、考试、申请学校、办签证，事情一件接着一件，中间有不少提心吊胆的紧张时刻；同时还要做项目、编代码、写毕业论文，校里校外都不缺让人发愁的事。

大学毕业后来了法国留学，刚来时法语不够好，生活中的不方便、不适应就不用多说了。这是我第一次独立生活，洗衣做饭什么都要学。学校课程很紧张，有时感觉又回到高中了。早上天没亮就起床，糊弄一口早饭之后坐班车去学校。上一整天的课，以很勉强的法语水平拼命记笔记跟上老师的节奏。晚上放学时恰好是交通高峰期，挤公交已经够心烦了，还每每遇上堵车，在公车上站一两个小时才到家。回到家里做饭、打扫、写代码、做习题，都忙完已经很晚了。这时我早已精疲力尽，再伟大的艺术也进不了我的法眼了。

就像高中最辛苦的时候我沉迷漫画一样，这几年我也选择了更轻松的娱乐方式。最主要的是电子游戏，游戏都懒得玩时就看看电视剧、动画和综艺节目。曾经很长一段时间里，差不多每一顿晚饭都要由台湾的谈话节目《康熙来了》作陪。

话题回到读书上来。我这段时间里读的书，基本都在科幻、奇幻、悬疑、武侠和轻小说这五个门类里。

科幻方面，阿西莫夫的书我读了很多本。阿西莫夫的文字风格，往好听了说是朴实无华，往难听了说就是枯燥无味，简直是中学生作文的水平。阿西莫夫的厉害之处在于知识渊博和想象力丰富，只要把他的想法清晰地表达出来，就成了一篇好科幻，完全不用顾虑文字好坏。《沙丘》《严厉的月亮》都更有小说的样子，《光明王》《海伯利安》则称得上是漂亮的小说了。还有一本令我格外喜欢的是《安德的游戏》。卫斯理的小说我也读了不少。总之都是些受欢迎的科幻名作，这里就不多提了。

奇幻方面，我最喜欢的是《冰与火之歌》。我读完原著第四部时，HBO翻拍的电视剧才开播，现在这部书更加流行了。其余还有「地海」系列、「夜访吸血鬼」系列、「守夜人」系列什么的。奇幻小说的特色就是长，非得出好多部才罢休。我对奇幻的喜好比较有限，感觉很多时候不过是加入了魔法和龙的架空历史小说，内容变化太少。

悬疑方面，我读了大量的日本推理小说，加起来恐怕不下百本。从早期的江户川乱步、横沟正史，到社会派的松本清张、森村诚一郎，再到新本格的岛田庄司、绫辻行人，以及近年来大火的东野圭吾、伊坂幸太郎，我把各个时期的代表作读了个遍。日本推理小说不断演化，脱离了侦探小说的老路，越来越朝着综合小说的方向发展，娱乐性是非常强的。时至今日，我仍然时不时会读上一本。

武侠方面，我重读了金庸的几大长篇，读了很多古龙的书，还有梁羽生、诸葛青云、温瑞安和一些大陆的年轻武侠作家，比如凤歌和小椴。感想就是金庸把武侠写尽了，后人简直无路可走。古龙创出一条新路，却由于自身性格的缺陷浪费了天赋，最终成就有限。其余武侠作家都只是金庸古龙的陪衬。悲观点说，武侠已死。就像骑士小说、西部小说告别历史舞台一样，盛极一时的通俗小说门类总有沉寂的一天。

轻小说方面，我最中意《全金属狂潮》，曾用一年读完了全系列。其余还有些「怪物猎人」、「机动战士高达」什么的，都是喜欢游戏和动画才找小说版来读。总的来说，轻小说是依附于日本ACG产业的，难以独立生存，格调水准都要差一些。

关于高雅与通俗这件事，我也已经想通了。说到底，艺术是为生活增加快乐的。高雅艺术像是茗茶美酒，能带来超凡的享受；通俗艺术像是果汁汽水，便宜解渴。享用高档美食时，可乐是不适宜的；酷暑时想要来杯可乐，偏要去品茗也是扫兴的。阳春白雪，下里巴人，各取所需罢了。

还有另外一件值得一提的事。正是从这段时期开始，我读电子书的比重越来越大。起初是为了方便，不管是等车排队还是睡前厕上，随时都能在手机上读一段。后来到了法国买不到中文书，更是完全依赖于电子版了。从小到大读了这么多年，感情上还是倾向于纸质书，读起来也更舒服。可是电子书在技术上的优势太大了，便于存储传播，一个小小的掌上设备就囊括成千上万册书，这是纸质书无论如何做不到的。几十年后，纸质书恐怕会彻底退出主流，仅作为工艺品和收藏品而存在吧。时代片刻不停向前跃进，再美好的事物也终将只能用来怀念。

## 七

许多年来，我一直保持着很大的阅读量。即便是最忙的时候，每个月也都会抽空读两三本书。近两年却觉得读不动了，甚至有意地少读书。超过一定阈值后，读的越多，读书好处越不明显。见多识广导致日益挑剔，很少有书能打动我了，读书得到的乐趣越来越少。我自己的想法成熟了，也趋向固定了，靠读一本书来改变自己是天方夜谭。我还怕自己变成博学的无知之人。我年纪还不大，我知道的东西都是看来的、听来的，很少是自己体验来的。书海无涯，假若沉溺其中，反倒把真实的人生遗弃了。

工作之后，我深感缺少动力和精力在书籍中肆意驰骋。我考虑过少量精读，钻研经典，又觉得这样会重蹈覆辙，犯下功利心太强的错误。读一本书之前还要瞻前顾后，反复思量值不值得，实在是败兴。

经过长久的思考，我得出的结论是：顺其自然。「自然」这两个字，是多么简单，又是多么深奥，人生的道理都在里面了。

去年我读川端康成的《古都》，就是一次自然的体验。我坐火车从法国南部北上，路上无事就找了篇长度适宜的小说来读。从小到大，川端康成的书我一直都有读。按说他的小说文字优美，情节简单，篇幅也不长，并没有什么阅读上的障碍。我却一直觉得抓不住要旨，欣赏不来。我初中时就读过《古都》，当时只觉得故事无头无尾，精神消极，不懂要表达什么。这次机缘巧合重读《古都》，意外地被深深感动了。书中对美好传统的歌颂，尤其是对这份美好终将消逝所表达的遗憾，远离祖国、身在异国文化中的我感受格外强烈。我所曾经认为的消极，其实是典型的佛教精神，看破人生的无常，与《红楼梦》的主题是相通的。那种无头无尾，反情节反戏剧的故事安排，乃是如同绘画、抒情诗一样的手法。曾经含糊不清的地方，一下子融会贯通，豁然开朗。

与川端康成的重逢，可以说是缘分使然，也可以说是必然的结果。正如卡尔维诺所说，经典即是反复重读的作品。在青年时代埋下种子，即使遗忘了也成为性格、潜意识的一部分，在人生经验酝酿成熟时开花结果。这种不去刻意追求，却水到渠成的感觉，就是「自然」。

所以，将来要如何读书，我并没有明确的想法。随心所欲，顺应自我，读书应该是单纯的、快乐的事。自然而然所得到的结果，就是我想要的结果。

## 八

当我回想一本书，读书时的其它回忆也一齐涌上来。写这篇关于读书的文章时，我不知不觉也将过往的人生回顾了一遍。稚嫩时促我成长，无聊时替我解闷，迷惘时为我解惑，悲伤时给我安慰，书籍一直伴随在我身旁。

之前有提到过，小时候我身边没几个爱读书的人。我年少时读的书，不仅亲戚朋友难以理解、一无所知，甚至连学校里的老师们也都闻所未闻。事实上，读书这件事让我成了「另类」，甚至遭到过质疑。小时曾有亲戚呵斥我，说看这么多书有什么用，买书很贵给家里浪费钱。当时还是小孩子的我只能涨红了脸，不知道怎么反驳。现在想想，读书是件乐事，根本不需要有什么特别的目的。非要说有什么用，读书给我带来的好处，很多时候是无心插柳。根据前面叙述的经历，读书对我起了四个作用：

第一就是增长知识，开阔眼界。书籍可以说是最浓缩、最精华，同时也是最便捷、最廉价的知识来源了。生长在小地方，享受不到优质的教育，没有良好的成长环境，书籍却成了我最好的良师益友。多年后离开家乡在外求学，无论是在上海，还是在法国，我从没有觉得跟同龄人相比在知识、教育上有什么缺憾和不足。

第二是培养审美趣味。中国一直有务实的传统，现在更是走向了一种极端，除了名利其它都不算正经事。这样一来，人的社会属性压倒了个人属性，私人空间被压榨到最小。好多人只是扮演职员、工人、家长、伴偶这样的社会角色，完全没有为自己活过。可是为了精神的满足，人是需要务虚的。如果像机器一样，所做的每一件事都有明确的目的性，成了社会运转的一个配件，活着又有什么乐趣呢？读书是件私人的事。读书时仿佛与外界隔绝，在自己的精神世界中游荡。正是读书教会了我独处的快乐，使我养成自省的习惯。从识字读书开始，我就有了一个专属于自己的精神家园。当我孤身一人的时候，我却觉得拥有了全世界。在这里我所要做的就是提高自己感受的敏锐，尽情享受艺术的美好。

第三是个性的形成。我所读的书成了我思想的来源，自我发展的养分。对自由、人文的崇尚，客观、理性的思维方式，或许是我内心早就有了萌芽，始终也要感谢书籍的指引。清理我读书的脉络，从中不难看出我成长的路径。这又应了最初开头的那段话，爱好显露人心。当我回顾读书经历，我自己也成了一本打开的书。

最后，读书让人生变得宽广绵长。与宇宙万物相比，人生是短暂的，如同转瞬即逝。我们纯靠自己双眼去看，双耳去听，能见识到的东西是很有限的。只依赖于自身经验，面对无穷无尽的世界，再见多识广的人也是井底之蛙。读书让我们与身处不同时空的人物交谈，见识千百样不同的人生，让我们作为人类的一份子而不是单一的个人，去克服有限的生命，理解永恒。

我相信，读书将会是我终身保持的爱好。二三十年之后，重新回顾读书经历，不知道会有怎样的想法。我只知道，读书不仅是我人生的注脚，更是独立的章节。

# 我为什么写作

我为什么写作？古今中外众多作家对这个题目作出过精彩的论述。博尔赫斯的说法最美：我写作，不是为了名声，也不是为了特定的读者，我写作是为了光阴流逝使我心安；奥威尔的说法最清楚明白：为了表现自我，为了审美，为了记录历史，为了政治影响；王小波的说法最直截了当：我相信我自己有文学才能，我应该做这件事。

以上的说法都很有道理，不过放在我身上都不太合适。我现在不是，将来也几乎不可能成为职业作家。在我看来作家是一种很糟糕的职业。职业的首要目的是提供稳定的收入，靠写作实现这一点太难了。就以国内来说，如果想要靠写作赚钱，比较靠谱的就是写企业文案、媒体宣传、营销广告、新闻报道。这些都是目的明确的实用写作，写什么、怎么写都不是作者作得了主的。至于创意写作，能赚钱的主要是写剧本和网络小说，这两样都要迎合市场，赚的都是辛苦钱，而且赢家通吃，绝大多数也就混个温饱。放眼全中国，能以写作为生并且自由创作的恐怕顶多几百人。任何一种主流职业的收入、稳定性和发展前景都比写作好得多。即便是青春年少时，我也未曾认真想过要当作家，对我而言写作只是一项爱好。

当一件事仅仅被当成爱好，做这件事的动机就会单纯许多。回顾我的写作经历，最初动笔的缘由是喜好读书。就像爱听歌的人自己也喜欢唱上两句，读得多了自然就想要写。当我还在上小学时就常常写些小文章，读后感、游记之类的。升上初中后开始尝试写小说。写作通常是从模仿开始，那时我在读卡夫卡、博尔赫斯还有许多其他奇奇怪怪的后现代作家，所以写出来的东西也是怪模怪样。高中时学业紧张，没有时间写作，只是偶尔在写周记时自由发挥一下。上大学后正好赶上社交网络的热潮，我时不时在网上写写日志、评论，在论坛发一些文章。出国留学后知乎流行起来了，我也用心写过些回答。

以上种种，同一辈里很多人都有过类似的经历。有人说现在是全民写作的时代，我很赞同这一说法。曾几何时，写作只属于少数人，能在报刊杂志上发表文章是件了不得的事。当今由于网络的普及，发表文章变得容易了。无论是论坛、社交网站、文学网站还是微博、博客、公众号，随便哪个平台都有成千上万的潜在读者，再不济也可以分享给自己的社交圈。而且随着经济水平的提高，人们有了追求精神生活的余裕，变得更加关注自我，表达欲更强了。写作从一件罕有、严肃的事变成了日常行为，不再限定于特定人群。

我早期的写作都是随性的、缺少自觉的。这些写作都没有什么价值，大部分都遗失了，只剩下网上留存的少数几篇文章。二十五岁生日过后我开始写日记，之后一直坚持到了现在。那时我已在法国留学半年，刚到外国时的新鲜感已经消失了，陌生环境造成的不适开始突显出来，学业压力也逐渐加重。我不想让父母担心，每次跟家里通话都是报喜不报忧。身边有一些中国同学，但彼此间还没到推心置腹的程度。在环境的推力下，我选择了写日记来宣泄情绪。直到这时我才第一次有了明确的写作目的。

人的情绪是复杂的，而且不断变化。人可以轻易地判断出自己处于负面情绪中，但要说清自己具体的感受、为什么会有这样的感受，这绝不是件容易事。当我把感受转化为文字时，必然需要理清内心细节，与自己的情绪保持一定距离，所以也就能够作出更客观的判断。当我处在心理低谷时，写日记帮我走出了一次又一次难关。

当然，日记最主要的作用还是记录生活。人生就是一连串的回忆，我希望用文字把过往留存下来。当我翻阅日记，我能知道在哪一天我看了场好看的电影，什么时候接触到新的音乐，和朋友出去玩时发生了什么好笑的事，甚至于做过什么古怪的梦。这些生活中的琐碎小事，如果不记下来肯定会忘掉。也许有人认为这些小事没有什么价值，但我认为零碎、重复才是生活的本来面貌。当这些点点滴滴的记录汇集起来，最终就还原了我的人生。

我认为写日记是件有益的事，但作为一种文体日记有着先天不足。日记是一天天如实写下来的，内容由不得任意编排，难免充斥无聊小事，内容杂乱无章。即便是文学大家的日记，其可读性也相当有限。另有一种辞藻华丽、内容精致的日记，那是用来出版的虚构写作，已经背离了日记的本意。一部真诚的日记必然包含个人隐私，是一部只供作者本人查阅的工具书。

日记写得越久，我愈发觉得这种文体限制了自由发挥。到了二十八岁时，我开始认真地写随笔。

随笔这种文体没有具体的定义，到底什么是随笔众说纷纭。有的说随笔就是杂文，有的说随笔是议论文，有的说随笔是散文的一种。我读过蒙田、兰姆、毛姆、奥威尔等人的随笔，其中有抒情，有叙事，有幽默讽刺，有文艺评论，如此种种，不一而足。我把自己的文章归类为随笔，因为无论主题如何，我要写的总是一件具体的事，而不是追求文字美感。比起修辞技巧，我更看重文章中的观点和事实。当我为写作寻找榜样时，我心中最好的散文不是出自文学家之手，而是哲学、历史等领域的学术专著。写随笔时我梳理、审视自己的思路，努力将自己的想法逻辑清晰严谨地表达出来。随笔写作保存了思维的结晶，同时也是一种良好的思维训练，提高了我的思辨能力和沟通能力。

自我是最直接的书写材料，我一直想把自己的回忆和观点总结成文。我写的第一篇是《读书回忆》，回顾了从小到大的读书经历。之后写了《迁徙》，描述自己成长的主要经过，如何从东北到上海，之后又留学海外。另外一篇《我的宅男生涯》写我的业余爱好，讲我如何接触到动漫游戏，喜欢哪些作品，我对宅男文化有什么看法。这些回忆类的文章和写日记一样，都是为了记录自己的生活。比起碎片化的日记，在随笔中我可以专门针对一个话题来写，内容更集中深入。

我写的另一类随笔则是阐述自己的观点。有的是对社会现象的观察，比如我写过一篇《职业考生》谈我对国内教育制度的看法，还写过一篇《生于忧患》谈当代人的焦虑感；有的是探讨思想观念，我写了《谈宗教信仰》《谈哲学问题》《谈道德》等一系列文章；有的是文艺评论，比如《谈香港电影》《谈日剧》等等。

在写作过程中，我有时难免会陷入自我怀疑。我是一个普通人，没有什么特别的经历，记录我的生活有那么重要吗？我不是思想家也不是评论家，我的观点有什么了不得呢？身为默默无名的业余写作爱好者，我在网上发表的文章至多不过几百次浏览、零星几个评论，有时难以避免会感到寂寥。

此外，写作作为一项爱好，即时的激励太低了。我在写作的时候，极少会感觉到像是读小说、看电影、听音乐、玩游戏那种快感。提起写作，我想到的第一个词就是辛苦。但凡是写作态度稍微认真一点、对文章质量有那么一点追求的作者，全都尝惯了写作的苦。构思文章时搜肠刮肚，动笔时为了寻找恰当的表达抓耳挠腮，好不容易写完了还要一遍遍修改，只有大功告成的一瞬间才有那么一点得意之情。过了一段时间重读旧作，拙劣之处触目惊心，恨不得全盘重来。

然而我还是坚持写下去了。我想爱写作的人恐怕多少都有些自我意识过剩，不甘心把自己当成茫茫人海中一颗不起眼的砂砾。没错，我是一个平凡的人，没有多少真知灼见。但我相信每个人都有追求自我实现的权利，社会中的每一员都应该发展自己的个性。无论是集邮、养花，还是烹饪、攀岩，只要你认定了自己想要去做，那就放心大胆去做。在辛苦写作之后，浏览自己用心写出的一篇篇文章，我为自己的脑力创造感到骄傲，觉得自己没有虚度时光，充分发掘了的自我的可能性。既然如此，还有什么不知足呢。

综上所述，我最初是无意识地写作，后来是为了抒发情绪、记录生活和表达观点；写作是一种思维训练，同时给了我意义感，让我的人生更充实。如果这些理由还不够令人信服，我只能说自己就是想写，天性如此。

我的写作经历只有短短数年，日记、随笔全算上不过几十万字，未来的探索之路还很长。今年我年满三十，写了一篇两万多字的科幻中篇，探讨人工智能是否能够理解艺术。除去年少时的信笔涂鸦，这是我第一次用心写小说。这篇小说很不成熟，不过是次很有意义的尝试，也许我将来会创作更多的虚构作品。无论写作之路如何艰辛漫长，我心甘情愿，乐此不疲。

# 卷三 我的宅男生涯 {-}

# 序篇

「宅男」这个词，据考证是台湾网民创造出来的。最早的词源是日语中的「御宅」，本意是类似于「您」的尊称，因为在动画、漫画、电子游戏爱好者中广泛使用，后来就成了族群的代称。这个「宅」引申出发烧友的意思，除了动漫游戏，喜欢铁路的可以称为「铁路宅」，喜欢军事的可以称为「军事宅」，诸如此类。中文的「宅男」一开始与原本的「御宅」含义类似，指动漫游戏爱好者。「宅男」不但平添了性别，而且容易令人望文生义，以为「宅」是成天在家不出门的意思。随着媒体的错用，以讹传讹，「宅男」彻底变成不爱出门、不善交际的人的同义词。

因为对「宅」的理解不同，这个词可褒可贬。相当一部分人以御宅的身份为荣，因为这个词指狂热的发烧友，往往对某一亚文化领域有深入的了解，是一位「达人」。按照日本御宅之王冈田斗司夫的说法，御宅在限定领域里有媲美专业学者的知识水平。他甚至出书宣称「御宅已死」，批评现在的粉丝根本没资格自称为御宅。在这层含义上，御宅是个褒义词。御宅的贬义则来自社会中对这一族群的偏见。在传统观念里，动漫游戏都是青少年喜欢的、不入流的玩意儿，成年了还喜欢这些就是呆子、怪人。刻板印象中的御宅，就是身体肥胖，不修边幅，不善交流（特别是与异性交流）的男性。这个形象可真是一点都不讨人喜欢啊。

我从小接触动漫游戏，不敢自诩为达人，至少可以说积累了不少相关的经验知识。写这篇文章，最主要的目的就是记录自己过往的经历。我写自己的「宅男生涯」，是不以为耻反以为荣的意思。一项爱好，尤其是动漫游戏这样纯私人的、对外界并无影响的爱好，没有理由无端端地被指责。身为小众文化爱好者，我对稀奇古怪的人与事有了更多的包容。有了多样性，世界才更精彩。

这篇文章分为五个部分，在序篇之后是动画篇、漫画篇和游戏篇，顾名思义分别讨论这三样爱好；最后则是完结篇，探讨综合性的话题。

# 动画篇

动画这东西，世界各国都有拍摄，唯有日本动画独树一帜，形成了特有的文化。中国的动画迷喜欢强调自己喜欢的是日本动漫，而不是国产动画。即便是在美国这样的动画强国，也有Anime（日本动画）和Cartoon（卡通）的区分，日本动画成了一种单独的类别。

我是从小看日本动画长大的。成人后虽不算是狂热的粉丝，也习惯性地经常观看。一路算下来看了二十多年，影响了我成长过程中的方方面面。

记忆中的第一部日本动画是《魔神英雄传》。这部二十多年前的老动画，现在看起来依然可圈可点，可以从中分析出不少日本动画的长处。主人公是一个普通的小学生，为的是让少儿观众更有代入感，这点不必多说。主人公穿越到异世界成了救世英雄，满足了儿童的冒险幻想。主人公驾驶的机器人漂亮帅气，还能变身为多种形态，设计水平很高。在热血冒险之余，不时穿插搞笑段落，让观看体验轻松愉快。印象最深的就是里面长的像河马、喜欢夸夸其谈的剑部武一郎（辽艺版译作施巴拉古大师），每次战斗要打电话才能叫来自己的魔神（机器人），跟主人公召唤魔神的华丽场面形成鲜明对比。

将《魔神英雄传》与同期的国产动画作比较，就更能理解到日本动画的好处。当年国产动画的佼佼者，如《黑猫警长》《葫芦兄弟》，在美术设计、画面细节、动作场面等方面都和日本动画有明显差距。而且由于产业发展落后，制作效率也远远比不上日本，短短几集用了数年才拍好。最核心的问题是，国产动画让人明显地感觉到是「大人拍给小孩子看」的，根本不了解儿童心理，以为故事里有小动物就算是童趣了。《黑猫警长》中螳螂新娘在新婚之夜吃掉新郎这样的情节太阴暗恐怖了，拟人化之后更让人难以接受，成了一代人的心理阴影，制作者搞不好还自以为是寓教于乐。与之相比，《魔神英雄传》是真正的技术成熟、水准优良的少儿动画，高下立判。

小时候看动画都是电视上播放的译制版，用中文重新配音。看的最多的是辽艺版(辽宁儿童艺术剧院)，《龙珠》《樱桃小丸子》《足球小将》《聪明的一休》等等。其次是台版，像是《灌篮高手》《名侦探柯南》《中华小当家》。动画配音这件事，按说质量与语言无关，中文配音更方便观看。可是实际上，日本动画配音演员无论数量还是专业水平都远超出其它国家，日语原版配音始终是首选。无论辽艺版还是台版，都有配音人员稀缺的致命伤，来来回回就是那几个声音，常因为声音不适合让人出戏。如今只要有得选，我都会看日语原版，已经好多年没看过中文配音的译制动画了。不过因为童年记忆，还是对过去的译制片有一份怀旧的感情在，有时在网上找些中文配音的片段听听，能想起好多过去的事。

说起当年喜欢的动画，首当其冲就是《龙珠》。这部动画在全世界都取得极大的成功，优点非常多。前期最吸引我的是风趣幽默，几乎可以当成搞笑动画来看。《龙珠》里面的角色形象稀奇古怪，性格也非常夸张。最典型的例子就是主角的师傅龟仙人，一个秃头、满嘴白胡子的古怪老头，戴着大墨镜，穿的花里胡哨，背着一个硕大的龟壳；平时的样子骨瘦如柴，一旦发功又变成魔鬼筋肉人；轻浮又好色，关键时刻却很靠得住。这部动画的动作场面很出色，打斗戏干净利落、拳拳到肉，又一直穿插搞笑桥段，很像成龙电影的风格。大战红缎带军团那段戏里有个搞笑忍者，所谓的忍术都是些愚蠢无聊的小把戏，现在想想都很有趣。从短笛大魔王登场开始，战斗戏的比例提升到一个新高度，战斗能力也越来越夸张，反派举手投足就能轻易毁灭一个城市。赛亚人登场之后，《龙珠》彻底变为战斗动画了，剧情就是无穷无尽的战斗，不断涌出更强大的敌人。那美克星上的多方角逐和沙鲁篇里时间穿越的科幻桥段是后期难得的亮点，此外的情节很有些拖沓重复。最后的魔人布欧篇更有狗尾续貂之嫌。前后剧情不连贯，拖戏，烂尾，这些都是超长篇动画的通病了。尽管有种种毛病，《龙珠》仍无愧为经典之作，时至今日我仍然时不时地重温精彩段落。

另一部非常喜欢的动画是《灌篮高手》。《龙珠》只是单纯地好看，《灌篮高手》则是为我灌输了拼搏努力的精神。体育运动是常见的励志题材，因为体育运动强调公平竞争，付出努力就能得到相应的回报，为体育献身又突显理想主义精神。主人公樱木花道为了泡妞，误打误撞加入篮球队，经过一番艰苦训练，真正爱上篮球。这些剧情可谓俗而有力，老套中见感染力。这部动画显现出创作者对篮球的热爱，除了篮球技术能力上的一些夸张，整体上是非常写实的，对篮球有着深刻的理解。这部动画可以说是没有反派角色的，对手都是值得尊重的运动员。其中大大小小的角色都有支持者，可见人物塑造之成功。我格外喜欢浪子回头的三井寿，比起顺风顺水的主角，这种经历挫折的角色更能打动我。动画版没有拍到全国大赛，剧情中途结束，很令人遗憾，好多年后我才看了原作漫画，终于知道了结局。可惜漫画版的结局也有缺憾之处。运动题材都避免不了俗套，一般都是以比赛胜利为结尾，一切困难挫折都是中途的情节转折。《灌篮高手》这样试图另辟蹊径的，反而给人一种未完成的感觉，心理上得不到满足。有生之年要是能看到《灌篮高手》出续集就好了。

《名侦探柯南》也是我当初非常喜欢的动画，是我侦探题材的入门作。《名侦探柯南》的节奏非常快，每集二十分钟就能讲好一个曲折离奇的侦探故事，实在是不容易。现在想想，这部动画是把供成人阅读的惊悚故事重新包装为少儿题材，里面的桥段颇有些少儿不宜，过于恐怖刺激。这种额外的刺激，恐怕也是受欢迎的原因之一吧。当代儿童越来越早熟，早就不满足于美好的童话故事了，红遍全球的《哈利波特》也是充斥着黑暗恐怖的要素。《名侦探柯南》的缺点就是太长了，而创作者的灵感终归是有限的，能借鉴的旧作也是有限的，到后来故事越来越差劲，连精心制作的剧场版都乏味起来。此外，这种单元剧式的故事并不适合搞主线。强行安排主线，又迟迟不推进，很让人疲惫。不管怎样，单论前面二三百集，仍可算是推理名作了。

再有一部印象深刻的动画是《樱桃小丸子》。因为画风可爱，又以小学低年级学生为主角，这部动画很容易被误认为是子供向的低幼动画。实际上，这部动画手法很成熟，是以中年人的态度回顾童年，其中的妙处没有一定年龄阅历是欣赏不来的。《樱桃小丸子》中的角色都活灵活现，对儿童的心态把握的很好。成人视角的旁白幽默又尖锐，很有讽刺的力量。小丸子一家的日常生活很能引起我的共鸣，温暖之处非常打动人心。这部动画也是十分之长，一百来集之后我就没继续看了，不知道质量有没有保持住。

童年时代另外一部意义重大的动画是《圣斗士星矢》。小学毕业的时候，我特意央求母亲买了一整套《圣斗士星矢》的VCD碟片，有五六十张之多，现在也不知道扔到哪里去了。小时候我没有赶上《圣斗士星矢》的电视播映，二堂哥曾经看过而且非常喜欢，经常给我讲其中的故事。借助偶尔的机会我看过一点漫画，还见过些漂亮的圣斗士图片。这些经历使得我对《圣斗士星矢》十分向往。最终得以一口气看完全套动画，圆了我的一个儿时的梦。可是实际看下来，只能说是差强人意，剧情的套路感严重，从头到尾就是雅典娜被抓走了、女神的圣斗士们逐一击败敌人、救回雅典娜这个循环，情节相当重复。战斗部分也是互相用大招轰炸，主角们打不过了就用顽强意志一次次爬起来重新打过，宛如打不死的小强。时至今日我已经不忍心重看《圣斗士星矢》了，担心会看出更多的毛病。让圣斗士们停留在我当初的回忆中就足够了。

小时看过的动画相当多，除了上面提到的几部，还有《铁臂阿童木》《足球小将》《四驱小子》《中华小当家》《铁胆火车侠》《城市风云儿》《三目童子》《斗球儿弹平》等等。我们这一代公认的一些童年回忆，像是《宠物小精灵》《数码宝贝》，我倒是没看过几集，《机器猫》也是以漫画为主。总的来说，童年的动画回忆还是很丰富多彩的，非常感谢当年的译制人员，把日本动画的精华引荐到中国。

升到初中之后，我看的动画一下子少了。其中有个人的因素，比如课业加重、不像小时候那样无忧无虑、我喜欢读书胜过看动画，等等。更为重要的因素则是广电总局加大了对海外动画的管制，后来甚至于干脆发布一纸禁播令，不允许在黄金时段播出海外动画。这时电视上的一些动画节目往往采用投机取巧的手段，比如用介绍的名义，把每集动画重新剪辑成五到十分钟，再配上解说性的旁白，将动画间接播出。当初我一直收看的《动漫驿站》及其后的《东西动漫社》就是用这种方式播出了《十二国记》《火影忍者》等动画。当时流行的地方电视点播台偶尔会有人点播动画，我依靠这种方式看了若干集的《犬夜叉》和《游戏王》。这些收看方式全都是别别扭扭的，看了上集没下集。与此同时，盗版碟片泛滥，能在电脑上播放的rm影片大行其道。当时买的一套《幽游白书》光碟，是我这一时期唯一一部完整观看的动画。初中周五下午大扫除时，我借着治疗鼻炎的名义回家看动画，一口气看上三四集《幽游白书》，是段难忘的回忆。

同样是热血少年动画，和《龙珠》这种简单直白的动画相比，《幽游白书》要更别具一格。藏马和仙水这样的角色，已经超出一般少年动画的范畴了。藏马外表俊美，像是柔弱的女性，实则外柔内刚，是主角群中最冷血的一个，变身妖狐后更是邪气十足。这种善恶难辨的角色已经脱离了少年动画单一的角色模板。仙水是更为复杂的角色，冷酷无情，孤独厌世，理想主义，种种特质交织在一起，让人捉摸不透。故事情节也独树一帜，加入大量智斗要素，每场战斗都有新的花样。要说缺点就是前后差异太大，几个章节不似同一套动画，一开始是小混混乱斗，到最后居然搞到毁天灭地。《幽游白书》的动画版要比原作漫画更顺畅，去掉了开头结尾处一些节外生枝的段落，将原作中一笔带过的魔界大战详尽演绎，是一次很成功的改编。

不知为何，这类动画光碟明明便宜量足，在书店里公开贩卖，我却只买了这么一套。当年错过了《银河英雄传说》，可谓憾事。究其原因，恐怕还是我对动画的喜爱不够深吧。

升入高中之后，家里安装了宽带，互联网极大地拓展了我的视野。通过云中漫步、漫游酷论坛这样的动漫论坛，以及时光网、豆瓣网这样的影视网站，还有ACGTalk这样的动漫专题博客，我接触到了大量动画资讯，不再着迷于一般的流行动画了。同时国内涌现出大量的动画字幕组，凭着对动画的热爱，自发地翻译动画。借助迅雷、电骡等下载工具，可以说是坐拥取之不尽的动画资源。可是由于高中的课业比初中更加紧张，当时我的爱好又更倾向于漫画，高中三年里看的动画是很少的。数量虽少，但都是经典。

最早看的一部是《棋魂》。这是继《灌篮高手》之后，又一部对我有深刻影响的体育竞技题材的作品，十多年里反反复复看了好多次。围棋这种难以理解、节奏缓慢的棋类运动，居然被《棋魂》演绎的跌宕起伏、惊心动魄。当时我只了解一些最基本的围棋规则，依然看的津津有味。这加深了我的一个观点，体育类作品的精髓是传达体育精神，具体的运动本身反倒不是最重要的。主角进藤光从对围棋一无所知到逐渐产生兴趣，最后成为职业棋手，这种角色成长是非常打动人的。院生训练、职业棋手考试这一段情节，内容极为写实，展示出职业竞技的残酷性。这种残酷，又更加让人理解到成功的来之不易。对职业考试失败的角色们的描写，尤其是对于伊角这个内心不够强大、通过中国之旅重振旗鼓的棋手的描写，描绘出了人生成长的多样性。一路顺风顺水固然好，经历过挫折，又从挫折中重新出发，也是很难得的经历啊。佐为消失这一段也是神来之笔，虽然作为观众会感到遗憾，不得不说这样一来使得作品得到了主题上的升华。动画拍全了佐为篇，北斗杯篇只拍了个开头。考虑到北斗杯篇素质一般，像是篇幅较长的后日谈，倒也不算是太遗憾。

《新世纪福音战士》几乎是近二十余年来地位最高的日本电视动画了，时至今日还在推出新作品，一直维持着流行度。早在小学时我就看过被修改的面目全非的中文版（《新世纪天鹰战士》），直到高中才得以观其原貌。关于EVA的文章不胜其数，二十多年来能讨论的东西都讨论的差不多了，我也没有什么新的观点。比起研究其中的隐喻，让文本越来越复杂化，我更愿意用简单的方式来欣赏这部动画。不管说的多么玄乎，这始终是一部老宅男们拍出来的少年少女驾驶巨大机器人与外星敌人作战的动画，本身就流着超级系机器人动画的血液。即便只是欣赏其中鲜活有趣的人物、细腻的心理描写、精彩的作战，《新世纪福音战士》就已经是一部出色的动画了。至于《新世纪福音战士》的主题，最核心的是人与人之间的隔膜，要突破隔膜才能互相理解。对于容易陷入内心封闭的青春期少年，尤其是御宅族，这是很能引起内心共鸣的题材。剩余的那些神秘主义的部分，在我看来只是创作者的美学趣味，没必要追求一个清楚明白的说法。

《星际牛仔》最初并不是很受欢迎，播出时甚至一度被腰斩，可是对于资深动画迷来说，这部动画如同圣经一般，同时也是我心目中最好的电视动画。这部动画制作精良，每集都很精彩，当初观看时非常沉浸其中。现在仔细想想，《星际牛仔》的故事并不特别出色，能回忆起来的情节有限。依我看，监督渡边信一郎并不是一个擅长编故事的人，也不是思想深刻的人。《星际牛仔》的好处，不在于故事或思想，而是氛围与情调。假想这样的场景：一个看上去经历沧桑，有丰富经历的男人，默默地在酒吧酌酒，好似在等人；一个身材婀娜的美人，在男人旁边坐下；两人进行了一段简洁、意味深长的对话；女人从皮包中套出手枪，带着悲哀的表情，射杀男人。只要略微添加一些科幻要素，霓虹灯、雨夜等赛博朋克风格的视觉效果，再来一段爵士作为背景音乐，这段场景可以轻易加入到《星际牛仔》里。男人和女人之间是什么关系、女人为什么杀男人，这些统统不重要，可以让观众自行想象；重点是浓厚的、有感染力的风格。喜欢这种风格就会觉得深沉动人，不喜欢这种风格就会觉得空洞无聊。这就解释了为什么《星际牛仔》受众有限，为什么形式类似的《混沌武士》还有多年后的《太空丹迪》让我提不起兴致。值得一提的是，我非常喜欢《星际牛仔》的原声音乐，反反复复听了无数次，至今依然是我最喜欢的专辑之一。

在这几部电视动画之外，我还看了不少动画电影，如吉卜力工作室的《龙猫》《风之谷》，大友克洋的《阿基拉》，押井守的两部《攻壳机动队》，等等。日本电视动画主要是面向青少年，而动画电影的受众要广的多，在手法和审美趣味上都更适合与一般的电影相比较。这些著名的电影监督是可以与黑泽明并列的电影大师，拍出来的并不是狭义的、受御宅族推崇的动画。即使再不细心的人，也能看出这些电影与《龙珠》《幽游白书》的区别来。所以，虽然我很喜欢这些影片，但是不太想将它们与一般的电视动画放在同一范畴里来讨论。

高考之后，我的人生进入了新的阶段，开始了独立的生活。我有大把的时间，可以自由地投入到爱好中。在各类爱好里，动画的排位虽然不高，但始终占据一个重要的位置。和朋友出去玩要有一整块的空余时间，读书写作、甚至打游戏都要耗精力。如果我时间不多，又不想太费神，往往就会看一集动画。我看动画的数量是逐年减少的，也不像小时候那样全心全意地享受，但终究是一种不错的放松方式。

我是喜欢搞研究的人，喜欢一样事物就想弄个清楚明白。要认真对待一项爱好，多多少少都要做些功课。我去看一些老动画，主要是为了加深对动画发展的了解，好不好看倒是次要的。比如1979年的《机动战士高达》，单论动画本身的质量，以今天的标准自然是惨不忍睹；要论历史价值，这部动画则是极其重要，引导了之后几十年的机器人动画制作。从1983年开始的《装甲骑兵》系列，是真实系机器人动画的代表作之一，我也是带着考古的心态坚持看完了。九十年代与《新世纪福音战士》并称为三大御宅动画的《机动战舰大和抚子》《少女革命》，九十年代末的实验性动画《铃音》，基本上也是由于其历史地位才去看的，动画本身并不十分符合我的口味。经过这样一番探索，我的观赏视野变得广阔许多，对各类动画都有了基本的了解。

我是以旁观者的心态去观看老动画的。当我观看新动画时，则意识到自己是时代的亲历者。我眼见着日本动画的风格与潮流发生变化。动画的原作来源不再是漫画一枝独秀，改编自轻小说、视觉小说的作品逐渐成为主流；由于制作成本提高、风险加大，年番越来越少，单季动画成为主流，连高达这样的传统年番都拆成两季播放了；泡面番、网络放映、众筹，动画厂商广泛尝试各类成本更低的商业模式。尽管多管齐下，日本动画产业还是危机四伏，很多相关从业人员发出预警。日本动画未来如何难以预测，我猜想并不是太乐观。

还是回过头来继续说自己喜欢的动画吧。首先是漫画改编动画。和动画相比，日本漫画的现状只有更糟糕，各大漫画杂志的销量节节败退。缺少足够好的原作漫画，巧妇难为无米之炊。亏得日本漫画底蕴深厚，还是出现了不少优秀改编作品，其中最好的漫改动画要属《钢之炼金术师》。漫画版《钢之炼金术师》各方面均属上乘，可以说是新世纪少年漫画的里程碑。2003版动画煽情过度，又是原创结局，不太合我的口味。2009版动画忠于原著，除了开头部分节奏偏快，整体改编质量堪称完美。另外两部非常出色的改编动画是《交响情人梦》和《花牌情缘》。我平日很少看少女漫画，要不是有这么好的动画版，我大概率会错过这样的佳作。《交响情人梦》中音乐占了很大比重，漫画只能用人物反应来表现音乐的感染力，动画却能直接演绎音乐，借助媒体的优势，可以说是青出于蓝了。《花牌情缘》的演出同样非常出色，动听的音乐和华丽的视觉效果，增添了剧情的感染力。充分发挥动画媒体优势的还有2014年的《乒乓》，乒乓球场面效果惊人。顺便一提，《乒乓》中的中国声优也是个小惊喜。轻松一点的作品我比较喜欢《幸运星》《月刊少女野崎君》和《元气囝仔》，随便看一集放松下最好不过。最近两年大热的《一拳超人》和《灵能百分百》是成功的新皮装旧酒。最后想提一下《乔乔奇妙冒险》《寄生兽》和《奔向地球》，这几部都是漫画史上的名作，能在多年后改编成动画，十分令人欣慰。同时也可以看到漫画资源匮乏，改编动画只能去找更古早的作品。

优秀的原创动画不是很多，我真正喜欢的只有个位数。《天元突破红莲之眼》是超级系机器人动画在新世纪的回归，单纯、热血、爽快；《电脑线圈》好似少年版的《攻壳机动队》，在扎实硬派的科幻设定之余又充满童趣；《东之伊甸》有一个有趣的、充满悬念的开场，每一集都引人入胜，可惜TV版剧情未完，剧场版水准大跌；《吊带袜天使》很黄很暴力很搞笑；《未闻花名》有用力过度的嫌疑，但确实很感人；《回转企鹅罐》演出手法炸裂，信息量大、象征性丰富，是一次炫丽的技术表演；《魔法少女小圆》重新解构魔法少女动画，因为大地震停播造成传奇式的影响，是近年来最可能留名史册的动画。

至于轻小说改编动画，我的兴趣要相对差一些。因为轻小说这种文体本身质量就不高。在我看来，近年热门的轻改都比不上当年的《十二国记》和《全金属狂潮》，甚至比不上最早引发轻小说改编热潮的《凉宫春日的忧郁》。我比较喜欢的是《四畳半神话大系》，我认为这主要归功于监督汤浅政明的个人风格，原作小说我是压根读不下去的。再有一部我比较喜欢的是《某科学的超电磁炮》，这部动画的来源比较复杂，不好说算不算是轻改，我主要是喜欢校园题材的轻松氛围。

视觉小说对我的吸引力比轻小说还要低，这些年堪称业界霸主的《Fate Stay Night》我都不大看的下去。唯一喜欢的只有《命运石之门》，除去最初用于铺垫的几集比较沉闷，之后高潮迭起，结尾也相当圆满，确实是一个创意新颖、结构完整的精彩科幻故事。

看了二十年动画，有时难免有倦怠之感，更喜欢厚古薄今，感觉现在的动画不如过去好看。究其原因，还是我年龄增长，逐渐超出了动画受众的年龄群。我也开始思考一个问题，动画吸引我的到底是什么呢？我喜欢的动画，要在视觉上做到一些只有动画能做到的事情，比如只存在于二次元的漂亮人物、机械、场景；世界观要有可信度，不能夸张、儿戏，人物言行举止要合乎逻辑；故事情节要结构完整，要有趣味，有悬念；风格要有独特之处，不能一味重复受欢迎的老梗。这些看上去是些简单的要求，能完全符合的动画却并不是很多。

欧美动画不吸引我，就是因为不符合我的需求。迪士尼动画，超级英雄动画，在我看来都偏低龄，过于儿戏，过于粗放。我其实很喜欢看《南方公园》和《瑞克与莫蒂》，但是感觉这类动画与日本动画风格相去甚远，本质上不是一类事物，反倒更接近于美国电视中的情景喜剧。像《灌篮高手》《棋魂》这样贴近生活、细腻动人的动画，在欧美动画中几乎找不到，即使有也是篇幅短的动画电影，跟长篇电视动画是两码事。有一部美国动画扭转了我的既定印象，那就是《降世神通》。这部动画被很多西方动画爱好者认为是欧美制作的日式动画。在人物、情节、演出、配乐等方方面面，《降世神通》都非常接近于日本动画，加上投资规模的优势，有些地方更可称得上青出于蓝而胜于蓝。像是第二部《科拉传奇》里的动作场面，质量可与剧场版相比。随着Netflix等公司开始投资制作动画，说不定日式动画能在海外重生。

无论如何，希望我这个小爱好能一直保持住。即使将来年纪大了，希望自己也能理解年轻人的文化，不至于走到对立面去。这些年来的动画经历，始终是一段难得的美好回忆。

# 漫画篇

我很小就接触到了日本漫画，只比日本动画晚一点点而已。动画是电视台引进译制的，只要按时守在电视机前观看就可以了。而在很长的一段时间里，国内没有正规的购买、阅读日本漫画的途径。我所知的唯一一套在我童年时期出版的正版漫画是人民美术出版社出版的《机器猫》，小时买到了几册。除此之外，我整个青少年时期所读的都是通过各种途径获取的盗版漫画。直到去上海读大学，我才读到了港台出版的正版漫画，第一次将印刷精致的漫画捧在手里时真是感慨万千。这些港台漫画并没有在大陆地区发行，理论上也是有些法律问题的。真正的简体中文正版漫画直到近几年才在国内陆续出版，这时我已经留学来了法国。法国的漫画出版业相当成熟，无论哪家书店都能看到一排排的漫画书。我到法国时年纪已经不小，如果真要等到这时才接触到漫画，十有八九会视而不见。

综合以上经历，如果我是一个百分百的守法公民，恐怕根本与漫画无缘了。盗版漫画填补了我人生中本可能会出现的一段空白。盗版伤害创作者的权益，看盗版不是件荣誉的事。可是，身处在一个文化的孤岛上，压根没有消费正版的途径，只能通过盗版来弥补精神的匮乏，我认为这是可以谅解的。如果我只看被允许看的，只听被允许听的，那我根本不会知道《教父》、披头士为何物，我也不会对外国文化感兴趣，也不会出国读书，整个人生都可能因此而改变。

盗版漫画自然不会堂而皇之地在书店里贩卖，我最早看漫画是在旧书摊。旧书摊上时不时会出现《机器猫》《龙珠》《圣斗士星矢》等漫画。印象很深的是海南摄影美术出版社，这家出版社曾经出了很多漫画。这家出版社的特点是把一本漫画拆分成数册，每册都非常薄，只有寥寥数十页，大概是为了降低定价吧。这些漫画印刷质量相当不错，一度令我误以为是正版。我很多时候都光看不买，因为我年纪小，书摊老板倒也不怎么在意。等我攒够了零花钱时，偶尔也会买一本。书摊上的漫画都是七零八落的，能碰上什么只能靠运气，一旦错过就再也找不回。记得当时有一本《龙珠》，剧情超出了我所看过的动画版的进度，当时非常想要，可惜囊中羞涩没有买，过几天再去看时已经卖掉了。升到初中之后我手头宽裕许多，遇到想买的书都是当机立断买下来。除了旧书摊，我家附近还曾有过一间动漫游戏店，出租漫画口袋书，还可以按时计费玩世嘉、索尼的游戏机。我曾那里租过几本《金田一少年事件薄》。对于小城市来讲这种店铺怕是理念太超前，没多久就倒闭了，只成了一段小插曲。我也有过和朋友互相借阅的经历，看过几本《胜负师哲也》什么的。只是身边爱看漫画的朋友太少，能借到书是件稀罕事。

回忆当初看漫画的经历，印象最深的就是挥之不去的缺憾感。漫画最通常的发表方式是在杂志上连载。漫画越受欢迎，连载的时间就越长。一部商业上成功的漫画，出个几十卷是常事。我这种东拼西凑的读书法，每部漫画都是看的七零八碎。初中时我曾尽全力收集到二十六卷《城市猎人》，达到全本（三十五卷）的四分之三，这就是我当时看的最全的一套漫画了。一套完整的故事，正看到兴头上，忽然没了下文，又或是中间空了一大段，这种体验最让人难受不过了。那些零零散散的精彩片段，有时又激发了我的想象力，幻想中完整的故事不知有多精彩。

这种情况得到扭转已经是初中快毕业时的事了。我在离家颇远的地方发现一家漫画店，里面有大量的四拼一漫画。所谓四拼一漫画，是将图片微缩，一页书里印四页漫画。这种书大小是三十二开，算一算其中的漫画是按一百二十八开印刷，比一般的口袋书还要小不少。这么小的篇幅，画面挤成一团，字也小的可怜。亏得漫画台词少，字号大，要不根本没法看。这种寒酸的印刷方式，让看漫画的体验大打折扣，好处则是便宜实惠。因为四合一，一册书里能收纳好几卷漫画。比如我最初买的《恐怖宠物店》，两册书就囊括了全部十卷漫画的内容。这样一来，我就得以在牺牲画面的情况下，以低廉的价格购入整套漫画。再有一个好处是四拼一漫画大多直接采用港台翻译，内容质量得到了保证。

初中毕业的暑假，我用百元「巨资」买了十册四拼一漫画，其中四册是总共二十八卷的《浪客剑心》，六册是总共三十八卷的《乱马1/2》。这时我刚结束三年的辛苦学业，顺利考入市里的重点高中，正是心情最好的时候，这场漫画盛宴更是锦上添花。直到那时为止，这是我看漫画看的最爽的一次，每天从早看到晚，直至搬到高中旁边的新家才全部看完。这种久旱逢甘霖般的快感，不曾经受过娱乐匮乏的人是难以想象的。

我生活中最重要、持续时间最长的爱好是读书，尤其是读小说。在高中那几年里，漫画却超过小说，成为我最主要的娱乐了。主要原因有两个，一是新人胜旧人，二是由于我当时的状态。说新人胜旧人，因为我当时读书已经有十年了，早已习以为常。虽然遇到本好书还是很开心，终究难有当初喜不自胜的感觉。漫画我也算是从小看到大，但是多年里都处在资源短缺的状态，只能偶尔看看。这时由于四拼一漫画和下文要提到的电子漫画，才终于可以随意看个够。一次性见识到海量的优秀漫画，那种被阅读乐趣所淹没的感觉是无与伦比的。再有是我的个人状态，高中时实在太辛苦太紧张了，严肃的正经书很难看得下去。漫画娱乐性强，是个很好的生活调剂。

我当时看漫画书，首先是按照自己的阅读经验，看那些八九十年代众人皆知的经典漫画。这一类型的漫画包括《棒球英豪》《北斗神拳》《猫眼三姐妹》等等。由此拓展开来，我再去找这些知名漫画家的二线作品，比如北条司的《非常家庭》。当时的一些电视节目，像是优秀却短命的《动漫驿站》，做过不少很好的专题节目，让我知道了前面提到过的《恐怖宠物店》，还有后来才买的《天使禁猎区》。杂志也曾是我获取漫画资讯的主要方式，《漫友豪华特集》《少年人生新干线》的漫画评论很大程度上影响了我对漫画的选购，《辉夜姬》《日出处天子》这样的漫画都是读过介绍文章后才买来看的。

家里安装宽带后，可以轻易地在网上获取资讯，进一步打开了我的眼界。当时常去名为「云中漫步」的论坛，里面的网友都是资深动漫迷，其中一些还是动漫杂志撰稿人和汉化组成员。比起动漫杂志，论坛里有更及时、更鲜活的讯息，还可以直接展开讨论。「青年漫画」这个概念就是我从这里得知的。在这之前，我只知道少年漫画和少女漫画，以为北条司就是世上最好的漫画家了，这时才接触到一系列大名鼎鼎、于我却是闻所未闻的名字：安彦良和，星野之宣，谷口治郎，浦泽直树，柴门文，永安巧，古谷实……一些当初认识的漫画家，像是手塚治虫和安达充，通过论坛里的讨论也得到了重新的认识。「漫谈ACGtalk」这个博客是由多个写手共同创作的，里面有很多出色文章。印象最深的是「两色风景」这个ID写的一系列漫画札记，他大概是我所知的看过漫画最多的人，对漫画是来者不拒的态度，无论质量好坏，什么稀奇古怪的漫画都看得下去。正因为涉猎漫画范围广泛，他的漫画评论非常有参考价值。还有「死也不告诉你」这个ID，写了一系列港台漫画出版社的介绍文章，内容很全面，非常有价值。云中漫步和漫谈现在都已经挂掉了，想寻找当初的一些文章都很困难。因为这些网站曾经对我的帮助，我仍时不时会怀念它们。

与资讯相配合的，是网络上无限的电子漫画资源。因为电子扫描漫画和汉化组的大量涌现，可以说，只要是能叫得出名字来的漫画就能在网上找到。那些遥远的、传奇的名字，落实为一页页的图片。《寄生兽》《剑风传奇》《无限之住人》《二十世纪少年》《十七青春遁走》《棋魂》《猎人》《乔乔奇妙冒险》《潮与虎》《GS美神！驱魔大作战》……都成了我高中生活中难得的精彩片段。高中毕业时我曾做过统计，当时看过的漫画总数已经将近一千卷了，其中至少八百卷是高中时看的。在高中学业极其紧张的情况下，可以说我把闲余时间都花在漫画上了。漫画当之无愧是我当时最热衷的事物。

升入大学之后，我终于释下学业的重负，变成一个自由人了，大把时间任我支配。高中积累的漫画知识，无尽的网络资源，加上自由的时间安排，大一这一年成了我漫画阅读生涯的顶峰，一年里看了上千卷漫画。平均来讲，看一卷漫画要花半个小时，算下来我平均每天花一个半小时看漫画。这一年看漫画的过程是系统而全面的，将自己感兴趣的漫画一网打尽，还看了很多地位重要的、自己却不怎么喜欢的漫画。《火之鸟》《强殖装甲凯普》《五星物语》《异兽魔都》《铳梦》《赌博默示录》《海贼王》……都是这时看的。那时我还发现了一个好去处，是邻校旁边的一家漫画店，里面藏书丰富，都是港台的正版漫画，只要饮食消费就可以无限制地阅读。我在文章开头提到在上海看正版漫画，说的就是这里了。大开本的漫画捧在手里，阅读体验要远超过电子版。我常常是下午过去，先叫一杯红茶，看漫画直到晚饭时间。有时在那里点一份猪扒饭作晚餐，吃完干脆看个通宵，早上再回宿舍去。《玻璃假面》《贫穷贵公子》《樱桃小丸子》《网坛小魔女》《死神》《钢之炼金术师》《通灵王》《影武者德川家康》等漫画都是在这里看的。有一次看永安巧的《铁道员》和《情书》，感动到几乎落泪，也是在这里。翻看顾客们在店里留下的涂鸦和留言，也常常打动我，让我明白漫画的魅力对所有人是共通的。现在想想，当初没交到几个同好实在有点可惜。漫画于我，始终是一个私人的、孤独的爱好。

在这番狂轰乱炸之后，我对漫画的兴趣逐渐变淡了。大二时漫画阅读量锐减到大一的一半以下，大概只有四五百卷。从大三开始，每年的漫画阅读量只有一百来卷了。直到留学法国的第二年，我才终于达成了三千卷的总阅读量。写下这篇文章时，已经是我工作后第二年，这个数字涨到了三千三百卷。我现在几乎只是时不时地重温过去喜欢的老漫画，不怎么看新漫画了，不知何年何月才能到四千卷。

从狂热到平静，这个转变是非常正常的。我所读的这三千多卷漫画，称得上是日本漫画几十年来积累出的最精华。符合我口味的经典佳作都看的差不多了，自己的标准也越来越高，一般的漫画不大看得下去。小时候有充足的闲余时间，可是没有漫画看；现在漫画随便看，可是没有时间。随着年龄增长，生活的焦点已经变了，不再追求一般的纯粹娱乐。漫画的娱乐价值对我来说也越来越小了。最后一口包子吃饱了，不代表前面的包子白吃了。虽然我对漫画的兴趣变低，但是漫画曾给我带来的快乐、对我审美趣味产生的影响，都是极其重要、不容忽视的。

现在和漫画有一定的距离感了，反而更容易客观地评价。我曾经如此热衷于漫画，认为喜欢漫画是理所当然的，还在网上与人争论漫画是不是艺术。现在我还是对漫画很有感情，但是乐于承认漫画的局限性。作为一种叙事媒介，漫画有什么长处和短处呢？这里我想将漫画与小说和动画作比较。在轻小说-漫画-动画早已形成完善产业链的今天，这个比较是有现实意义的。

与小说相比，漫画的优势自然是图像的魅力。当我回想一部漫画时，首先映入脑海的一定是其中角色的美术形象。这样一幅图胜过千言万语，再怎么用语言去形容角色的容貌都没有图片来得直接。幻想题材作品中稀奇古怪的异世界，战斗题材作品中激烈的对战，在这些方面图片的表现力都胜过文字。但是图片传达信息没有文字精确，一旦涉及复杂的内容，漫画就很吃力了。除非大段大段地贴上文字，否则漫画很难重现小说中细腻的心理描写、社会分析。语言是纯粹的思想载体，文学或许在某些情况下不太直观，但其深度是其它艺术媒介难以比拟的。

漫画和小说毕竟距离较远，与动画的关系则十分密切。甚至可以说，改编为动画是漫画取得商业成功的标志。与动画相比，漫画似乎处处低上一截。日本漫画多数是黑白的，直观的视觉享受就无法与动画相比；漫画要拆分成一个个小格子，靠读者的想象来构筑连贯性（不熟悉漫画的人看不懂剧情是很正常的），完全比不上动画的自然流畅；动画有配音、配乐，比漫画多了一个维度。严苛一点地说，漫画像是动画制作中的分镜图，是用来生产最终结果的半成品。

这样看来，漫画似乎是小说（一维）和动画（多维）中的过渡，是可以被取代的。小说和动画有着广泛的社会影响，而漫画只是种小众文化，正是证明了这一点。在宅文化中，看漫画的人肯定也会看动画，反过来却未必成立。可是，要我自己对漫画和动画进行比较（小说形式太不同，姑且不提），我却以为漫画高过动画一筹。

这是为什么呢？前面不是说动画在形式上全面超越漫画吗？理论上确实如此。但是之前的讨论忽略了一个重要的问题，就是创作成本。在人力物力资源无限、创作时间无限的条件下，动画确实可以超过漫画了，可现实不是这样的。动画是集体创作的产物，成本非常高，而且又极为耗时。相比较起来，漫画只要有笔有纸就能画，成本简直可以忽略不计。要表现同样的故事情节，一集标准长度二十来分钟的动画要数千乃至过万枚彩色作画，而漫画只要几十页黑白稿就行，工作量有天壤之别。因为动画太昂贵了，所以商业性太强，限制非常多，在长度、题材、风格上都没有漫画那样自由。正因如此，原创动画的数量远少于改编动画。像《灌篮高手》这样热门的漫画都不能完整地拍成动画，像《剑风传奇》这样原作画功太出色的漫画无法在动画中还原同样的作画水准，还有众多优秀的漫画根本没有机会被改编成动画。没错，动画的效果是比漫画好，但我更在乎故事的原创性、完整性、艺术性，在这些方面漫画都做得比动画好。加上漫画的数量要碾压动画（创作容易太多），产生优秀作品的机会也更多。当我超过动画预设的消费年龄层之后，能看的下去的动画就很少了，过去喜欢的动画也不太想重看了。而漫画始终对我保持一定的吸引力，过去的经典也有常看常新之感。

接下来就具体聊聊自己喜欢的漫画。正如之前所说，我认为漫画的优势在于动作和幻想方面的描绘，我喜欢的作品也大都集中于这些类型。成功的漫画往往会改编为动画，这部分难免与之前的动画篇有重复之处。对于重复提到的作品，我会把重点放在漫画版与动画版之间的差异上。

说到以动作为主的漫画，最初引我入门是战斗类的热血少年漫画，直到现在依然很喜欢。首先要提的就是《龙珠》了。鸟山明其实是偏好搞笑漫画的，他当初大概没想到自己会在战斗漫画这条路上走这么远，以至于成为了这一类型的标杆。鸟山明的天才在于对高速动态战斗的表现，漫画分镜可以原封不动拿来拍成动画。单独看时可能感觉不明显，把《龙珠》与其它漫画的动作场面比较一下，就能看出《龙珠》厉害。很多漫画（尤其是少女漫画）中的动作部分都只会摆姿势，与《龙珠》的硬桥硬马是天壤之别。再有是《幽游白书》，因为动画版的改编非常成功（删掉漫画开头结尾跑题的部分、增添魔界统一比武大会的内容），我对漫画的印象倒不是特别深。比较难忘的是结尾处窗边吹落四位主角的合影，这一个镜头胜过千言万语，回忆、惆怅都在里面了，这种巧妙的手法正是漫画的长处。在我心中比这两部更高一筹的是《乔乔的奇妙冒险》，在一百卷以上的超长篇幅里涵盖了热血少年漫画的各式内容，其本身就像一部活历史。第一部是《北斗神拳》式的老套硬派战斗漫画，第二部是情节紧凑的动作喜剧，第三部是正统的冒险剧，第四部变为异想天开的日常剧，第五部是血肉横飞的黑帮追杀，各种点子都试了一遍。从第三部开始的替身战斗堪称一大创举，每场战斗都是智慧、勇气和意志力的综合较量，免去少年漫画中常见的战斗力暴走的毛病。可惜第六部发展太过，从画风到剧情都有走火入魔的感觉，变的太奇怪了；第七部是由繁入简、返璞归真的杰作；第八部还没画完，就目前来看比较一般。就整体成就而言，《乔乔的奇妙冒险》绝对是少年漫画的巅峰之一。八九十年代是少年漫画的黄金时代，千禧年之后就有些青黄不接了。最让我有耳目一新之感的要数《钢之炼金术师》，这部漫画各方面都很优秀，尤其突出的是长篇小说一样的完整架构，有精心设计的篇章布局、线索铺陈，剧情一气呵成，一改长篇漫画剧情散漫、节外生枝的故辙。

青年漫画的受众年龄层更高，内容上的限制更少，某种程度上可以视为少年漫画的进阶版。少年漫画中常常是随便找个借口就打个天昏地暗，青年漫画的情节相对来说更有逻辑。少年漫画中的暴力往往是幻想化、卡通化的，青年漫画中的暴力表现则更直接。说到战斗在情节中所占比例较大的青年漫画，我比较喜欢《剑风传奇》《铳梦》《强殖装甲凯普》和《无限之住人》。《剑风传奇》是阴郁狂暴，克苏鲁风格的黑暗漫画，正因为情节压抑，反而使得暴力血腥的战斗更有酣畅淋漓之感。可惜随着作者三浦建太郎的功成名就、养尊处优，慢慢失去了漫画前期的蓬勃力量，剧情越来越软，变成俗套的奇幻漫画了。漫画的创作周期太长，一部漫画画个几十年都是常事。在漫长的创作中，由于作者心态、理念、画功的变化，导致作品前后不一致，这是长篇漫画难以避免的一个缺点。《铳梦》连载时间将近三十年，内容混乱的毛病尤为明显。主线剧情的基本逻辑还是有的，就是线索、主题太多，整部作品变成了科幻大杂烩。《铳梦LastOrder》中的武道大会更让我有些哭笑不得。尽管如此，《铳梦》好的地方是真的好，那些精彩的片段像是混在沙土中的钻石，一些独特的角色如疯狂科学家堪称经典人物。《强殖装甲凯普》是假面骑士这种特摄片风格的漫画，前期只算是素质扎实，倒也不算特别出色。中期开始超展开，搞出绵延万年的背景故事，一下子变得与众不同了。缺点则是后劲不足，超展开收不回来，作者有一搭没一搭地连载，眼看着就要烂尾。与前面三部漫画相比，《无限之住人》算是善始善终了，质量保持如一，动作戏水平之高几乎在剑客漫画中数一数二，常让我啧啧惊叹。能顺利完结，也有格局较小的缘故，从头到尾就是一个复仇的故事。比起野心太大的半成品，我还是喜欢这种稳扎稳打的作品多一些。

前面说的这些漫画都充分发挥了漫画的特质，有独特的美术表现方式。除非改编成血缘相通的动画，要改编成小说、真人影视都太困难。接下来的一些漫画则没有那么特殊化，是可以与其它媒介的作品相比较的，也更容易被非漫画爱好者接受。

比如说竞技题材的成长励志故事，这在小说、影视中都很常见。这类作品我最喜欢的就是《灌篮高手》和《棋魂》，之前都有在动画篇提到，这里就不再赘述了。这种努力拼搏、用汗水换来回报的故事，明知俗套却百看不厌。这类故事中的具体运动项目其实是无关紧要的，不打篮球、不会下棋一样能欣赏。《歌牌情缘》以竞技歌牌这样冷门的项目为题材，日本之外闻所未闻，仍然做到了让人热血沸腾。有些体育范围之外的漫画，比如戏剧表演题材的《玻璃假面》和古典音乐题材的《交响情人梦》，同样可以归入此类。《玻璃假面》的热血程度不逊于《圣斗士星矢》，女主人公的毅力简直比星矢还强悍。能把任何题材套进热血励志的套路，也真是难为日本的漫画家了。

再有是科幻题材。虽然很多漫画都带有科幻要素，但是纯粹的科幻漫画却不占主流。《火之鸟》内容庞杂，不太好分类，要说是科幻漫画应该不算错。日本文化敏感细腻，擅长螺蛳壳里做道场；反过来讲则是不够大气。在日本的文学影视作品中，常常是背景宏伟，跨越广袤时空，实际内容却十分小家子气，局限于几个人之间的爱恨情仇。而《火之鸟》的格局之大是惊人的，是真正的史诗级作品，跟其它艺术媒介的长篇叙事作品相比也毫不逊色。《火之鸟》以永生不灭的火之鸟为线索，每章讨论一个单独的主题，相对独立又彼此关联。我所知的与《火之鸟》形式最相似的作品，就是著名的科幻小说《海伯利安》。遗憾的是手冢治虫在完成整部作品之前就去世了，感觉缺少画龙点睛的最后一笔，否则艺术成就要更上一层楼。另一部我非常喜欢的科幻史诗是《机动战士高达The Origin》，这部漫画虽然是由安彦良和独自执笔，实际上应该算是集体创作，是数十年来机动战士高达的集大成之作。1979年开播的《机动战士高达》是机器人动画里程碑式的作品，开创了真实系机器人动画这一流派。历史地位虽高，毕竟是老动画，今天看来是很粗糙的。可是经过数十年来跨越多种媒体的续集、前传、外传、二次创作，宇宙世纪的世界观逐步丰满、完善，成了可以和星球大战相比的成熟架空体系。所以，新世纪重新创作的《机动战士高达The Origin》结构之完整、人物之立体、情节之严谨，固然要靠安彦良和的天才，却也并非一人之功。还有两部我非常喜欢的科幻漫画是《寄生兽》和《2001夜物语》。《寄生兽》的想法并不新颖，恐怖生物是最常见的科幻题材了，优秀之处在于教科书般的编剧技巧，起承转合都恰到好处，又自然适当地展开哲学探讨，每次看都能学到不少东西。《2001夜物语》是一组精巧的短篇，看标题便知是受《2001太空漫游》的启发，内容颇有亚瑟・克拉克的神韵。对于科幻爱好者来说，这些漫画都是不容错过的。

惊悚悬疑也是我很中意的类型，尤为喜欢的两位漫画家是浦泽直树和福本伸行。

浦泽直树在我看来是学霸型的人物，有天分肯用功，画功、分镜、编剧各方面都是一流水准。他的作品画面精细，产量又高，令人不得不惊叹其过人的精力。我最早看的是《怪物》。那时我才刚刚接触青年漫画，遇到这样风格硬派的惊悚漫画，当真吃了一惊。《怪物》中的悬念设置、气氛烘托都做的极好，让人欲罢不能，几乎可以与《沉默的羔羊》这类悬疑名作相媲美。可惜有虎头蛇尾之嫌，结局虽然勉强算是把故事圆上了，但总觉得缺了点什么。悬疑作品就是这样，通过技巧吊观众/读者的胃口是比较容易的，想创作出令人满意的结尾则无比困难。之后陆续看了《二十世纪少年》《布鲁图》和《蝙蝠比利》，烂尾的毛病越来越严重，都是开头惊为天人、结尾一言难尽，使我对浦泽直树评价一路下滑。究其原因，作为一个创作者，浦泽直树很聪明很努力，个性却嫌不足，匠气大过天分。尽管如此，单从技术来讲，浦泽直树仍无愧为一代名家。

福本伸行是剑走偏锋的人物。随便翻开他的一本漫画，看到那好像用三角尺画出来的丑陋人物，蹩脚的画功能让人倒吸一口凉气。这种画功都能成名成家，自然是在剧情方面有过人之处。福本伸行真的是在赌博题材上很有想法，总能设计出一些奇奇怪怪有趣的赌博游戏来。要玩好这些游戏，智力要高，头脑要清楚冷静，还要有拼死一搏的勇气。在生死关头，靠着极致的发挥和一丝好运，成功地逆转翻盘，这就是赌博漫画的魅力了。福本伸行的画功不好，就用大量的文字叙述来弥补，常常是满页的心理描写，完全可以直接改写成小说了。这些细致的心理描写，成了烘托紧张气氛的关键，毕竟赌博都是玩玩牌什么的，表面上看不出来什么，剧情的波澜起伏都是在心理层面。福本伸行的漫画还有股浓浓的屌丝愤青气质，主角都是出身社会底层，而反派都是内心阴暗变态的富人，不懂是不是和他的个人经历有关。

最后还有一类漫画，不太好归类，只好说是比较有人文气质吧。像是《少爷的时代》《王道之狗》《宗像教授秘闻录》等等，涉及历史、民俗方方面面。这些漫画好归好，可是总让我感到有些困惑，为什么要用漫画的形式来表现呢？这个问题似乎有点蠢，因为作者是漫画家嘛，自然是画成漫画。日本的漫画业如此发达，没有什么题材是不能画进漫画的，浴室、铁道便当都能出漫画，何况人文题材呢。可在我看来，这类人文内容还是直接用文字表现比较自然直接，创作起来也更高效。同样的内容，写成书要六个月，一页一页画出来恐怕六年都不止。岩明均的《历史之眼》连载已经超过十年了，不止何年何月才能画完，如果写成小说肯定老早之前就能结束了。对于不太需要画面的题材，或者是增加几幅插画就能讲的清楚明白的内容，还是不要勉强画成漫画为好。日本的众多漫画家，如果出生在其它国家，十有八九会变成小说家吧。这也是为什么我偏好动作、幻想漫画的理由，这些类型更适合于漫画，看到孙悟空大战弗利萨和剑风传奇里战斗场面，绝不会发出「为什么要用画面来表现」的疑问。

以上叙述了我看漫画的经历，探讨了我喜欢的漫画，接下来还想简单聊聊日本以外的漫画。漫画这东西其实很多国家都有，欧洲的艺术漫画水准很高，中国的连环画也一度很发达。要说为什么较日本漫画逊色，应该是因为没有形成良好的商业模式。有人说商业是艺术的天敌，我却认为商业是艺术的支柱。艺术家是要吃饭的，艺术创作不是凭空而来的，适度的商业竞争也促进了优胜劣汰。正因为日本的漫画产业发达，每年有海啸山洪般的资本涌进来，才使得小众艺术漫画也有生存的空间。市场这么大，犄角旮旯的冷门需求也足够养活漫画家了。美国的漫画产业也很强盛，漫画产量非常大，我却不大看的下去。我对美国漫画的了解不深，这里不妄谈高低优劣。因为文化差异，日本漫画和美国漫画已经成了两个不同的物种了。日本漫画里最常见的形式，由一个漫画家（其实还要算上编辑和助手，但终归是由漫画家自己来把持创作大局）用数千页乃至万页漫画来叙事一个长篇故事，这在美国是不常见的。美国漫画是集体创作，铁打的题材流水的画师。蝙蝠侠、超人是长久不变的热门漫画，创作者则换了一批又一批。这种集体混合创作的内容在画风、剧情上都不连贯，看的颠三倒四，让我很不习惯。日本漫画是可以直接与日本动画、轻小说联系起来的，虽然媒介不同，内容上却能保持一致。而美国漫画不经过大刀阔斧的改编，是很难转换成其它形式的。我既喜欢小说，又喜欢影视动漫，我追求的是跨越媒介的、共通的叙事内核。而这种追求，在美国漫画中是很少能寻找到的。漫画是种艺术形式，重点是表现手法，国籍是无关紧要的，中国和韩国同样有日式漫画（Manga）。如果将来在欧美出现了优秀的日式漫画，我也很想看一看。

赶上了日本漫画的黄金时代，能看到这么多好漫画，是一件非常幸运的事。在日本之外，漫画似乎也有逐渐进入主流视野的趋势，这是我非常乐于看到的。希望漫画的将来更加光明。

# 游戏篇

游戏与动画、漫画并列，可谓是宅文化里的御三家。以我的经验，真正三者兼修的恐怕不多。因为动漫互相改编的缘故，动画爱好者与漫画爱好者基本上是同一群人，而游戏爱好者则是另外的一个圈子。我当年痴迷动漫的时候很少玩电子游戏，身边痴迷电脑游戏的朋友则很少看动漫。除了都是年轻人的热门爱好这一点，动漫与游戏之间的共同之处其实没那么多。与看动漫时来者不拒的态度不同，由于游戏内部门类的差异性太大，我所喜欢的只是其中特定的几种。回顾我的游戏经历，能清楚地看出我的游戏偏好。

我很小的时候就接触到了电子游戏，现在已经记不清楚最早玩的是什么了，十有八九是《超级马里奥》或者《坦克大战》。小时候我没有自己的游戏机，都是去亲戚朋友家玩，有什么就玩什么。那时国内还在流行山寨版任天堂FC，玩的最多的都是FC游戏，《魂斗罗》《双截龙》《热血物语》什么的。此外还流行过带游戏功能的VCD影碟机，可以玩世嘉MD游戏，印象最深的是《街头霸王II》《腐尸之屋》《火枪英雄》和《魔王连狮子》。小学五六年级时家里买了台学习机（其实就是山寨FC），可那时已经是2000年前后，FC游戏看上去太过时了，刚开始的兴奋劲过去后就不怎么玩了。

升到初中后家里买了电脑。我对电脑游戏几乎一无所知，阴差阳错买了张几百合一的游戏光碟，里面都是些用模拟器玩的街机、家用主机游戏。一开始我热衷于街机游戏，尤其是格斗游戏，如《拳皇》和《侍魂》。不过我的格斗游戏水平很差，只是喜欢动漫风格的漂亮人物罢了。《合金弹头》也是我当时非常喜欢的游戏，其细节之丰富现在看来都令人叹为观止。

这些街机游戏比FC游戏画面更好，系统更复杂，但游戏设计大体上都是同一个路数。真正刷新我对游戏认知的是《恶魔城：白夜协奏曲》。之前我玩的FC、MD游戏都是八十年代末到九十年代初这段时间发行的，而这部是2002年在GBA平台发行的，这是我第一次玩到同时代的家用机游戏。GBA是小屏掌机，分辨率很低，游戏图像放大到电脑屏幕上模模糊糊的。加上《白夜协奏曲》画面风格阴暗凄凉，看起来实在不怎么样。恶魔城本来以音乐华美著称，这一代偏偏搞起了电子乐，受GBA机能限制不能充分表现电子音色，听起来相当诡异。而且那时玩的是日文版，不懂日文的我根本看不懂剧情。在种种负面条件下，这款游戏依然吸引我玩下去，全是因为出色的游戏设计。这款游戏乍看上去是普通的2D动作游戏，跟《忍者龙剑传》什么的差不多。传统的2D动作游戏是卷轴式的，角色朝着一个方向前进，不断推进关卡。而这款游戏的地图却是开放式的，上下左右四个方向都可以随意探索，不再有关卡的概念，而是巧妙地利用Boss位置、特殊道具来控制流程。比方说有的地方太高了跳不上去，得到二段跳能力就能跳上去了；有的地方道路太狭窄，需要用滑踢的能力从下方滑过去；有的地方被水淹没，需要游泳的能力潜下去，等等。开放地图里有大量的隐藏要素、特殊捷径，达成全地图探索以及用邪道玩法出城都很有趣。这种设计手法是《银河战士》首创，又被《恶魔城》发扬光大的，现在大热的魂系列的地图设计也是其精神继承者。在战斗系统方面，《白夜奏鸣曲》加入了丰富的道具、装备，角色还能升级，还有多样的魔法技能，完全是按照RPG来设计的。在各种类型的游戏中引入RPG要素，也是当今的潮流之一。《白夜协奏曲》在同系列、同类型中都不算突出，由于这是我第一次接触这种类型的游戏，所以留下了深刻的印象。之后玩的《超级银河战士》《月下夜想曲》等等论游戏素质都比《白夜奏鸣曲》高出不少，可是却没有那么惊艳了。

我上初中时正好是PS2的黄金时代。那时对购买PS2这件事连想都不敢想，只能看看电视上偶尔播出的游戏节目过过眼瘾。有次看到《鬼武者3》的介绍视频，真是震撼到不行，想象不到电子游戏居然能有这样漂亮的画面。上高中后，我终于玩到了PC版的初代《鬼武者》，这是我第一次玩到PS2级别的游戏。这款游戏采用老生化危机式的固定视角和坦克式操作，这种设计现在早已被淘汰了。《鬼武者》的突出特色是开创了著名的一闪系统，就是在精准的时机进行攻击、防御、闪避等等，正确输入后可以获得奖励，比如将敌人瞬杀。这种考验反应速度的技巧我最玩不来了，《鬼武者》系列我都只是玩个皮毛，通关了事。

高中时学业繁忙，只能见缝插针看几页小说漫画、看段视频，根本没时间玩游戏。值得一提的是，寒暑假时我偶尔会玩玩《红色警戒2》，父亲旁观时起了兴趣，后来他比我玩的还起劲，把所有战役都打通了。他非常喜欢屯兵，每次都是造了一大堆坦克，再靠兵力优势碾压敌人。他还喜欢自娱自乐，已经胜利的局面继续造兵、造建筑物，填满了整个屏幕，搞到电脑都卡顿了。电子游戏就是有这样的魅力，不分老少都会被吸引。如果我父亲能早些接触到电子游戏，应该也会成为一个游戏玩家吧。

高考结束后，我有一个漫长的暑假，终于可以尽情娱乐了。我在堂哥家住了一段时间，在那里玩到了《生化危机4》，这是一款对我影响很大的游戏。我对射击游戏没什么兴趣，中学时同学间盛行《反恐精英》，我都没怎么玩过。《生化危机4》同样是射击游戏，却让我玩的如醉如痴。当然可以列举出一系列区别来，比如《生化危机4》其实是生存冒险游戏，有探索解谜要素，有紧张的剧情等等。对我来说，《生化危机4》吸引我的地方可以概括为一点，这是一款按照日式动作游戏的思路来设计的射击游戏。除了把冷兵器换成枪，这款游戏是与我过去玩的种种日式动作游戏一脉相承的。比方说，敌人具有多样性，各有独特的攻击方式和弱点。电锯老祖，橡皮人，瞎子，全都是经典的敌人设计。再比如说，每一段游戏流程都会在最后关卡设置Boss战，Boss往往还能多段变身，Boss战分为若干阶段。这些都是在冷兵器动作游戏里司空见惯，而在射击游戏中极少看到的设计。《生化危机4》还加入了体术的要素，这就更像是动作游戏了。升级枪支也和《鬼武者》《鬼泣》中的能力升级十分相似。一般的欧美射击游戏，无论题材是一战二战、警匪对峙还是外星未来，打来打去都是大同小异的人型敌人，强调的是走位和瞄准，没有Boss战的概念。再强的人类，被一枪爆头总该死了，一个回合就结束战斗，怎么设计Boss战？从这里也可以看出日本游戏与欧美游戏的思路分歧：日本游戏强调游戏性，怎么好玩怎么来，哪怕是夸张的、不符合现实的设计；欧美游戏追求拟真，真实性就是政治正确，哪怕游戏单调难玩也无所谓。

上大学之后我的空闲时间更多了，不过头两年热衷于动漫，还是很少玩游戏。玩的几款游戏基本都是过去的延续，比如用模拟器玩DS上的三款《恶魔城》，PC游戏《暗黑破坏神2》《红色警戒3》，移植到电脑上的那些Capcom游戏：《鬼武者3》《鬼泣3》《鬼泣4》《生化危机5》等等。我还打通了古早的《生化危机2》，果不其然一点都不喜欢，因为我喜欢的是4代开始的第三人称射击模式，对正统的恐怖游戏并不感冒。有次寒假里我玩了《使命召唤》，这是我打通的第一款FPS游戏。除此之外还玩了些《植物大战僵尸》之类的风靡一时的独立游戏，以及和室友们一起玩《三国杀》。

到那时为止，我接触的游戏不算多，也不算少，也就是一般中国年轻人的平均水平吧。偶尔玩玩游戏是挺开心的，但算不上我的主要爱好。直到大三时搬到了郊区的分校，情况才有了转变。由于几个因素的相互影响，我对游戏燃起了不一般的热情。

搬到郊区以后，出行不方便，生活就是宿舍、教室、图书馆、食堂四点一线，购物都靠淘宝，有时两三个月都不出一次校门。整天宅在学校，总归要找点乐子。那时我对动漫已经很有些腻味了，看书看电影看美剧也都早已沦为日常惯例，没有什么激情。新室友教会了我玩Dota，从此Dota成了定期的宿舍活动，几乎每晚必玩。Dota以及同类型的《英雄联盟》《王者荣耀》都是现今最红火、最主流的游戏，没有什么介绍的必要了。游戏的主流趋势不断更新发展，Dota的成功大概就在于符合了当下的生活节奏吧，半小时到一小时就能打完一局，操作相对简单，团队合作适于社交。我的Dota技术很一般，痴迷了几个月之后就秉持「小玩怡情，大玩伤身」的态度只是偶尔玩一玩，之后跟朋友们的水平差距就更大了。要说Dota对我最大的影响，其实是养成了玩游戏的习惯，每天安排一两个小时的游戏时间，为我接下来的游戏历程做了铺垫。

我曾经常去一个名为「漫游酷论坛」的动漫论坛，后来不止为何有很长一段时间无法登陆，我就转战到著名的S1论坛「Stage1st」。这个论坛包括了号称「华语第三」动漫论坛，实际上却是以游戏论坛起家的。我时不时去游戏论坛逛逛，看看网友们讨论些我闻所未闻的游戏，居然产生了兴趣。那时是2011年左右，正值第七世代主机（PS3/XB360/Wii）的末期，3DS刚刚发售、由于高售价和大地震举步维艰，PSP回光返照成了日式游戏最后的阵地，论坛里每天都吵到天昏地暗。

再有一件事是我在图书馆发现了大量游戏杂志，《家用机游戏技术》《电子游戏软件》和《大众软件》等等，看到那些绚丽的游戏截图，更加刺激了我的好奇心。

虽然兴趣来了，却苦于没有游戏设备，只能望梅止渴。恰巧我换了新手机，装了个GBA模拟器，用老游戏来填补一下饥渴。前面提到过，我早在上初中时就玩过GBA游戏了，对其并不陌生。这次再续前缘，不同之处是几乎所有主流游戏都已经被汉化，能玩上中文版的游戏，终于能看懂剧情了。加上我逛论坛、看杂志提升了游戏知识，挑选游戏也更加得心应手，玩的全是经典佳作。GBA的机能不高，却也有独特的优势，它是最后一款以2D游戏为主的主机，涌现了众多优秀的2D动作游戏、策略游戏、角色扮演游戏，某种程度上可以视为SFC的延续。

重新接触GBA，我最早玩的就是《火焰之纹章：封印之剑》。这类SRPG游戏，我过去是有玩过一些的，比如MD上的《水浒传》和GBA上的《火影忍者：木叶战记》。火纹系列是同类型中水准最高的，在GBA上三款作品都非常出色。火纹的系统简明又耐玩，了解武器相克、地形、站位之后就能轻松入门，精巧的关卡设计让玩家主动地研究策略，严苛的人物死亡设定又增加了挑战性。众多的俊男美女角色，生动的战斗画面，流畅的剧情，更为游戏增添光彩。《封印之剑》《烈火之剑》《圣魔之光石》一路玩下来，火纹在我心中建立起了特殊的地位。

《高级战争》系列与火纹是同一家工作室开发的，设计方面颇有相似之处，比如基本的战斗模式，兵种相克等等。不同之处则是《高级战争》允许牺牲战斗单位，注重资源争夺，没有升级、装备这些RPG要素，更加强调策略性。《高级战争》风格卡通，看似简单，其实内容非常深奥，有复杂的战术博弈，贴吧、论坛里的深入研究文章常看的我一愣一愣的。

《塞尔达传说：缩小帽》是我第一次接触塞尔达系列，因为我是解谜苦手不算太喜欢；两款《银河战士》与《恶魔城》风格类似，更注重解谜；《逆转裁判》系列充分发挥了GBA的特色，有漂亮的动漫风格，但在谜题设置方面有点扯，不太合我心意；《瓦里奥制造》《节奏天国》等游戏让我见识到了任天堂天马行空的创意。总之，GBA上好游戏非常多，是我非常喜欢的一款主机。

GBA游戏玩的差不多之后，我开始折腾DS模拟器，可惜我的笔记本电脑性能一般，效果不是很好。忍着低帧数和卡顿，我打通了《新超级马里奥兄弟》和《超级马里奥64DS》，这两款游戏，尤其是细节丰富、每张地图有多种玩法的马里奥64，让我重新认识了马里奥，没想到小时看不上眼的游戏居然发展到如此程度。

那年暑假结束后，我终于无法忍耐，斥「巨资」（加上各种配件才不过一千块）买了一台PSP。买到手后并不是特别兴奋，还有种复杂的别扭心态，觉得再有两年就毕业了，买的时机很奇怪。说到底还是节俭惯了，给自己买件礼物都思前想后。从这时起我开始记录自己玩过的游戏，所以前后玩的每一款游戏都记得清清楚楚。我先是打通了两款《战神》，然后是《无双大蛇》《第三次生日》《机战MX》《最终幻想VII：核心危机》。这些游戏的画面都很不错，能在掌机上达到这种效果真的很惊人。可是游戏性就马马虎虎，比GBA上的经典游戏差了不少。年底玩的三款游戏才真正刷新了我对游戏的认知。

第一款是《怪物猎人P3》。《怪物猎人》系列是PSP上最火的游戏，对很多人来说，PSP甚至可以说是怪物猎人专用机。P3这款PSP上最后的怪物猎人，在技术上达到了顶峰，画面综合水平在PSP上数一数二，浓厚的和风也特别吸引我。当时我对《怪物猎人》几乎一无所知，只是听说难度很高。我一开始用的太刀，很快就卡怪了，土砂龙死活打不过去，差一点就想放弃了。改用弓之后重开一片天地，干掉土砂龙时真是开心极了。后来虽然又遇到了各种困难的任务，比土砂龙高出几个级数，可是再也没有过放弃的念头，坚信只要坚持一定会胜利。花了一百小时，一路上披荆斩棘，最后打败村最终紧急任务峯山龙的那一刻，内心真是充满了感动，在校内网（如今半死不活的人人网的前身）发了很长的一条状态来纪念，如此感受是前所未有的。在我看来，《怪物猎人》系列是迄今为止3D动作游戏的最佳形态。武器、怪物丰富，动作流畅手感好，这些都不用提了，更了不起的是精准的动作设计和判定。每一个动作的速度、硬直、范围都是确定的、精心调整过的，一招一式的拿捏都不含糊。加上怪物肉质的概念，每一招打在不同的位置都有不同的伤害效果。正因为这份精准，《怪物猎人》的难度是公平的，打不过只说明学艺不精，只要勤修苦练，没有狩猎不了的怪物。经过一次次的尝试、摸索、练习，变换武器和打法，加上道具的辅助，最终战胜一个看似无敌的庞然巨怪，那种成就感是无可比拟的。素材系统也是让人投入的重要原因，《怪物猎人》里的所有装备、道具都是可以通过狩猎、采集得来的。每战胜一个强大的敌人，自己也变得更强大。种田、钓鱼、挖矿、捕虫这些日常任务也成了一种轻松的调剂。在那一百小时里，我真的感觉自己成了一个猎人，成了结云村的一分子。之后我开始找朋友联机一起打集会所，不过因为身边玩PSP的朋友太少，玩的就比较少了。

第二款是《合金装备：和平行者》。我之前有玩过PS上的《合金装备》，可是毕竟年代久远，早期的3D画面过于粗糙抽象，没留下太好的印象。这款《和平行者》终于让我领略到了潜入游戏的快感。比起激烈紧张、狂风骤雨式的战斗，这种细心观察环境、耐心等待时机，不惊动一草一木潜入敌营的游戏更适合我。《和平行者》为了适应掌机，关卡比较短，让我这样的新手更容易入门。《合金装备》除去高素质的游戏内容，在叙事和影像风格上也是别具一格的。现今我已经打通《合金装备》全系列，对剧情比较不以为然，可是当年确实觉得剧情酷毙了。严肃冷峻的近未来背景，高端炫酷的科幻武器设定，这些都非常吸引人，不逊于一般的好莱坞娱乐大片。

第三款是《最终幻想VII》，是通过PSP内置的PS模拟器来玩的。说到FF7对我的意义，一句话就可以概括，那就是RPG的入门作。RPG的流程非常长，认真打通一款往往要三四十个小时，实在是非常硬核的游戏类型，不是所有玩家都吃得消的。我之前有接触过一些RPG，不过都是半途而废了。我用50小时打通了FF7后，好似成功跑完一次马拉松，之后遇到流程再长的游戏也不以为然了。FF7是游戏界的《泰坦尼克》，是里程碑式的巨作，除了画面过时（其3D画面在当年反而是最大的卖点），在剧情、系统、设定等所有方面都极其优秀。剧情从破坏魔洸炉开始，一开场就展开紧张的情节，随后与神罗的冲突、营救艾丽丝、神秘强大的萨菲罗斯登场，环环相扣毫无冷场。后期揭示克劳德的过去，塑造出独特的悲剧英雄，成功描绘了克劳德的成长、与同伴之间的羁绊。战斗方面是集过往之大成（对当时的我而言却是新鲜的），ATB、极限技等等让回合制战斗变的紧张刺激。魔石系统更是一次成功的创新，队伍组成、技能配合更加自由多样。我之所以喜欢上RPG，就是因为FF7让我明白了电子游戏的品质是与规模紧密相关的，在RPG这种内容、长度无所限制的类型中才能创建最高的杰作。

2011年我总共玩了将近三十款游戏，游戏时间达到了500小时。尽管我很早就开始玩游戏，在我看来，这才是我正式成为游戏玩家的元年。

接下来的几年，都是2011年的延续。我顺理成章地买了更多游戏机，玩了更多游戏。喜欢的游戏我就深入地玩遍全系列，比如前后玩了十来款《最终幻想》；感兴趣的类型就把相关的代表作都玩一玩，比如喜欢上RPG后很自然地就去玩《勇者斗恶龙》《超时空之轮》等等。下面就不一一详述，只挑几个关键的地方讲一讲。

2012年暑假我玩了英文版的《女神异闻录3携带版》。在这之前我已经把PSP上感兴趣并且有汉化的游戏玩的差不多了，开始找一些英文版的游戏来玩。因为RPG很长，文字量又特别大，玩英文版比较累，所以开始时只是想随便玩玩，不一定要打通。没想到玩起来一发不可收拾，一周时间就通关了。这是我第一次打通全英文的RPG，让我对自己的英文更有信心，间接导致后来买了美版的3DS，那就是后话了。《女神异闻录3》的设计很独特，把RPG和GAL两种游戏结合起来。白天是恋爱冒险游戏，搞各种校园活动、交友谈恋爱；晚上则是正统的RPG，走迷宫打怪兽。恋爱冒险部分推进人际关系，就可以在RPG部分获得更多经验，从而将两者结合起来。把两种不同的游戏类型结合在一起是非常新鲜的想法，玩起来别有一番风味。3代是初次尝试，两者的结合还有些不自然，之后玩的《女神异闻录4黄金版》和《女神异闻录5》愈发完善，浑然一体。我喜欢《女神异闻录》系列，首先当然是因为游戏素质高，战斗系统基于女神转生系列多年的经验积累，剧情、人设等方面也非常出色，改编成动画后也大热。更重要的理由是《女神异闻录》达成了我对青春美好的幻想。我的青年时代都忙于学业，每天就是学习、作业、考试，没有什么美好的回忆。《女神异闻录》让我在虚拟世界中重新体验校园生活，与朋友玩闹、参加社团活动、搞学园祭、温泉旅行……全都是我向往却不曾体验过的事情。《女神异闻录》的流程非常长，四五两代我都玩了近百小时，多半时间都花在日常部分了，这份漫长使得学院生活的戏份更加细腻真实。因为击中了我内心柔软的部分，《女神异闻录》是我难以忘怀的作品。

2013年我玩了3DS上的《动物之森》。这款游戏非常奇特，难以归类，大概可以说是《牧场物语》和《模拟人生》的结合体吧。我玩之前并不十分期待，只是出于对任天堂游戏素质的信任买回来试试看，没想到一气玩了一百来小时。游戏内容轻松可爱，就是建房子、买衣服，和小动物聊聊天，和其他玩家联机玩玩捕虫、钓鱼小游戏什么的，没想到却很上瘾。细想一下，电子游戏的主流一直是打打杀杀，多少都有些暴力要素，为什么不多制作些让人放松的游戏呢？《动物之森》的核心思想就是放松，没有一个固定的游戏目标，只要沉浸到纯真无邪的世界中就行了，可以说是颇有禅意的。虽然在短时间沉迷后就没怎么玩过了，《动物之森》给我的启发是很重要的。

2014年我买了PS3，2015年买了Wii，这两年玩遍了第七世代的代表作。下面将欧美游戏和日本游戏分开讨论。

先说欧美游戏吧。欧美游戏在第七世代异军突起，销量和评价上都超越日本游戏，一下子逆转了形势，成为业界主流。我这种几乎只玩日本游戏的玩家，也不得不主动去找欧美游戏来玩。第七世代欧美游戏的两个主流趋势就是电影化叙事和开放世界。由于技术的提高，动作捕捉、表情捕捉成了大型游戏开发的标配，每款大作都要有电影级别的大场面。《使命召唤4：现代战争》推广了脚本的概念，让游戏叙事不再依靠文字叙述和播放影片了，而是配合玩家的行动来触发相应的脚本。开放世界的代表就是《侠盗猎车手》系列，顾名思义就是有一张全开放、可以自由闯荡的地图。靠着这两招绝技，欧美游戏给人强烈的感官震撼，第一次在《神秘海域》里充当印第安纳琼斯式的冒险家，第一次在《刺客信条》里游览宏伟古都，要说不震撼是骗人的。但是在游戏性方面，苛刻一点地说欧美游戏在整个世代几乎毫无建树。电影化叙事和开放世界都成本高昂，在打造好漂亮的外表之后，游戏厂商已经没有时间、金钱和勇气在游戏系统上下功夫了。与第六世代百花齐放相比，第七世代的3A大作出奇地整齐划一，使用同样的图像引擎、同样的操作模式、同样的战斗系统，游戏之间的差别只在于背景故事这种外包装。我比较喜欢的几个游戏，都是在故事题材上吸引我，游戏本身没什么突出之处。《质量效应》三部曲是太空歌剧题材，科幻设定、人物塑造、故事情节（除掉令人失望的结局）都很让我喜欢，玩起来就比较单调无聊，就是毫无特色的第三人称掩体射击。《蝙蝠侠》阿卡姆系列让我体验了一把蝙蝠侠，游戏内容也算花样繁多，可是各项设计都比较平庸，战斗系统好似音乐节奏游戏、道具解谜简单粗暴，完全是以量取胜。《荒野大镖客》和《最后生还者》都是以故事取胜，前者更写实、讽刺更犀利，后者由于是线性设计，故事更加连贯。《侠盗猎车手V》是第七世代最后的大作，也是集大成之作，是欧美游戏工业水平的集中体现。如果要挑选一部游戏来代表第七世代，我一定会选《侠盗猎车手V》。《侠盗猎车手V》的内容就是各种流行要素的排列组合，单看每一项水准只算中上，结合在一起就成了工业上的奇迹。短时间内玩过许许多多欧美游戏之后，没有太多的美好回忆，反而因为内容重复导致倦怠。

再说日本游戏，第七世代日本游戏的表现很差劲，大大小小的厂商似乎都迷失了方向，不由得让人感慨日本游戏衰落了。经济大环境变差，游戏制作成本升高，少子化，这些都是客观存在的原因；同时也要怪游戏厂商自己走上歧路，放弃自己的传统去模仿欧美游戏，结果画虎不成反类犬。最典型的例子就是《最终幻想XIII》，抛弃了一贯的传统，搞的不伦不类，不仅不像是一款《最终幻想》游戏，甚至不像是一款RPG。只有少数的游戏保持了日本游戏的优良传统，最突出的代表就是《异度之刃》，这是我评价最高的第七世代日本游戏。《异度之刃》顺应潮流采用了开放世界设计，地图宽广宏伟，但是主线流程完全是传统的线性设计，保持了剧情扎实感人、系统有深度可玩性高这些日本游戏一贯的优点，同时在战斗节奏、演出方面做出改良。在我看来，这种承前启后的做法才是日本游戏发展的正确方向。

2016年我结束了学生生涯，毕业参加工作。年龄的增长、步入社会后心态的变化，以及玩过大量游戏之后的疲惫感，使我对游戏的兴趣一下子淡了不少，新购入的游戏机甚至一个月难得开一次机。我不再有耐心去重复练级或是挑战高难度，画面的噱头也对我失去了作用。比起新鲜出炉的热门大作，我更喜欢游戏性突出的怀旧游戏和独立游戏。

以上就是我过去这些年来的游戏经历。小时候喜欢玩游戏，却没有条件去玩；初中高中时有了一定条件，却没有什么时间；大学和留学期间把积攒多年的游戏欲望释放出来，狂热地玩了大量游戏；毕业后心态老了，不太能够从游戏中得到乐趣，闲暇时也不怎么玩了。游戏买回来只在游戏机里转一圈就放在角落里积灰，甚至于压根没打开包装。这在当年是无可想象的，却是如今的现实，人生的变化就是这样奇妙。也许将来我会彻底远离游戏几年，等游戏技术有了突破性的进展（比如虚拟现实和增强现实）再重新以少年的心态去玩新一代的游戏。

# 完结篇

这篇探讨些杂七杂八的内容，没有一定顺序，想到什么写什么。

## 动漫游戏是不是艺术

动漫游戏的主要受众是青少年，常被大众认为是没有什么价值的纯粹的娱乐，缺乏主流认可。由于这种贬低，爱好者们总是想证明动漫游戏的价值，常常围绕动漫游戏是不是艺术展开争论。这种讨论的潜台词是，艺术是有价值的，如果动漫游戏是艺术，那么动漫游戏就有价值。这种观点把艺术看得太高尚了，我认为一样事物只要有主观的、创造性的要素就能被称为艺术，没理由把艺术限制在某几种「高雅」的形式中。说动漫游戏不是艺术的人，往往举出几个粗制滥造的动漫游戏，然后声称这不过是工业品罢了。实际上，质量差只能说明艺术价值低，并不能借此否认一样事物是艺术。

动画与真人出演的影视作品在本质上是一回事，漫画是绘画与文学这两种艺术的结合，动漫是艺术这一点是毋庸置疑的。电子游戏的情况则比较复杂。现代电子游戏种类繁多，除了都是带有互动要素的电子软件，彼此之间相去甚远。有的游戏纯粹是对现实的模拟，如运动、赛车游戏；有的是实体游戏的数字化，如电子版的棋牌游戏；有的游戏是让玩家发挥创意的工具，如《我的世界》。这些游戏虽然都会有艺术包装（画面与音效），主旨却与艺术天差地别，非要说是艺术实在太勉强了。在游戏中，玩家是核心参与者而不是旁观者；如果说游戏是艺术，有时甚至无法辨别玩家和制作人谁才是艺术创作者。一些被公认为艺术的游戏，比如《风之旅人》，是借由限制玩家的行动来实现制作人的艺术表达，比起游戏更像是电影。牺牲游戏的互动特性去向艺术靠拢，这注定是一条狭小的分支而不是游戏的主流。

游戏并不需要靠委身艺术来证明自身的价值。游戏是人类更本质的需求，甚至可以反过来说艺术其实是一种游戏。人类天生有娱乐的需求，借由数字化的形式，电子游戏摆脱了物理世界的限制，可以将运动、艺术、科学都融入其中，提供无限样式的娱乐。从这个角度来说，目前对游戏的定义还是太狭隘了。随着电子技术的发展，我想电子游戏会更加广泛地融入到人类社会中。

## 谈盗版

盗版是一种偷窃行为，在道德层面上、法律层面上都是错误的。小时候力不从心；成人后经济条件、消费环境得到改善，我全力支持正版。但是，由于以下几点原因，我对盗版行为是比较宽容的，偶尔使用盗版也并不会多么良心不安：

一，没有正版消费途径，盗版是唯一选项。比如说，我国市场在相当长的时期里都混乱封闭，根本没有渠道去购买正版动漫游戏。当时在国内看盗版动漫、玩盗版游戏并没有损害创作者的利益，反而起到了宣传的作用。再有，除了少数名作，动漫游戏很容易绝版，大量作品已经永久性遗失了。动漫游戏的商业价值是有时效性的，一旦过时就没人消费了。版权方只重视盈利，对老作品的保护不到位，甚至出现过游戏厂商丢失代码，反倒去盗版网站下载游戏rom的例子。在这种情况下，互联网上的盗版下载反而保存了历史。

二，正版服务差、不切合实际，盗版提供更好的体验。这点主要是指游戏。在网络、电子技术如此发达的今天，要在技术上防范盗版是不可能的，再高端的加密手段也迟早会被破解。有的游戏厂商费劲心力研究加密手段，间接导致了对正版消费者的折磨，安装、使用游戏软件都要经过层层关卡，单机游戏也要联网检验。盗版游戏很多时候反而提供了更好的体验，可以直接在网上下载，权限开放可以自由修改游戏，添加MOD。在玩老游戏的时候，功能丰富的模拟器可以提高分辨率、用材质包改良贴图，可以即时存档，可以用爱好者制作的改版、翻译，提供了远超原版的游戏体验。动画方面也存在外国发行商（对于日本动画）发行不及时、擅自篡改内容、翻译质量差、不提供原声的毛病，有时真是逼得观众去看盗版。厂商应该扭转观念，满足消费者的需求，让消费物有所值，让消费者主动去用金钱来交换更好的体验。

三，文艺作品应该自由、广泛地传播。文艺作品不是单纯的商品，没有哪个创作者不希望自己的作品流传到每一个角落。在互联网广泛普及的今天，传播已经没有技术上的阻力了，因为版权而局限住作品的传播是令人遗憾的。在互联网时代，应该创造、使用新的商业模式，比如流媒体订阅，作品免费推广靠周边产品盈利，等等。

总而言之，网络时代用蛮力去遏制盗版是不切实际的。应该靠提高服务质量，让消费者主动选择正版。顺应时代潮流，站在传播的同一阵营而不是对立面，才能导致互利的结果。

## 轻小说

轻小说产业规模越做越大，现在已经成了宅男文化中和动漫游戏相提并论的第四极了。像我这种对轻小说不以为意的人，不知不觉居然也读了不少，算算也有上百卷了。

轻小说是个相当粗泛的概念，幻想、冒险、悬疑、恋爱……什么要素都能在轻小说中找到，很难单凭内容判断一部小说是不是轻小说。说穿了轻小说只是一种商业推广手段，只要配上动漫风格的插图，什么小说都能当成轻小说来卖。非要找出风格上的共同之处，大概就是轻松易读的青少年文学。

比起文学作品，轻小说有时更像是动漫游戏的周边产品，是扩展盈利的一种方式。我最沉迷于《怪物猎人》的时候，就有找《怪物猎人》的小说来看，这种消费跟购买画集、手办、饰品等周边产品是一回事。这种商业性质极强的作品，文学二字简直无从谈起。

因为快消品的性质太强，轻小说的文学素质普遍不高，绝大部分对我来说都难以卒读。尤其是那些标题特别长、用重复啰嗦的对话填满整本书的典型轻小说，只能用来催眠。说到我真正喜欢的作品，也就只有《十二国记》和《全金属狂潮》。这两部系列小说的轻小说味道不那么浓，并不以美少女插图为卖点。前者是相当正统的东方奇幻小说，后者则是科幻军事题材，完全可以抽离出轻小说的范围，被一般读者所接受。

抨击了这么多，最后说说轻小说的好处，那就是快速廉价地尝试点子，如果受欢迎再改编为动漫游戏。这比直接制作动漫游戏的风险小太多了。事实证明这是个成功的商业模式，我相信轻小说还会继续流行下去。

## 网络论坛

互联网是小众文化的救星。即使身边一个同好都没有，也能在网上找到组织的温暖。在网上游荡这么多年，我觉得一个中等体量的专门论坛才是最适合爱好者聚集的。

专门论坛这点无需多说。在信息过载的时代，对信息精确定位是非常重要的。我很受不了一个论坛动漫、游戏、电影、数码无所不包，没有一个重点。这方面我最欣赏NeoGAF的做法，论坛里只有游戏讨论和水区这两个分区，一目了然。

关于论坛体量问题，一个论坛如果太受欢迎、流量太大，就会被海量低层次的讨论淹没。像百度贴吧这样的网站，因为没有任何门槛，聚集了大量缺少基本知识的网友，充斥着无聊的帖子。反之，如果一个论坛太冷门，门槛太高，结果就是挂掉。典型的例子包括云中漫步、机动战士联盟、The Ring of Wonder等网站，要么关闭服务器要么苟延残喘，一个月也没有几个新帖子。到了这种地步，根本没有聚集同好的作用了。

怎样的体量才最适宜是难以估计的，也是无法控制的。看过许多网站的生生灭灭，我对虚拟的社区不再抱有过多的期望了。网络这么大，总归有地方能获取信息、交流意见，社区只是交流的场所罢了。

## 东西宅男文化差异

同样是围绕动漫游戏产生的亚文化，东西宅男文化相差甚远，甚至可以说并非同一群体。东方是以日本为主，中韩的动漫游戏大都是模仿日本；西方则是以北美为主，其次是欧洲。东方文化彼此相通，加上从小耳濡目染，我自然偏好日本风格。我两次三番地尝试欧美作品，但始终有水土不服之感，总是有一层隔膜。同样的事物，在不同环境下独立发展，最终居然产生如此大的差异，真是很有意思的一个文化课题。

拿漫画来说，即便是缺乏经验的人，也能一眼看出日本漫画与美国漫画的不同。日本漫画多是黑白，美国漫画则是彩色；日本漫画有符号化的表情和夸张的人体比例，美国漫画则偏写实；日本漫画用分镜和速度线烘托动感，美国漫画则比较静态；日本漫画是由创作者掌控，整部作品剧情连贯风格统一，美国漫画则是铁打的题材流水的画家，情节、画风变来变去；日本漫画更像是长篇小说，定期连载，然后集结出版，美国漫画则更像是集体创作的短篇集，出版情况复杂零碎。以上是粗略的概括，虽有例外，大体上没错。对我个人而言，日本漫画最大的长处就是像长篇小说（也可以说是像电视剧），能完成结构严谨、篇幅宏大的叙事。这也是为什么日本漫画能几乎原封不动地改编成动画、真人电视剧的原因。再有一个突出的长处是题材广泛，没有任何创作限制。漫画在日本的普及程度是任何其它国家无可企及的，从幼儿园小朋友到日本首相全都看漫画。因为受众如此之广，美食、历史、民俗……什么都可画进漫画里。在日本，漫画是主流的艺术创作形式，自然能取得辉煌的成就。

日本动画多是改编于漫画，前面的观点放在动画上依然成立。日本动画的年龄层跨度高，尤其是在大屏幕上，既有《口袋妖怪》《数码宝贝》这种低龄向作品，也有《攻壳机动队》《阿基拉》这样面向成人的作品。美国动画，尤其是电影版动画，则以合家欢乐为主，幽默要素是必不可少的。还有一点是，日本动画长期以2D为主，美国动画则早已由2D转向3D。在皮克斯、迪斯尼、梦工厂清一水地制作3D动画时，吉卜力还在用传统的手绘。在我看来，2D和3D无法互相取代，同时共存是最好的结果。

在游戏方面，刨除掉表层美术风格的差异，更本质的区别在于设计理念的不同。日本游戏重视游戏性，设计游戏是从玩法出发。任天堂正是游戏设计的典范，每款游戏都能看出制作人的思路。比如《超级马里奥兄弟》，就是以跳跃为核心，用敌人安排和地形障碍来增添难度，在需要观察探索和考验特殊操作技巧的地方加入收集道具，用特殊能力改变游戏体验，等等。每个设计都有脉络可循，经过了精雕细琢。欧美游戏则强调拟真，追求体验，比如《侠盗猎车手》就是在都市中横行霸道逍遥法外，《荒野大镖客》就是体验西部牛仔，等等。再举一个类型相同，风格却相差极大的例子，日本RPG讲究战斗系统、养成系统，数值设计严谨，欧美RPG则把功夫花在背景故事、世界探索、剧情分支选择上面。对我来说，游戏是用来玩的，游戏性永远排在第一位。一个不好玩的游戏，画面再漂亮、剧情再好看也没有意义，所以我更喜欢日式游戏。

以上只是探讨风格的差异，并不是评判质量的优劣。我越来越觉得，东西方的动漫游戏追求不同，不应放在同一框架下比较。我也看清了自己是个日系宅，不再强求对欧美文化的理解认同。喜欢高达的就去看高达，喜欢变形金刚的就去看变形金刚，各取所需就好。

## 与作品的机缘

对一部作品的评价是有很大主观成分的。在恰当的时机遇到恰当的作品，就会成全一段美好的回忆。时机不对，再好的作品也可能白白浪费。小时候看的《灌篮高手》《幽游白书》对我有很大的影响，每一段剧情都如数家珍，记得清清楚楚。上大学之后看的《异兽魔都》《医龙》在水准上丝毫不弱于儿时经典，看完却没留下多少印象。有时看到家里没开封的游戏、只看了个开头的漫画，我就会想要是能送到儿时自己的手里该有多好啊。

动漫在连载时追看和完结后一口气看完也是完全不同的体验。追连载把观赏时间拉长了，短则数月长则数年。如此漫长的时间，往往把当时生活中的回忆也混进去了，成了人生的一部分。边看边参与讨论也是一种乐趣，剧情的每一次转折都更加扣人心弦。缺点则是节奏太慢，有时看到后面忘了前面。完结后一口气看完能完整地把握整部作品，冲击力更强，在脑海中留下的印象却更浅。我曾经通宵看完的动漫，现如今都记不得多少了。

我在成人后看动漫，很大程度上是一种弥补童年遗憾的行为。可是有些事情错过了就是错过了，无法事后补偿。人生就是这样。

## 时间的考验

我经常带着补课的心态去找些过去的动漫来看或是找老游戏来玩。这些作品在当年都声名卓著，是轰动一时的大作。一路看下来/玩下来，有些经受住了时间的考验，在若干年后仍然不失为一部杰作；有些则惨不忍睹，让人怀疑当初是怎么出名的。

艺术作品是能超越时空限制的。《水浒传》距今六七百年了，贝多芬的交响曲距今两百年了，依然是一流杰作。而技术则是不断向前发展，一直推陈出新，旧技术很快就过时了。艺术成分越高，技术成分越低，也就越能经受时间的考验。以我的经验来看，在这一方面漫画优于动画，动画优于游戏。手塚治虫六十年代创作的漫画就已经相当成熟了，现在看也非常精彩。动画则受制作工艺、成本的制约，电视动画要到八十年代之后才算定型。游戏严重依赖于图像技术的发展，老游戏受到最残酷的考验，PS、PS2上很多3D游戏都已变的不堪入目。由于2D游戏在技术上没有多大变化，美术水平对画面的影响超过技术水平，九十年代的2D游戏现在看起来依然不错。当下欧美游戏极其重视感官效果，老游戏一旦画面过时就再也没有重温的价值了。将来游戏画面水平和制作成本到达一定阈值时，或许会暂缓无止境的画面追求，把游戏制作的重点放在艺术层面，那时游戏才算是真正成熟。

## 与爱好告别

人是善变的动物，生命中没有什么是持久不变的。曾经狂热沉迷的爱好，有一天却变得索然无味，这是人生的必然规律。依照我个人的经验，热情来得越快就散得越快，越猛烈的就越不持久。我在动漫游戏上投放了过多的热情，高潮退去后也就变得尤其冷淡。《兰亭集序》中写道，「及其所之既倦，情随事迁，感慨系之矣。向之所欣，俯仰之间，已为陈迹，犹不能不以之兴怀。」

动漫游戏都曾是我生活中重要的内容，现在却越来越无足轻重。客观上来讲，动漫游戏的历史太短，成就有限，本来就不如其它的爱好耐琢磨。作为一般的爱好者，单纯是为了观赏游玩，时间一长很容易腻味。主观上来讲，动漫游戏主要针对青少年人群，超过一定年龄后，在心态、审美上就不太适应了。虽然与动漫游戏渐行渐远，我还是要感谢动漫游戏曾经给我带来的快乐、在审美上对我的熏陶。我乐于将动漫游戏作为生活中偶尔的调剂，为它们保留一块小小的空间。作为消遣而不沉溺，或许这才是一门爱好正确的定位。

# 后日谈

我在写作时总是将自己设想为第一读者，而我也确实喜欢重读旧作。《我的宅男生涯》写于2017年夏天，距今（2023年底）已经有六年多了。近来重读这篇文章，首先想到的是用文字记录生活很有价值，其中不少内容我已经记得没那么清楚了，放在今天恐怕写不出来；另外一点是过了这么久，不妨写写之后的一些经历，就当作是原文的后日谈。

先聊动画。其实在写原文时我就很少看动画了，现在则更少了。从2017年至今，我大概每年挑两三部热门动画新番看一看，偶尔会补一补小时候错过的老动画。原文中我写到希望等自己年纪大了仍然能理解年轻人的文化，现在不过三十出头，我发现自己已经不太能明白为什么一些动画如此受年轻人喜欢。比如说《鬼灭之刃》，我看了几集觉得很普通，说不上好坏，只是中规中矩而已，没想到居然能取得破历史记录的成绩。我最近看了一点儿《咒术回战》，内容既视感特别强，好像是用《猎人》《火影忍者》《死神》《乔乔奇妙冒险》的老梗拼凑出来的，偶尔出现的一些猎奇画面和反套路也像是故意整活。我倒也不觉它们有多差，只是看了将近三十年动画，老套路早就看腻了，不自觉就变得挑剔。我在这个年龄也很难被青少年冒险故事打动了，这是没办法的事。我对喜剧片的要求不高，只要能让我笑出来就行。大热的《辉夜大小姐想让我告白》前后三季我都看全了，《游戏三人娘》《佐贺偶像是传奇》这类的动画也能看个乐。《间谍过家家》非常火，我看了几集倒不觉得多么有趣。真正让我印象深刻的是两套经典老动画：《第一神拳》和《机动警察》。这也让我意识到自己的审美偏向于八九十年代的老作品。

漫画方面也是差不多的情况。我这几年看的比较新的漫画有《帝一之国》《炎拳》《电锯人》《黄金神威》《破坏双亡亭》和《MAO摩绪》。古屋兔丸是一位风格多变的漫画鬼才，《帝一之国》画风神似另类漫画家丸尾末广，内容却是校园讽刺喜剧，造成一种奇妙的错位幽默感。前面提到《咒术回战》的反套路太刻意，像是通过夸张行径努力给作品增添一点原创性，而藤本树的反套路就自然多了。从《炎拳》到《电锯人》，我觉得这人的脑回路真的异于常人，有艺术家的个性。虽然他现在还不算太成熟，未来可期。《黄金神威》是冒险、悬疑、民俗、搞笑等元素的大杂烩，我虽然从头至尾看完了，但不算太能欣赏，电波不太合。《破坏双亡亭》和《MAO摩绪》是藤田和日郎和高桥留美子两位漫画大师的新作。这批老一辈漫画家正在逐渐从主流视野中淡出，出于怀旧心态，只要他们还肯画，有新作我都会看一看。我也补完了一些老漫画，比如《向阳之树》《神龙之谜》《功夫旋风儿》和《游戏王》。最后提一下《进击的巨人》，漫画刚开始连载时我就有在看，那时我还在上大学。这部漫画两年前完结，达成史诗级的恶性烂尾，很令我失望，算是负面的印象深刻吧。

在原文中我提到过，动漫商业性非常强，又以青少年为主要目标人群，一旦超过了适宜的年龄段就很难找回当初的乐趣了。我相信自己将来（至少在未来数年）仍然会继续看动漫，但是我认为不会再有哪部作品能对我造成像是《龙珠》《幽游白书》《灌篮高手》《棋魂》那么大的影响了。对我而言八九十年代的经典动漫超出了普通娱乐作品的范畴，是我珍贵的童年回忆。新一代的青少年观众肯定更喜欢现在的新动漫，这是再自然不过的事，流行文化潮流就是这样变换更替的。意识到自己的审美取向已然有了怀旧的标签，是我人生中的新体验。

个人喜好是主观的，我的口味不能作为漫画今不如昔的证据。但有一个客观现象，大概可以为更喜欢老漫画的人辩护，那就是漫画杂志销量大幅下滑（以下数据参考日本杂志协会2023年四月到六月的调查）。《周刊少年Jump》在九十年代巅峰期单周发行量曾经高达653万本，如今只有117万本。《周刊少年Magazine》曾以445万的单周发行量超越《周刊少年Jump》成为日本最畅销的漫画杂志，但是现在只剩下37万本了。《周刊少年Sunday》也从巅峰的200万部跌至如今的16万部。在没有互联网、没有智能手机的年代，漫画杂志在日本曾是一种主流娱乐。现如今娱乐方式这么多，看漫画的人当然就少了。读者少了，投身于漫画界的人才也就少了。当年集中涌现出来一大批才华横溢的漫画家：鸟山明、北条司、荒木飞吕彦、高桥留美子、安达充、富坚义博、井上雄彦、浦泽直树、三浦建太郎……新人漫画家年年有，可是如今绝对找不出同样豪华的阵容。

早些年因为四处搬家，我身边没什么动漫收藏。近几年生活稳定了，买了几套自己喜欢的经典老漫画放在家里。我买的都是法文版，看起来总有一点别扭，名称的翻译尤其令我不习惯。就算看得懂，可是「进藤光」写成「Hikaru Shindo」，「邪王炎杀黑龙波」写成「Ensatsu Kokuryuha」，总觉得差点儿意思，身在海外也没法强求了。明年《灌篮高手》会在法国出完全版，我还是很期待的。

还有一件值得一提的事是我入坑了钢普拉，陆陆续续拼了一些自己喜欢的机体模型。我只是入门的水平，没有改造也没有对细节的追求，能拼完就行，也算是多了一个小爱好。

接下来聊一聊电子游戏。如原文中所说，虽然我很小时就接触到任天堂红白机，但是真正开始大量玩主机游戏是在2011年，距离现在并不远。而且电子游戏的制作质量在客观上随着技术发展不断提升，新游戏的游玩体验比老游戏好。我可以算是「动漫遗老」，但绝对不是「游戏遗老」，并不执着于老游戏。我游戏玩得少了，并不是现在的游戏不如过去好玩了，主要是出于个人原因。2016年是我游戏生涯的一个转折点，这一年我毕业参加工作，业余时间和精力都少了很多。我从事计算机行业，每天都对着电脑屏幕，下班后再对着屏幕打游戏，实在有心无力。现在流行一个「电子ED」的说法，很多二三十岁的年轻人都发现自己突然玩不动游戏了，这是一种普遍的现象。希望自己能对青少年时代的业余爱好终生保持同样的热情，这本来就是一种不切实际的预期。

为了适应新的生活节奏和身心状况，我的游戏习惯发生了不少变化。

由于年龄增长，我的反应速度下降，容易疲劳，也没有时间练习技术，我放弃了所有技术性强、注重输赢的多人竞技游戏。我玩游戏是为了开心，不是要和其他玩家一决高下，何况我早就知道自己会输多赢少。还有一个原因是这类游戏的玩家群体以青少年居多，年轻气盛，容易发生冲突，竞技游戏社区往往不怎么友好，我不想给自己找不痛快。我偶尔玩格斗游戏、RTS或是MOBA，也只玩人机对战模式自娱自乐，从不与真人对战。

基于相似的理由，我也放弃了对游戏难度的追求。只要有游戏难度选项，我一般都会选简单难度。对于魂系列这样以困难著称、没有难度选项的游戏，我的选择是：不玩；对于怪物猎人这样越玩越难的游戏，我的选择是适可而止，如果哪个任务实在打不过去就算了。游戏没了挑战性，会不会太无聊？其实还好。现代电子游戏的乐趣种类很丰富，看剧情是一种乐趣，人物养成是一种乐趣，探索世界是一种乐趣，甚至走路看风景也是一种乐趣，并不会因为战斗难度降低就一下子不好玩了。

流程过长的游戏我也很少玩了。我平均每天打游戏的时间不到一小时，一款流程50小时的游戏要玩将近两个月，上百小时的游戏就要玩小半年了。如果中途一时兴起玩了其它游戏，通关时间就拖得更长了。最夸张的一个例子是《女神异闻录5》，我从2017年四月开始玩，断断续续直到2018年一月才打通。长流程的游戏如果不是一口气打完，中途停了一段时间，再重新捡起来的时候难免会发出「我是谁我在哪儿我要做什么」的疑问，体验很不好。所以我现在更偏向于短平快的游戏，尽量在一两周内通关；或者是关卡制、章节式的游戏，每次至少玩到一个阶段性的终点，将来重新接着玩也比较容易。

我也开始玩手游页游。当初我对这类游戏不屑一顾，觉得质量太差，跟主机、电脑上的大型游戏没法比。可是不得不承认这些游戏太方便了，随时随地都能玩，节奏又快，时间少也没关系。当我想玩游戏，却又没有充足的时间精力时，轻松的手游页游就成了填补碎片化时间的简易代餐。而且现如今手游的制作水准越来越高，早已不可小视。

综合以上几点，可以看出我正在朝向轻度玩家演化。玩游戏能满足娱乐需求就好，每个人都有自己的玩法。我的目标是将游戏阻力减少到最小，不需要提前准备、不会因为难度卡关、不会因为失败而沮丧、不会有外界干扰，每次打开游戏都可以预期半小时到一小时无障碍的快乐时光。甭管别人怎么看，这样一来我至少能一直玩下去。

除了营造客观条件，调整心态也很重要。

很多人都会发现自己买了一大堆游戏却没有时间玩，别说通关了，有时干脆没有打开过。对于这个问题，我想首先应该认清现实，业余时间有限，根本不可能打通所有游戏，不急着玩的游戏不用马上买。一款游戏的时长可以轻易达到几十、上百小时。趁打折狂买游戏时提前算一算打通这些游戏要花多少时间，如果超出了未来数月的自由时间，不妨等几个月再买。游戏总是越来越便宜，错过一次打折也没什么大不了。

更重要的一点是，不要把打游戏当成任务，让堆积的游戏给自己造成压力。订阅XGP改变了我对游戏的看法。XGP里有四五百款游戏，不可能把每一款都打通。把自己买的游戏当成XGP这样的游戏库，想玩就玩，不想玩就放着，没必要有心理负担。

在原文中我提到对游戏的倦怠感，这很大程度上是因为我在短时间内玩了太多同质游戏。现代游戏成本太高，为了避免风险，游戏大厂热衷于出续集，重复已经被市场验证过的稳妥方案。像《使命召唤》和《刺客信条》这样标准的3A游戏我实在玩不动了。好消息是世上的游戏太多了，千奇百怪什么都有，一种游戏玩腻了可以试试别的。只要多一点耐心探索，总能发现新大陆。这里又要感谢一下XGP了，让我可以低成本尝试大量的游戏。

下面聊一聊我这几年印象最深刻的几款游戏。

《血源：诅咒》是我第一次接触魂系游戏，游玩过程却有种浓重的即视感，总感觉这就是3D版的《恶魔城》加上《怪物猎人》的战斗系统。我很欣赏这款游戏的美术设计，成功打造出一个维多利亚风的克苏鲁世界。地图设计也很巧妙，每个区域都有独特的记忆点，打到后面不自觉地就把整个地图记在脑子里了。恶意满满的难度设置则不是太合我心意，打通游戏费了不少精力。现代游戏难度设置更加人性化是一个进步，可以让更多的人而不是只有游戏高手才能从中得到乐趣，刻意增加难度在我看来是矫枉过正了，所以后来我一直没有兴致玩其它的魂系游戏。

《群星》是一款太空背景的4X游戏，系统包罗万象，特别复杂。刚上手时感觉很难，一旦搞清楚了游戏逻辑就很容易沉迷，假期时经常不知不觉就能玩一整天。这种策略游戏如果追求最优化会很累人，我是沉浸模拟派玩家，把每局游戏当成一部太空歌剧，并不非得要称霸银河。《群星》融合了海量的科幻梗，有很多让人会心一笑的小细节，越熟悉科幻作品的人就能越能体会到乐趣。

《塞尔达传说：旷野之息》是一次成功的「新瓶装旧酒」。我这样说并不包含贬义，而是《塞尔达传说》系列历史太长、游戏设计太成熟，核心内容提升空间太小了。单拿解谜和战斗来说，《旷野之息》与众多前作之间并没有本质区别，甚至有些地方还缩水了（大型迷宫数量缩减到四个）。而且玩久了会发现，所有探索内容最后都归结为神庙和呀哈哈，连神秘的龙也不过是用来提供材料收集，让探索的新鲜感打了一个折扣。但是《旷野之息》在全系列中第一次引入真正的开放世界，除了开头几个小时的教学引导，全部游戏内容可以用任意顺序游玩，的确将游戏体验提升了一个层次。

《雀魂》让我学会了日本麻将。麻将的趣味性不需要我来解释了，《雀魂》的成功之处在于降低了入门难度（比如宝牌的提示），把麻将用二次元重新包装，更容易吸引新人。

《杀戮尖塔》是一款非常惊艳的卡牌构建游戏。我玩过一点点《游戏王》和《炉石战记》，觉得卡池太深，机制太复杂。《杀戮尖塔》卡牌数量有限，而且逐步开放，有效控制了游戏的复杂度，鼓励玩家慢慢摸索套路。敌人种类不算多，但是非常有特点。随机抽卡增加了耐玩度。后来我还玩了《怪物火车》，也是不错的卡牌游戏。

《吸血鬼幸存者》是一朵奇葩，画面粗糙，像是同人游戏；操作简单，只要走路吃道具，其余都是自动。这样一款乍看起来莫名其妙的游戏，居然让人一玩就沉迷，简直欲罢不能。这款游戏把玩家心理琢磨透了，高密度、快节奏地提供正反馈，而且游戏内容持续更新量大管饱，其成功是有必然性的。

《崩坏：星穹铁道》改变了我对手游的看法。《崩坏：星穹铁道》的剧情和玩法都很传统，就是JRPG祖传的那一套，但是制作质量极其高，内容堆得非常满：全程语音、大魄力Boss战、文本量惊人。即使忽略掉氪金，主线流程的丰富度也可以媲美主机上的一流JRPG了。

另外我还玩了不少老游戏：

《英雄无敌3》我早在将近二十年前就接触过，但是当初年纪太小，浅尝辄止没怎么玩明白。几年前重新上手，感慨这款游戏的完成度太高了，一点都不过时。我今年玩了《帝国时代2：决定版》，虽然我技术很差，几乎把它当成城市模拟来玩，还是玩出不少乐趣。这些游戏让我确信真正的经典游戏可以超越时间。

《梦幻之星Online》属于最早的一批3D网游，从画面到游戏机制都比较过时，老实讲没法跟今天的游戏相比。但是这款游戏玩起来很轻松，玩家群体以中年人居多，大家心态都比较随和，对新人非常友好，是不错的怀旧养老游戏。

我在初中时就玩过GBA上的机战，那时玩游戏没耐心，嫌流程长、节奏慢，玩了个开头就放下了。几年前我入手了一台DSi XL，心血来潮玩了《机战W》，后来一发不可收拾连着打通了好几款机战。如今机器人动画已是明日黄花，机战已经两年没有任何新作消息，前途未卜，好在旧作多到玩不过来。

还有一些很喜欢的游戏，就不一一细说了，在这里简单列举一下：《女神异闻录5》，《怪物猎人：崛起》，《泰坦天降2》，《超级马力欧：奥德赛》，《血污：夜之仪式》，《伊苏VIII》，《Inside》和《死亡空间重制版》。

这样数一数，发现自己游戏没少玩。我相信喜欢玩游戏是人类的本能，电子游戏可以像体育运动、桌游棋牌一样成为终身爱好。我最近接触了一些开源游戏引擎，没准将来还会把爱好升级，学习开发游戏。

以上就是我在动漫游戏方面的后续经历。新冠疫情期间我长期闷在家里，全靠着自己的兴趣爱好挺过那段时间。人活着总要找点乐子，多一个爱好就多了一种享受人生的方法。动漫游戏在国内一直被污名化，好像上不了台面。其实娱乐只要开心就好，何必分高低呢。当个老宅男，我乐在其中。

# 卷四 娱乐看客 {-}

# 私房电影十选

在这篇文章里，我打算聊一聊自己最喜欢的十部电影。从小到大看过的电影足有上千部，要从中挑出十部来实在不是件容易事。构思这篇文章的时候，十部电影的名单变来变去，难以定夺。我能轻而易举地挑出另外十部电影来，无论是我对其喜爱程度还是电影自身素质都不遑多让。在最终定下的这份名单中，我尽量选择不同风格的影片，以便涵盖我的观影经历、总结我的电影喜好。因为内容题材大相径庭，难以比较电影之间的高低，下面按照上映时间排序。

## 《天堂电影院》（意大利，1988）

第一次看这部电影是在2009年元旦，那时我在上海读书。因为放假的缘故，上海本地的同学和老家较近的南方同学都回家了，宿舍里就剩下我一个人。由于寂寞无聊，我跑去网吧看电影，阴差阳错就看了这部《天堂电影院》。看到最后我泪流满面，完全控制不住自己。后来我把这部电影推荐给父亲，他对外国文化缺乏了解，而且勉强才能跟上字幕，同样也被感动到落泪。这部电影有超出文化隔膜、打动人心的地方，那就是对过往的怀念。无论是谁，多多少少都有怀旧的情结。哪怕再铁石心肠的人，想到童年的趣事、初恋的美好、亲人的关爱，心中总会涌上一股暖流。这部电影就成功地唤起了那份温暖。结尾主人公重回故里是画龙点睛之处，往日旧时光在今日重现。当最终看到老放映师留下的吻戏胶卷，伤感、喜悦、激动……无数情绪交织在一起，让我深深感到这就是电影的魅力。《天堂电影院》不单是一部好电影，更是送给电影的一首赞美诗。

## 《霸王别姬》（中国，1993）

《霸王别姬》是一部史诗电影，看完仿佛过了一辈子。在我看来，《霸王别姬》有三层好处：首先是精彩的故事，构成了电影的骨架，这主要要感谢原作者李碧华；再有是精彩的表演，生成了电影的血肉，尤为突出的自然是张国荣；最后是主题的升华与提炼，铸成了电影的灵魂，这是导演陈凯歌的功劳；此三者缺一不可。后来我读了原著小说，虽然故事够传奇，总觉得少了精气神，流于通俗；张国荣再才华横溢，也免不了被粗制滥造的港片暴殄天物；陈凯歌追求的宏大叙事一旦没了内容的支撑就变得空洞干瘪，他后来的作品素质节节下滑有目共睹。所以这是部享尽天时地利的电影，二十多年过去了，国内再也没能拍出第二部来。这部电影层次丰富，不同的人有不同的欣赏角度。看完这部电影，最让我感概的就是命运无情，人生无常。面对历史的车轮、时代的巨浪，普通人就像小虫小虾，毫无反抗之力。经历过苦难的人，最要紧的不是自怨自艾，而是警醒、帮助后人，不要重蹈覆辙。

## 《大话西游》（香港，1995）

《大话西游》是一部奇特的电影，大概只有华人才能看得出其中的好处。《大话西游》重新解构了《西游记》。这部电影的默认前提是：观众认识孙悟空、唐三藏，知道西天取经的故事；否则连故事都看不明白。正因为中国观众对《西游记》太熟悉了，所以每一处颠覆都造成了奇妙的笑点。在喧哗杂乱、颠三倒四的表面下，《大话西游》讲述了一个伤感的爱情故事。人与人的相遇，有相见恨晚，也有相见恨早。拥有时不知道珍惜，错过了已追悔莫及。现实不是童话故事，总有重重阻隔让王子和公主不能在一起。当结尾响起《一生所爱》，终于明白什么是笑中带泪。内心太悲伤，才要装作若无其事。

## 《攻壳机动队》（日本，1995）

我看过太多精彩的日本动画电影了，《幽灵公主》《岁月的童话》《阿基拉》《千年女优》……实在难分高下。选择《攻壳机动队》是因为它对我有启发式的影响，让我知道原来动画可以这么酷，原来动画可以探讨这样复杂的问题。《攻壳机动队》讨论自我的定义：当人体机械化，当人的记忆可以被篡改，要怎样确定自我呢？自我是不是寄居在驱壳中的灵魂呢？我认为，自我是持续变化的，并非永恒不变。即使没有动画中高科技的影响，人从青少年到成年、老年的生长过程，同样经历了人格的改造。我不相信身心二元论，如果我的肉体被替换，我的感官、欲念、性格必然也产生变化，不可能存在一个不变的灵魂。说到底，如果我能确定自我的存在，确定我拥有自由意志，那就足够了。无论自己身为何种形式，并不会让我动摇。当然，这是一部动画，而且是影像技术高超、惜字如金的动画，并不会也没必要像论文一样全面深入。能带来故事和视觉上的享受，又能激发观众的思考，《攻壳机动队》是当之无愧的杰作。

## 《黑客帝国》（美国，1999）

如果事先看过《银翼杀手》《攻壳机动队》，读过赛博朋克小说，会发觉《黑客帝国》并没有太多的新东西。但这并不是《黑客帝国》的缺点。正相反地，将旧要素整合包装，用新形式展现出来，这是通俗文化的一种继往开来的繁衍方式。奥德赛、罗密欧与朱丽叶、西游记乃至福尔摩斯探案、007，这些故事里的经典要素都被反复借鉴与演绎。比起原始母本，《黑客帝国》包装更华丽，节奏更快，更容易被广大人群接受，说它是赛博朋克文化的集大成者并不为过。《黑客帝国》是一个惊艳的开端，预示着鼓舞人心的未来，然而随后两部并不太合我心意。值得一提的是，这部电影请了袁和平做武术指导，给西方影视业带来正面影响，此后好莱坞电影动作戏水平显著提升，可谓额外的惊喜。

## 《关于我母亲的一切》（西班牙，1999）

西班牙的影视作品总给我留下夸张、过于戏剧化的印象。阿莫多瓦的电影充斥着谋杀、变性、同性恋这些强烈的戏剧要素，更加强化了我的刻板印象。《关于我母亲的一切》里，女主角的儿子一开始就遭遇车祸去世，她的丈夫变性做了妓女还染上了艾滋病。这种离奇的剧情实在太远离现实了。影片中却把这种超现实的苦难拍的真实自然，娓娓道来。这部电影中的女性都对苦难有着强大的承受力，什么痛苦都能用泪水化解，还能宽恕生活中的不幸，惨痛的故事拍的温情脉脉。女人是情绪化的，戏剧化的，却更柔软，更坚韧。题目中的「母亲」一词也突出了女人母性的特点。电影开头女主角失去儿子，为了儿子的遗愿去寻找伤害过自己的丈夫；结尾处身染艾滋的修女产下了婴儿，这孩子奇迹般地没有染病。以母亲的身份，女人可以变得更温柔、更强大。我觉得这部电影的好处，就在于深入探讨和阐述了女性的特质，是一部挖掘人性的佳作。

## 《笑的大学》（日本，2004）

《笑的大学》原本是部话剧，剧本千锤百炼，可以作为编剧的教学典范。整部影片的角色安排和场景设置非常简单，就是两位主演，一张桌子，两把椅子，所有内容都要靠演员的表演来展现。这部电影的结构也非常简单明了，看过开头十来分钟就能猜出后面的套路来，就是审查官不断刁难编剧、编剧巧妙地修改剧本。正是这份简单才考验真功夫。假设只保留这个创意，把具体内容换个人来创作，能不能做到同样的简洁洗练，每一个转折、每一处笑点都恰到好处呢？原作三谷幸喜的表现堪称完美，几乎挑不出毛病来，我想很难有人能做到更好。当然，工整的过了头也算是个微小的缺点吧，毕竟匠气有点重。好的喜剧不仅是幽默，更要有内涵。影片中讽刺的文艺审查，估计所有创作者都心有戚戚焉。哪怕是今时今日，自由创作仍旧是件奢侈的事。有技巧，有内涵，《笑的大学》是部了不起的喜剧片。

## 《坠入》（美国，2006）

与这份名单里其它赫赫有名的影片相比，《坠入》是部比较小众冷门的电影。不夸张地说，《坠入》是我看过的最美的电影，我很讶异这部电影没有取得更高的声誉。这部电影的故事很有博尔赫斯、卡尔维诺的风格，反映了叙事的模糊性。影片中一位意外致残、一心寻死的特技演员在病院里认识了一个小女孩，每天给她讲幻想故事，想借机利用她拿到安眠药自杀。这幻想故事荒诞不羁，情节桥段来自于他参演的粗劣影片；可是经过小女孩的想象，竟然完全变了一番面貌。小女孩按照自己的理解（比如把主角讲的印第安人当成了印度人），脑补出一个个绚丽动人的场面。纯真孩童脑海中的世界实在太美好，影片中的每一帧都色彩斑斓、美轮美奂。与许许多多高深复杂的电影相比，这份自然童趣更能打动我。

## 《狩猎》（丹麦，2012）

电影是门综合艺术，不一定非得要有个明确的思想主题。但有一类电影，明显是带着鲜明的立意来拍摄的，体现出创作者的社会责任心，想为现实社会造成正面的影响。早年的《偷自行车的人》《十二怒汉》，近些年的《熔炉》《辩护人》都是有重要社会意义的电影，《狩猎》也可以归入此类。这类影片里我更偏好《狩猎》，因为它的手法更自然，所反映的内容也不限于一时一地。影片中男主角被诬蔑侵犯儿童，在法庭宣判无罪后仍然受到周围人的歧视。结尾时他似乎重新融入社会，然而背后依旧隐藏着让人不寒而栗的黑枪。在我看来，热衷于道德审判的人是把道德退化为原始的禁忌，完全曲解了道德的意义。仅凭片面的信息，就认定一个人罪大恶极，做出低下的攻击，这是缺乏文明、藐视法律的行为。《狩猎》客观冷静的风格也让我非常欣赏。光有一腔热血解决不了问题，实事求是、客观处理才是正确的态度。

## 《鸟人》（美国，2014）

《鸟人》的每一个环节都完成的太漂亮了，让我赞叹不已。长镜头手法非常华丽，能把紧张的戏剧冲突、复杂的内心情绪一镜到底拍出来，堪称炫技。背景音乐也选的太好了，鼓点时而随性时而压抑，让我见识到了打击乐的魅力，没有旋律一样能感染人心。影片中主角对理想主义的追求让我感同身受，想要追求艺术却受到各方面的阻挠，连自杀都成了媒体从中牟利的热点新闻。几位演员的现实经历也为电影造成了一种真假莫辨的奇妙效果，过气好莱坞明星来演过气好莱坞明星，知名方法派演员来演知名方法派演员，现实与虚构混杂在一起，可谓神来一笔。《鸟人》是部耐看的、手法复杂的影片，每次观看都能从中学到不少东西。随着时间流逝，我猜想《鸟人》的地位会越来越高，成为公认的现代经典。

以上就是我选出来的十部影片。正如开头所说，这是个困难的选择。如果过一个星期再问我，恐怕我就会答出另外十部影片来。至少可以确定的是，这十部电影都是我心中的杰作，足以反映我的审美趣味。

最后再聊几句离题的话。我认为不同的艺术形式有不同的成熟程度。跟文学、绘画、音乐相比，电影实在太年轻，或许还没有到真正的成熟阶段。跟其它艺术形式中的经典作品相比，我对著名「老」电影的价值是存疑的，以为它们并没有像莎士比亚、巴赫那样足以承受时间的考验。我觉得很多过去的电影有重要的历史价值，但未必有重要的艺术价值。比如说希区柯克是电影界的伟人，他的悬疑手法大家都要学。经过反复的试验、发展，希区柯克的技法已经化成养分被吸收干净，现今的悬疑片要比希区柯克的片子好看得多。诚恳地说，我认为今天的观众即使不看希区柯克的电影也不会错过太多。我选出来的这些影片都离现在比较近，其中包含着我的这一态度。不断涌现出新的好作品，正是艺术蓬勃发展的明证。

# 续·私房电影十选

之前写过一篇《私房电影十选》，发到网上后，有些朋友很喜欢，鼓励我再写一篇续集。我想了想，上一篇刻意选择年代较近的影片，这次不如就都写老片吧，正好作为互补。以下十部电影都老过我，依照上映时间顺序排列。

## 《卡萨布兰卡》（美国，1942）

《卡萨布兰卡》的故事颇有武侠味。一个冷若冰霜、愤世嫉俗的男人，在异域开了一间酒吧。这酒吧是个自成一体的小世界，黑白两道鱼龙混杂；不管你身份多高，多富有，到了这里就要服从这里的规矩。这男人开口讲话都是一股古龙味：「昨日过去太久，我已忘了做过什么。今夜太遥远，我不知自己会做什么，因为我从不做那么远的打算。」这样一个天不怕地不怕的硬汉，心里唯一的伤口，自然是一个女人。这女人很美，看她一眼就明白，对于她身边的任何一个男人，她永远是故事的女主角。女人抛弃过男人，给他留下除不去的伤疤；多年后突然出现，居然开口就让他冒天大的险，而他居然答应了。经过一番生死冒险，两个相爱的人就此分别，相忘于江湖。异域风情、惊悚悬疑、感情纠葛，一样不缺，怎能不拍出好故事？男主演鲍嘉相貌普通，个子不高，微微驼背，却男人味十足，不靠脸一样帅死人。

## 《日落大道》（美国，1950）

《日落大道》是一个以「衰老」为主题的故事。美国文化，尤其是好莱坞电影文化，近乎病态地狂热追捧青春美貌。一位电影明星，往往年纪轻轻就达到人生巅峰，被鲜花与掌声围绕，享受到任凭谁也无法抵抗的虚荣；可是随着年龄增长，接下来就要眼睁睁地看着这一切一点一滴逝去。除非有大智慧，很少有人能经历这样的大起大落而不迷失自我。《日落大道》里的默片明星就因此而癫狂了，她贪婪地渴求青春、声誉和爱，那份扭曲的执著令人恐惧。片尾她走下楼梯那著名的一幕，简直像是一出恐怖片了。电影中不仅有讽刺，还有深切的同情，是一首献给默片时代的挽歌。这就使得此片很有一种佛教看透人间虚幻的思想情怀，这在西方电影里是不多见的。电影中另外一条故事线是落寞不得志的编剧，一步步放弃理想、委身于老女星，这是名利场中又一种典型悲剧。前几年莱恩·墨菲拍的迷你剧《宿敌：贝蒂与琼》与这部电影有异曲同工之妙，同样推荐一看。

## 《七武士》（日本，1954）

《七武士》的故事情节非常简单，就是七名武士受农民所托，抵抗山贼。假如写成小说，恐怕几页纸就讲完了。《七武士》好到可以当教材，用来教人怎么拍电影，不是因为剧情，而是由于精彩的影像叙事。《七武士》中大量段落完全没有台词，直接把情景展现在观众眼前，让你自己去看。武士与山贼的恶战，场面调度无懈可击，繁而不乱。这样的电影，一定要一帧帧分析才能品出好处，文字说明有心无力。与《七武士》相比，国内那些台词啰哩啰嗦的影视作品大概只能算是广播剧。无法被文字浓缩，只有亲自去看才能体会其好处，我想这样的电影才配得上艺术二字。

## 《宾虚》（美国，1959）

《宾虚》是一电影史上屈指可数的史诗巨作，其气势之恢弘令人惊叹。我前些年重看了蓝光版，感慨片中的大场面放在今天仍然不过时。当年没有电脑特效，所有场景都是实拍。最著名的四轮马车大战那一段，十几分钟的戏足足用了三个月才拍好。看到这样壮观的视觉奇迹，我不得不对好莱坞黄金时代的电影人肃然起敬。除了精彩绝伦动作场面，这也是一部宗教色彩浓厚的影片。我并非基督徒，但同样被电影中耶稣的故事所打动，因为宽恕与仁爱是普世的精神。如果你喜欢《角斗士》《天国王朝》这样的历史大片，那绝对不能错过《宾虚》。

## 《阿拉伯的劳伦斯》（英国，1962）

大卫·里恩是我最喜欢的导演之一，他以荡气回肠的鸿篇巨制著称，片长动辄三四个小时。虽说电影好坏不取决于长短，但形式与内容是不可分割的，有些故事一定要足够篇幅才能充分发挥。《阿拉伯的劳伦斯》讲述了一个残酷而又带有异国浪漫气息的战争传奇，片中最吸引人的是对主角劳伦斯的塑造。历史上那些创下丰功伟迹的英雄人物，是伟大的超人，还是命运的宠儿？电影中的劳伦斯无疑具有杰出的军事才能，同时他也爱出风头、喜欢哗众取宠，以至于一度被胜利冲昏了头脑，真以为自己具有神力、无所不能了。他致力于阿拉伯民族解放，付出了惨痛的代价，最后却被政客出卖，终究是作了大英帝国的一颗棋子。历史上的劳伦斯也是一个充满争议的人物，这部电影虽然并不完全符合史实，却真实刻画出了英雄人物的迷惘与无奈。

## 《黄金三镖客》（意大利，1966）

香港译作《独行侠决斗地狱门》，浓浓的邵氏武侠风。当年我在同一周看完镖客三部曲，同时打通《荒野大镖客：救赎》，过足了牛仔瘾。荒野大漠，一人一马，快意江湖，岂不快哉！当电影开场经典的口哨声响起，我的劲头立马就上来了。这部电影三个主角，一个负责耍帅，一个负责扮狠，一个负责搞笑。三人斗智斗勇，好戏叠出，在冒险夺宝之余，还穿插了一场悲情的战争大戏。最后三人坟场对决更是经典。

## 《教父》（美国，1972）

电影史上一个有趣的现象是，伟大电影往往改编自二流小说。我读过《教父》原著，没有留下太深的印象，感觉不过是本普通的通俗小说。而由此改编的《教父》电影前两集却被公认为电影艺术的巅峰。这是为什么？我认为，一部杰出的艺术作品，必然充分发挥了其艺术形式的特色，比如文学中的修辞，电影中的表演。既然这优点与形式紧密连结，也就难以在改编为另一种形式时保留下来。无论一个摄影师如何努力，也都无法还原「落霞与孤鹜齐飞，秋水共长天一色」的艺术美感；而无论文字多细致，也无法还原马龙·白兰度在《教父》开场的伟大表演。电影在改编小说时，往往只留下故事，而把文学艺术性都遗落了。所以重视故事情节的通俗小说反而更适合改编成电影。《教父》在摄影、表演、配乐等方方面面都近乎完美，把一个黑帮故事上升为史诗，每次看都有新的感受，无愧为影史经典。

## 《骗中骗》（美国，1973）

这部电影在两岸三地的译名大相径庭，香港译作《老千计状元才》，台湾译作《刺激》，依我看还是大陆译名《骗中骗》更贴切些。这是一个行骗的故事，叙事稳扎稳打，干净利落，逐个小节向前推进：介绍人物、规划骗局、招兵买马、引人上套、实施骗局、出奇反转。正因为模式化，更考验编剧的功力，在套路里玩出花来。或许《骗中骗》没有太多艺术上的创新，但是足够巧妙好看。

## 《唐人街》（美国，1974）

《唐人街》的故事情节结构坚实，环环相扣。照着电影把故事记下来，几乎不用更改，就成了一本雷蒙德·钱德勒风格的好小说。《唐人街》的剧本被很多人认为是史上最佳。麦基那本著名的编剧教科书《故事》就总爱拿《唐人街》举例，视其为写作典范。《唐人街》由始至终一直保持着悬念，情节扑朔迷离；每次解决了一个疑问，却又引出更大的疑问；最后真相大白，，每处伏笔都发挥了作用。重看《唐人街》时我突然联想到了克苏鲁神话。主角从一件小事开始被卷入到神秘事件中，不自觉越陷越深，发掘出比预想中更庞大的邪恶。结尾也符合克苏鲁神话的惯例，带有一种虚无的宿命感，主角对邪恶无能为力。近年的美剧《真探》也是相同的风格，大概受到了《唐人街》的启发。

## 《办公室的故事》（苏联，1977）

作为一个中国八零后，我一直对苏联抱有复杂的感情。一方面，我熟悉苏联冷笑话、古拉格群岛，知道老大哥的恐怖；另一方面，当我观赏苏联文艺作品时，又不自觉地被其中的宏大叙事和理想主义所吸引。不过这部《办公室的故事》一点都不宏大，是平凡人的爱情喜剧，恰恰扭转了我对苏联的刻板印象。男主角是一个其貌不扬的中年人，戴着厚厚的眼镜，举止笨拙；他被老婆甩了，一个人照顾孩子。女主角是一个男人婆，不苟言笑，孤僻难相处，是男主角的顶头上司，男主角在她面前一直畏手畏脚。这两个人原本互相厌恶，没想到由于一系列的阴差阳错，居然起了奇妙的化学反应，最后成了情侣。这种故事其实很俗套，可是由于出色的情节设计和表演，从头到尾笑点不断，成了我最喜欢的喜剧片之一。

既然聊到了老片，不妨再说几句题外话。作为影迷，观影经验积累到了一定程度，少不了要看老片补课。那些影史上的经典名作，有些放在当下依然好看，另外一些恐怕就不容易吃得消了。相当多的名作是由于技术开创性而留名史册，比方说巴斯特·基顿开创了肢体喜剧表演风格，连成龙都是学他，他的《将军号》被公认为影史经典。然而对于今人来说，肯定还是成龙电影更好看。再比如《公民凯恩》是当年电影叙事、镜头、剪辑技术的集大成，被尊为最伟大的电影，可这并不代表它真的比其它所有电影都好。电影是大众娱乐，我不相信有什么电影非看不可。我选择这十部电影的方针偏重于「好看」，标题改成最适合新观众的老电影也说得通，希望能为读者提供有益的参考。

# 谈香港电影

在少年时代，我看的电影九成都是香港制造。当年很少去影院，看的电影要么是在电视上播的，要么是租的影碟。印象中香港电影的影碟封面夸张露骨，即便是巨星名导的作品也显得格调不高。小时和大人一起去租影碟，滿墙稀奇古怪的封面时不时给我造成一些不适。大概是旧电视和盗版影碟的过错，记忆中的香港老电影全都画面模糊，色彩失真。香港电影往往配有字幕，可是粤语字幕与国语对白各讲各的，有时失之毫厘谬以千里。香港电影的题材似乎总是功夫、枪战、搞笑、赌博、恐怖，同类影片总是充斥互相抄袭的雷同桥段。如此种种，即便在小时候我也意识到香港电影的粗糙，与《泰坦尼克号》《拯救大兵瑞恩》等好莱坞大片不可同日而语。话虽如此，形式粗糙的香港电影曾为我带来无数的快乐。自从《无间道》开始，香港电影越来越精致了，可是反倒失去了当年的趣味。总听人说现在的香港电影没有港味了，我也深有同感。至于港味到底是什么，三言两语很难讲清楚。我之前读过一本《香港电影的秘密》，其作者大卫·波德维尔是位著名电影理论家，详尽地探讨了香港电影在导演、剧本、摄影等方面的技术特点。我对专业技术所知寥寥，只谈谈作为普通影迷的感受。

说起香港电影的特色，我首先想到的是功夫片。中国武术文化源远流长，在小说、戏剧、影视、动漫等诸多艺术形式中都有体现。早在上世纪二十年代我国便开始拍摄武侠电影，香港五六十年代的黄飞鸿电影红极一时。我所看过的最早的武术题材电影则是李小龙七十年代拍摄的四部半功夫片。这几部电影情节简单，无非是正邪对抗，精彩之处全在于李小龙的功夫表演。李小龙采用远镜头，动作看得清清楚楚，这点极其令我欣赏。功夫片就是要看硬功夫，那些镜头切得花里胡哨的都有投机取巧之嫌。李小龙的动作迅猛简洁，在快速急促的进攻后往往加入一段停顿，制造动静对比，更加强化动作的魄力。这些动作场面虽然没有台词，但是依然富有戏剧性的起承转合，观众能清晰地感受到开始时的受挫，中途激烈的对攻，后期形势的转折，最终大获全胜。最典型的例子就是《猛龙过江》结尾在罗马斗兽场的决斗。紧随其后的成龙则是在动作中加入了喜剧要素。比起战无不胜的李小龙，成龙的形象更加亲民，他在电影中总是要经历辛苦和狼狈，最终获得来之不易的胜利。成龙的打斗往往发生在杂乱无章的环境，他会利用身边的道具，与环境互动，实现花样百出的动作场面。比如《A计划》中精彩的自行车巷战，还有《醉拳2》中钢铁厂的乱斗。另一位功夫巨星李连杰则具有传统大侠的气质，一身正气，动作潇洒，一举一动都有武林宗师的气度。最能体现李连杰个人风采的就是《黄飞鸿》。九十年代初受《东方不败》的影响，兴起大量新派武侠片，注重声光特效。这类武侠片与神怪片无异，武林高手在天上飞来飞去，挥一挥手就四处爆炸。此类电影中，最精彩的几乎都是林青霞主演，如《东方不败》《新龙门客栈》《白发魔女传》等等。林青霞的古装扮相兼具美艳与英气，演反串角色无人能敌，堪称影史上的传奇。

香港功夫电影独领风骚，这要归功于武术、京剧、武侠小说等多方面的文化积淀，无数武师、演员们的辛苦演出，还有导演、摄影师的想象力和不断的探索。我从小看功夫电影，习惯了高水准的动作演出。当我看其它国家的电影时，总觉得打戏不过瘾。比如说《星球大战》，绝地武士的挥剑动作又慢又假，看得我昏昏欲睡。直到《黑客帝国》之后华人武术指导进军好莱坞，美国电影的打斗场面才算能看了。

香港的枪战片也堪称独树一帜。枪战片其实是个很模糊的概念，警匪片、黑帮片、赌博片都有枪战的要素。说起枪战片，我想到的是吴宇森执导的《英雄本色》、林岭东执导的《侠盗高飞》、杜琪峰执导的《枪火》等等。在我看来，香港的枪战片与武侠片是近亲，故事背景总是充满江湖味，角色们都像是从武侠小说里走出来的侠客，只是把刀剑换成枪炮罢了。香港枪战片中所有看似古怪奇特的设定，当成武侠片来看就全说得通了。就拿吴宇森的电影来说，主角总是富有英雄气概，为了义气两肋插刀，动作设计总少不了飞身射击，时不时莫名飞出一群鸽子。持续不断的正邪对抗、结尾夸张的大决战就更像武侠片了。《侠盗高飞》中周润发右手致残，苦练左手用枪，这段简直让我联想到《独臂刀》。这些电影在外国人眼里或许用力过猛，煽情过度，看上去都像邪典电影，对国人来说却是喜闻乐见。

喜剧片是香港电影的另外一种主流类型。香港电影不爱端架子，很少从头严肃到尾，不管什么片子都要加些搞笑桥段。像之前提到的成龙电影，大多可以归类为动作喜剧片；像《赌神》这样的，可以算作赌博喜剧片；还有像《僵尸先生》这样的，可以算作恐怖喜剧片；一点喜剧要素都没有的香港电影才是另类。

香港电影情节零碎，剧本不够坚实，这点在喜剧片上尤其突出。在我印象中，很少有哪部香港喜剧片讲了一个情理通顺的完整故事。香港喜剧片往往是用一连串密集的搞笑桥段串联而成。当我和朋友们讨论某部港片如何搞笑时，不太会谈到剧情设计的巧妙，而是会大谈特谈某个搞笑桥段。香港电影中的搞笑桥段简单直接，无所不用其极。比如说扮丑，像是《东成西就》里梁朝伟的香肠嘴和梁家辉的女装，《食神》里莫文蔚的龅牙，还有在各种电影里客串的如花和八两金；比如说下三路笑话，《家有喜事》中毛舜筠打张国荣的脚板配上配角大便的呻吟，《百变星君》中周星驰下体变花洒；还有性笑话，像是《国产凌凌漆》里喷火的胸罩，《鹿鼎记》里海公公收藏的各种鞭；再比如各种幸灾乐祸的情节，搞笑电影里的角色总是跌倒、被殴打、被车撞，总少不了鼻青脸肿的镜头。这些手法或许低俗幼稚，但确实行之有效。而且这些桥段并不是像看上去那样简单，要拿捏好分寸很不容易。电影角色需要讨人喜欢，要做到贱格而不猥琐、好色而不淫荡。很多桥段之所以好笑，是因为演员演的好笑，换一个演法恐怕就不行了。香港有一批极其出色的喜剧演员，除了能独挑大梁的周星驰、许冠文、黄百鸣等人，还有吴孟达、吴耀汉、黄韵诗、苑琼丹这些出色的绿叶，即便是极小的配角也有一手绝活。除此之外，香港演员放得开，再大牌的明星也能无所顾忌地恶搞，周润发、张国荣、梁家辉、梅艳芳、郑裕玲都不乏喜剧佳作。相比之下大陆的演员就比较拘束，巩俐出演周星驰电影时就显得水土不服。

香港喜剧片总是采取底层的视角，对高大上的角色报以嘲笑，越是地位显赫、光鲜靓丽的，越是要讽刺其阴暗虚伪的一面；小人物历尽艰辛，最后总会换来一个快乐的结局。经历过生活的困苦，同时保持乐观的心态，这样才能拍出感人、不做作的喜剧片。《喜剧之王》就是绝佳的代表，几乎可以说是香港喜剧片的榜首。主角尹天仇从头至尾都严肃认真、兢兢业业、百折不屈，并不刻意搞笑，这种一根筋的态度反而制造出了笑点。剧中龙套演员所受的种种挫折，明显包含了周星驰自身的生活经历，夸张中显出真实。龙套演员和舞女之间爱情故事，没有太多文艺浪漫，却令人感动落泪。可惜结尾太刻意，破坏了整体结构，这点也算是香港电影的通病了。

香港电影的跟风程度令人震惊，只要一部电影红了就会迅速涌现出大量仿作，明目张胆地使用雷同桥段。比如《赌神》火了，之后就冒出一堆《赌圣》《赌侠》《赌霸》《赌王》；《倩女幽魂》的成功引出一大堆古装鬼片，光是王祖贤都不知演了多少次女鬼。由于这种不断的模仿衍生，香港电影细分下去有许许多多的子类型。不过在我看来这些子类型都是流行要素的拼贴，香港电影最突出的还是动作和搞笑这两样。其余类型的商业片我就不详谈了，接下来说说文艺片。

文艺片是个定义模糊的词，是华人圈特有的说法。要我说所谓文艺片就是没有武打、赌博、僵尸这些明显商业卖点的电影，只好将其归类为文艺。香港的文艺片多是爱情题材，往往会请大牌明星来撑票房，商业性并不弱。如果不是放在香港电影商业至上大环境中，这些电影大半会算作商业爱情片，比如《秋天的童话》《胭脂扣》《新不了情》《甜蜜蜜》等等。还有比较偏向现实主义的，比如《女人四十》《桃姐》，反映香港本土生活，在拍摄手法上就比较平淡。要论特色鲜明，不得不提的就是王家卫。

王家卫的电影情节零碎，节奏缓慢。他拍电影的方式也相当随心所欲，最出名的是没有剧本，人物设定、故事走向都变来变去。他的电影要拍成什么样，要拍多久，全都是未知数。这种艺术家的任性几乎到了骇人听闻的程度，比如《春光乍泄》中原定的女主角关淑怡去地球另一边的阿根廷拍戏拍了一年多，最后戏份全部删光。《2046》拍了五年，《一代宗师》更是拍了十年。极度商业化的香港影坛能出现王家卫，证明了艺术与商业并非对立。我一直相信，艺术并不是空中楼阁般凭空出现的，艺术家也要吃饭，商业汇集起来的金钱和人才才是培养艺术的健康土壤。正因为香港电影产业发达，产量巨大，所以才能出现王家卫这样的奇葩。

回过头来继续谈王家卫的电影，我以为他的电影本质上是静态的，角色从一开始就成型了，直到结尾才会产生突然的变化。比起叙事，他的电影更像是画作，执着于瞬间的美感。王家卫电影里忧郁伤感的男男女女，说穿了不过是纠结于“我爱的人不爱我”或是“相爱却错过”这些爱情剧俗套，但是配合表演、镜头、音乐，这些情绪和伤感氛围格外地引人沉溺。所以我对王家卫的兴趣是美学上的，并不太在意故事和隐喻。

以上提到的电影，基本集中于八九十年代。香港电影在那段黄金时代创下了一个奇迹，产量、票房都仅次于好莱坞。从九十年代中期开始，香港电影迅速衰落，多家电影公司倒闭。香港电影衰落的原因包括经济衰退、好莱坞大片入华、盗版泛滥等等。现如今高成本的香港电影基本都是与大陆合拍，纯本土电影只剩些小成本作品了。对我来讲，最直观的感受就是香港电影圈已经好多年没有出现像样的新人了。我小时候看电影就是双周一成、四大天王，现如今为香港电影撑场面的还是这些人。最后一批成功的造星大概是谢霆锋、余文乐那一代，这些演员也都已经年近四十了，而且影响力远逊前辈。因为缺少人才，古天乐、张家辉这样的中坚演员成了劳模，看来看去每部戏都是那几个人。

从辉煌到衰落，这种英雄落魄的故事总令人感慨万千。香港电影伴随了我的青春成长，更为其增添了一份怀旧情怀。所以不难想象，我对香港电影是有深厚感情的。但是客观来讲，我以为香港电影的现状才是回归常态。毕竟如果奇迹长存，那也就不能称之为奇迹了。除去情怀滤镜，即便在鼎盛时期，香港电影也有粗制滥造之嫌。由于过度功利，一味追求精彩桥段，香港电影常有佳句而罕有佳章。近年来不断有香港电影利用影迷的怀旧情怀搞宣传，炮制出徒有其表的情怀大片，令观众大呼上当，这也使我不得不反思自己对香港电影的态度。影迷最在乎的是电影质量，产地其实无所谓。香港电影融入到华语电影中，这何尝不是一种新生。至于美好的回忆，就让它停留在过去吧。

# 谈日本动画电影

人总是容易对年轻时的事念念不忘。年轻时读过的书、看过的电影、听过的音乐往往会给人留下深刻印象，伴随人的一生。说起电影，最令我难忘的是八九十年代的电影，其中又以香港电影和日本动画电影为代表。这篇文章里我想谈谈后者。

动画是种成本昂贵的艺术。八九十年代电脑作画尚未普及，日本动画电影主要都是靠手绘。在影院上映的动画要追求品质，不能像电视动画那样偷帧数浑水摸鱼。一部九十分钟的动画电影，作画数轻而易举就要超过十万张，这个工作量想想都可怕。而且动画的题材和受众受限制。一般都拍些民间传说和童话故事，观众以青少年为主。成本高加上受众少，动画电影相对来讲算是小众。在相当长的一段时间里，能保质保量拍动画电影的只有迪斯尼。

我小时候只看过零星几部动画电影，包括迪斯尼的《人猿泰山》，国产的《哪咤闹海》《宝莲灯》等等。说实话我对这些电影兴趣不大。直到初中后，由于网络的普及，我才见识到日本动画电影的魅力。

日本动画电影带给我的首先是视觉上的冲击。无论迪斯尼还是国产动画电影，人物线条都比较圆润，整体画风偏向低幼化。当我看到《阿基拉》和《攻壳机动队》时，真是第一眼就被惊艳到了，未曾想到动画的美术风格也能这样冷峻。《阿基拉》中天塌地裂般的破坏场面，《攻壳机动队》中高速凌厉的动作镜头，都令人一见难忘。日本动画电影的另一特色是题材多样，科幻、悬疑、冒险、爱情应有尽有，不拘一格。《未麻的部屋》大胆前卫，《岁月的童话》细腻写实，这些题材恐怕只有在日本才会被拍成动画。

我这些年来看过的日本动画电影大概百余部。接下来我挑选其中代表性的作品，按照导演分别讨论。

## 宫崎骏

宫崎骏毫无疑问是日本动画导演中最著名的一位。一开始时我对他并不十分喜欢。之前介绍了我接触日本动画电影的经历，不难理解我起初是被面向成年人的动画所吸引。青春期少年往往急于摆脱童年的稚气，宫崎骏的动画在当时的我看来过于童趣了，一点都不酷。此外，宫崎骏的电影有着鲜明的思想主题，用不容置疑的态度阐述自己的想法，这让我联想到了国内的教育片，不由得产生了反感。直到自己真的长大后重看宫崎骏的电影，才慢慢体会出他的好处来。现在我仍谈不上多喜欢他的动画，但是不得不承认他是一位天才人物，是真正的艺术家。

首先要说的就是他一流的动画技术。动画不单单是绘画，还包括对镜头和动作的理解。没有技术做支撑，一切艺术思想都是空中楼阁。随便挑出他的任意一部电影，任意挑出一个片段，都能看到精巧的构图，丰富的细节，流畅的动作，以及蓬勃而出想象力。当然，动画不是一个人的功劳，这些都要感谢吉卜力工作室辛勤工作的画师。但宫崎骏是出了名的“暴君”，对动画的把控直到最深入的细节，最终成品很大程度上要归功于他。

其次是他杰出的叙事能力。宫崎骏既能画又能写，他的动画都是自己担任编剧。宫崎骏的动画并没有什么特别的叙事花样，从来都是直来直去。所谓大巧不工，就是这份直来直去才显示出大师的气派，他不需要什么噱头，拍出来的故事就是好看。我看的小说、影视越多，就越觉得能写出好故事是稀有的才能，绝大多数的作家、编剧都是重复旧有的套路罢了。所以我十分佩服宫崎骏正面出击的叙事能力。

再有是他动画中的思想性。动画电影成本高，必然趋向商业化，即便是成名的大导演也没有几个能坚持自我表达的，而宫崎骏始终执着于个人表述。他的几部代表作都是以人与自然的关系为主题，尤其以《幽灵公主》为集大成的杰出代表。正像《幽灵公主》中对不同势力的多角度描述，宫崎骏并没有单纯肤浅地将人或自然的某一方定义为善或恶，而是激发观众思考如何能让两者和谐相处。我不觉得宫崎骏是深刻的思想家，但是能把严肃的探讨引入到动画中，这已经是件很了不起的事。

最后是他旺盛的精力。不得不说，有雄心壮志的人才能做出伟业。宫崎骏全身心投入到动画事业中，拍出一部又一部规模宏大的动画电影，为常人所不能为。他统筹全局的魄力，对完美的严苛追求，都体现出天才的气质。他几次说要退休，然后又出尔反尔，实在是缺乏自我认知。我相信他一定会工作到最后一刻。

在宫崎骏的众多电影中，我最喜欢的是《幽灵公主》，在我眼里这是他最好的一部电影。其次我则比较偏爱《龙猫》，简单自然却让我格外感动。不怎么喜欢，甚至有些反感的则是《起风了》。即便抛除掉政治因素，其中的论调也让我无法苟同。人生在世总要有多方面的考虑，只是单纯坚持自己喜欢的事是任性、不成熟的表现。如果追求理想的途中冷落、牺牲了此外的一切，这没有什么值得歌颂的。宫崎骏的电影观点太强硬，如果观众持有不同的观点，必然出现理念上的冲突，影响到对电影的观赏。这可能就是我欣赏宫崎骏却无法对他感到亲近的原因吧。

## 高畑勋

因为宫崎骏名声太盛，吉卜力其他导演都活在他的阴影下。海外常常会搞混吉卜力电影的导演，把所有影片都算成是宫崎骏拍的。其中最冤就是高畑勋，按资历来算他还是宫崎骏的前辈。

与激进的宫崎骏相比，高畑勋要平和的多，事实上甚至有些过于四平八稳了。宫崎骏的电影有着鲜明的特色，而相较之下高畑勋则有些缺少棱角。高畑勋在吉卜力的五部电影，《萤火虫之墓》和《岁月的童话》是现实题材，《平成狸合战》是热闹的幻想片，《隔壁的山田君》是改自四格漫画的搞笑片，《辉夜姬物语》则是传统的民间传说。光看这五部电影，很难总结高畑勋到底是怎样的风格。高畑勋的每一部电影都很好，同时好得不张扬，把导演自己藏起来了。在我心中高畑勋像是位勤勤恳恳、德高望重的老手艺人，只是把自己份内的事情做好。

他这五部电影中，我最喜欢的是《岁月的童话》。我是个喜欢怀旧的人，非常能理解主人公的心情。那些童年时代的点点滴滴，对他人来说都是无足挂齿的小事，对自己却有不寻常的意义。只有同过去和解，自己才能真的成长。比起鸿篇巨制，有时温情细腻的小作品更能打动人。正因如此，高畑勋的动画永远在我心中占有一席之地。

## 其他吉卜力导演

吉卜力工作室成立的目的是为宫崎骏和高畑勋提供平台，这样的工作室必然难以持续发展。吉卜力也推出过数部年轻导演的作品，这些作品在我看来都被吉卜力的传统局限住了，亦步亦趋地模仿过往经典的风格。这里面也存在宫崎骏插手过多的问题，年轻人不能放手去做。最终的结果，好些的是不功不过，比如近藤喜文执导的《侧耳倾听》；差的则是不伦不类，比如宫崎吾朗执导的《地海战记》。后者简直可以说是吉卜力历史上的污点。

比较起来，我最喜欢的一部非宫崎骏、高畑勋的吉卜力作品是望月智充执导的《听到涛声》。这种描写年轻人间微妙情愫的故事，宫崎骏、高畑勋那样的老人家是绝对拍不出来的。艺术不可能单靠模仿，鼓励年轻一辈自由发挥才能让工作室健康发展。不过现在已经太迟了。

## 大友克洋

在日本漫画和动画这两个领域中，大友克洋都是划时代的人物。随意在网上找一找大友克洋七十年代漫画的截图，再跟同时期的漫画（诸如《凡尔赛玫瑰》《明日之丈》）比较一下，任谁都能轻易看出两者间的不同。大友克洋的写实画风是突破性的，为日本漫画走出一条新路。至于大友克洋在动画上的成就，自然就是大名鼎鼎的《阿基拉》了，这是第一部打入国际市场的日本动画电影。

作为一位业界顶端的动画名导，大友克洋的作品少得令人惊讶。他参与制作、担任剧本和设定的动画还是能列出一长串的，但是他自己执导的动画长片则只有《阿基拉》和《蒸汽男孩》。考虑到《蒸汽男孩》在票房和口碑上的惨败，可以说大友克洋的地位就是靠《阿基拉》这一部电影支撑起来的。

《阿基拉》确实有这样的份量。即使是三十年后的今天，《阿基拉》依然是一部充满视觉冲击力的杰作。日本人执着于日本毁灭的题材，无论小说、影视、游戏何种体裁，日本都被外星人、自然灾害、战争毁灭了无数次。这大概是危机意识的体现吧。《阿基拉》正是这类题材中的佼佼者。《阿基拉》的情节很简单，几乎像是一个寓言故事：人类获得超出控制的巨大力量，最终导致自我毁灭。这部电影情节简单，美术却极为奢华。整部电影中一半时间都是在追逐、爆炸，大友克洋在毁灭美学上的能力与追求得到了完美体现。最令我难忘的场面就是巨大建筑逐渐粉碎，碎片随着爆炸四处横飞。要在真人电影中达到同样效果，至少要等到二十年后的好莱坞灾难片。此外还有众多引领时代的视觉设计，比如末世的东京，金田的摩托等等。《阿基拉》配乐同样精彩，恢弘神秘，成功渲染出末世感。为其配乐的艺能山城组在名气上比久石让、川井宪次、平泽进等常为动画电影配乐的音乐家逊色很多，但在艺术水平上不遑多让。

在我看来，大友克洋的才能主要是在美术上的，这是他在《阿基拉》后难以为继的主因。大友克洋拍短片还好说，长片就容易陷入叙事混乱。《阿基拉》的情节就有很多不明不白的地方，连阿基拉能力的由来都缺乏解释。至于《蒸汽男孩》更是从头到尾都不知所云。这也是我之前赞扬宫崎骏叙事能力的原因。除去宫崎骏等少数几位，大多数日本动画导演都有叙事能力弱的毛病。究其原因，一般来讲电影导演的创作动机是要拍出一个故事；而动画导演多是美术出身，追求的是漂亮的画面。动画制作耗时耗力，在一方面投入多了，在另一方面就难免有亏欠，这是很遗憾的事。

## 押井守

押井守的电影都很晦涩，不少人说这是因为他的思想深奥。这里不妨审视下押井守有哪些思想：

首先是政治立场。押井守的电影总带有强烈的无政府主义色彩，他在电影里不遗余力地抨击权威。在他的电影中，高层权威总是官僚、腐败、低能，主人公总是向体制发出挑战。

其次是对人存在意义的反思。在他的电影中，高科技并没有给人带来幸福，反而将人异化。押井守电影中的主人公常陷入自我怀疑，不确定自己的记忆、行为甚至自我本身是不是真实的。通过探讨虚拟与现实之间的关系，进一步引发对于自我存在意义的思考。

以上两点在他的作品中反复重现，可以说是他思想的核心。但这并不是什么深刻的想法，放在今天更可以说是赛博朋克的陈词滥调了，至少没有高明到要为其牺牲叙事。

在我看来，晦涩是个严重的贬义词。把自己想要表达的事情梳理好，清清楚楚地展现出来，这是叙事艺术的基本功。如果容易让观众感到困惑，那一定是影片出了什么问题。押井守的电影晦涩，主要是叙事上的缺陷。

押井守号称原作粉碎机。无论原作是什么风格，到他手里全变成了押井守的风格。所谓的押井守风格，大体上像是冷硬派侦探故事，开场时会甩出一个起到线索作用的悬念，主人公为了发现真相而展开行动；主人公往往不苟言笑，可是一旦开口就像个哲学家满嘴深奥的对白；故事进展冗长缓慢，直到结尾突然真相大白，然后发生一场激烈的动作戏，最后电影戛然而止。

观众是跟随主人公的视角来观看故事的。然而押井守的主人公都是高冷神秘、符号化的人物，缺少正常人的情绪起伏，让观众难以代入。虽然押井守的电影采用了悬疑故事框架，但是并不遵循悬疑设计的起承转合手法，开头的悬念引出的好奇心有限，结尾揭露真相也不会让人感到恍然大悟。押井守电影中不乏美丽的画面，但这些画面多是抒情性的而非叙事性的，关键情节往往是靠对白讲出来的，使得电影节奏冗长。诸多问题叠加起来，电影自然晦涩难懂。

如果押井守愿意向大众妥协，他还是能拍出具有可看性的片子来的，《攻壳机动队》就是个精彩的例子。但是他太执着于自我表达了，总是要搞自己那一套。艺术家是必须要有自我表达的，否则创作千篇一律，也就不能称之为艺术了；同时艺术家也要懂得节制，因为艺术创作不是自娱自乐，要把信息传递给观赏者。在我看来，押井守天生是个边缘小众的艺术家，却因为日本动画的影响力误入了主流视野。

## 川尻善昭

宫崎骏、大友克洋、押井守这样的导演充满雄心壮志，拍出来的电影自有一股大作的架势。川尻善昭的电影则不端架子，一眼看上去就是B级Cult片。除去一些过于血腥黄暴的内容，我非常欣赏川尻善昭的电影。他的强项就是动作场面，对镜头的把握不逊于香港、日本的动作片名导。

就拿他的代表作《兽兵卫忍风帖》来讲，全片不过一个半小时，却安排了八个能力各异的反派人物，逐一登场和主人公对打，整部电影可以说是从头打到尾。其中的刀剑战斗场面极其出色，快速凌厉，毫不拖泥带水。同时其中还有各种诡异邪魅的忍术，花样百出充满想象力。另一部杰作《吸血鬼猎人D》不但在动作戏上具有超高水准，哥特唯美的画面也是一绝，每帧截图都是一副精彩的画作。

川尻善昭的电影或许没有什么深刻的内容，但如果观众想要单纯地享受动画的乐趣，这些电影绝对是不容错过的娱乐享受，可以与《精武英雄》《新龙门客栈》《杀死比尔》《罪恶都市》等作品相媲美。

## 今敏

我喜欢看动画电影，但不得不承认动画电影论质论量都要比真人电影差上不少。艺术形式之间原本不分高低，但是由于人才数量、投入资源的差异，最终的成品却难免有品质上的差距。前面提到的诸多导演，包括大名鼎鼎的大友克洋、押井守，虽然在电影的某一方面独树一帜，但是整体而言存在不少问题。大友克洋有大师级的美术造诣和旺盛的想象力，但是叙事水平不及格。押井守有严肃的创作动机，对镜头有独特理解，但是容易陷入自娱自乐的故作深沉。如果一一检视情节安排、叙事结构、人物塑造，恐怕没有几部日本动画电影能完全过关。大友克洋、押井守拍摄的真人电影都糟糕到近乎惨不忍睹，这当然有隔行如隔山的缘故，但是也能看出一旦脱离了动画圈的小众光环，这两人在导演基本功上确实有所欠缺。

接下来要讲到的今敏则是一位真正的电影天才，即便在短暂的导演生涯中只拍出了四部动画长片，其耀眼的才华依然显露无疑。若非英年早逝，我相信他的地位将可以与宫崎骏并列。

今敏执导的第一部电影《未麻的部屋》就已经显现出技法老到，这部心理悬疑片无论在悬疑的层层递进还是现实与想象的虚实结合上都做得极好，对细节的打磨令人叹服；随后的《千年女优》堪称剪辑教科书，手法高超令人眼花缭乱，电影高潮的蒙太奇简直神乎其技；《东京教父》的剧本非常漂亮，有着无数的前后呼应和喜剧转折，把一个简单的故事拍的花样百出，同时充满幽默感和人情味；最后一部《红辣椒》是今敏技法上的集大成，但是故事的新意不足，略显遗憾。

今敏的作品没有日本动画中常见的粗糙感，每一部都精雕细琢。他的电影完成度高，我每次观看都会发现新的细节。对于这一点，专业从影人员一定感受更深，《黑天鹅》《盗梦空间》等电影都有对今敏的借鉴和致敬。能够成为他人学习的范本，我想这是对艺术家创作能力最好的赞扬。

## 新生代导演

在经历了多年的蓬勃之后，日本动画电影正面临青黄不接的局面。毕竟电视动画才是日本动画的主流，有能力、有资源专门拍摄动画电影的导演屈指可数。日本整体经济环境的萎靡也让动画电影显得越发奢侈，没人愿意投资。每年影院上映的动画都是新一集《精灵宝可梦》《名侦探柯南》《海贼王》，原创动画电影不见了踪影。近些年能独挑大梁的新生代导演主要有细田守和新海诚。

这两位导演的商业成绩都很亮眼，新海诚的《你的名字》更是创下了票房纪录。但是依我看来，这两位与前辈们存在不小的差距。他们欠缺的不是技术与经验，而是艺术家的个性与自觉。前面提到的动画导演们，尽管能力上可能存在一些问题，但是都有独特的艺术气质，有自己的艺术追求。而对于新一代导演，我能欣赏他们的能力，却看不出他们到底要表达什么内容。

细田守的电影从画风到故事再到主题思想都给我一种绵软的感觉。他的电影缺乏张力，全靠清新细腻的风格撑场，内容不过是些爱情、亲情的老套，看不到思想深度。新海诚比细田守小了几岁，电影内容更为狭窄，反复讲述的都是年轻人的爱情故事。新海诚电影里唯美的画面与空洞的内容形成鲜明对比，仿佛是加长版的音乐录影带。

平心而论这两位都算得上是优秀的商业导演，但是曾经独树一帜、令人惊艳的日本动画电影变成了如今平庸的样子，实在令人遗憾。其实这不单是日本动画电影的问题，现在的文艺工作者都是在富裕安逸的环境下成长起来的，缺少独特的人生经验。没有内容，空有表达欲望，创作出来的东西必然陷入平庸。

以上就是我对日本动画电影的一些想法。短短一篇文章无法面面俱到，像富野由悠季、庵野秀明、渡边信一郎、汤浅政明这些以拍摄电视动画为主的导演就不展开谈了。日本动画电影给我的印象与香港电影有相似之处，都是风格与众不同、充满新意，在八九十年代取得辉煌成就，随后又逐渐低落。现如今日本动画业界存在很多问题，从业待遇低导致人才流失产能下降，少子化导致观众人群缩小，等等。作为一个普通爱好者，我能做的也就是多买几张影票和影碟，且看且珍惜。

# 谈美剧

好莱坞电影已经占领全球好久了，而美剧在世界范围广泛流行恐怕只是最近十来年的事，起码在中国是这样的。没有人会不偏好自己熟悉的文化，尤其是影视这种通俗文化，喜欢国产是很自然的事。美国电影那么成功，主要还是靠技术的领先，硬生生把各国本地电影打垮了。那些电子特效横飞、投资动辄过亿的巨型商业片，只有美国能拍的出来。但是长久以来，美国电视剧并没有这样突出的优势。电视剧成本低，工期短，与精益求精的电影走的是不同的路线。受文化限制，同时又没有技术上的特殊优势，外国电视剧难以在本土成为主流。在我上高中之前，我对外国电视剧了解甚少，顶多知道一些日韩爱情剧，美剧就更别提了。一方面是电视台不引进，另一方面也是我个人对此没什么兴趣。同样是拍些家长里短、爱恨纠葛，干嘛要看外国人拍的呢。

2006年的时候，一部美剧改变了我的想法，那就是《越狱》。当时《越狱》第一季刚播完，所以时间记得非常清楚。这部美剧的剧情对很多人来说已经耳熟能详了，主角是兄弟两人，哥哥遭人陷害锒铛入狱，弟弟以身涉险故意被抓进同一所监狱，然后双双越狱。打从一开始，《越狱》就设下非常大的悬念。哥哥被判死刑，每一集都是向死亡倒数，让观众纠结兄弟二人到底能不能及时越狱。监狱里乌烟瘴气，聚集了各色妖魔鬼怪，弟弟要在各势力夹缝中寻求生路。各自心怀鬼胎的囚犯想要一同越狱，中间更是有无数的戏剧冲突，每集都高潮迭起。哥哥遭陷害的原因是典型的阴谋论，跨国大公司暗地里操控政局云云。这些情节现在来看很俗套，对当时的我来说还是很新鲜的。总之是一部题材好、有爆点的优秀电视剧。

第一集刚开始的时候，我就看到弟弟故意抢银行被抓的情节，当时真的很惊讶，没想到电视剧居然能设计出这种的电影般的情节、拍出电影般的质感。所以我对美剧的第一印象就是像电影。其实说穿了，除了长度和放映方式，电影和电视剧并没有本质的区别。我对电视剧的刻板印象，甚至一直觉得凭借一个镜头就能判断出是电影还是电视剧，主要是因为电视剧投资低、制作质量差。如果电视剧也能获得高投资，绝对能拉近与电影的差距。

除此以外，《越狱》还为我普及了美剧的制作与播映方式。美剧通常每周播放一集，边拍边播。根据收视率的高低变化，制作方会随即调整剧情走向。而国产剧通常是用几个月拍完全剧，然后卖给电视台，一口气从头播到尾。要是单纯从作品质量考虑，还是全拍完再上映更有利于整体上的把控。美剧边拍边播是为了控制风险，一旦收视不好就修正剧情或者干脆停拍，从而及时止损。这种商业至上的制作方式，加强了电视剧之间的竞争性，淘汰掉了质量低的作品，能生存下来的都是佼佼者。和一切商业连载相同，这种手法也导致作品难以善始善终。如果电视剧不受欢迎，故事没讲完就被腰斩；如果受欢迎，那就生拉硬扯不肯结尾。这样一来，无论如何都难以保证作品的完整性。就拿《越狱》来说，第一季结尾越狱成功，已经算是个完整的故事了。第二季在监狱外被通缉，众囚犯逃亡，在剧情上还算是合情合理，监狱内外的对比也让角色形象更丰富立体，但整体水平已经开始下滑了。如果这时见好就收，在第二季结尾兄弟二人逃到外国，整部戏就这样收尾，说是经典也不为过。可是第三季又到了一个新的监狱，又展开一轮越狱，简直如同儿戏。再往后剧情已经千疮百孔，无以为继了，我也就没再看下去。

《越狱》在中国是现象级的作品，让很多人从此喜欢上了美剧。如果仅仅从客观素质上来评价，受后面几季的拖累，《越狱》只算差强人意，能取得这样的成功是赶上了恰当的时机。那时宽带开始普及，中国网民数量极速飞升，开始有了自己的网络文化，利用网络去了解广阔的海外世界。免费、自发地为国外影视动漫添加汉语字幕的字幕组就是在那时起步的。当时热播的美剧就藉此在国内获得了大量观众，看美剧成了年轻人的一项新鲜时髦的爱好。而且美剧并不单单只是一种娱乐，也是了解美国文化的便捷途径，更为英语学习提供了大量新鲜有趣、切合实际的语言材料。我能在高中紧张的学习生活中挤出时间来看美剧，就是因为有学习英语这个光明正大的理由，也确实从中获益匪浅。

我看的第二部美剧是《超能英雄》，这部剧当时给我的惊艳感毫不逊于《越狱》。我对美国的超级英雄影视动漫向来没什么兴趣。这类作品中情节逻辑上的欠缺也就算了，更与我审美相违背的是其中强烈的个人英雄主义。《超能英雄》能吸引我，是因为着重描绘了普通人觉醒超能力的过程，以及超能力对他们个人生活造成的影响，使得情节非常具有真实感。剧中的超能力设定可以说十分朴素，无非是意念力、心灵感应、时空穿梭这些俗套，一旦有了真实感就产生奇特的化学反应，一下子变得有趣了。在叙事方面也相当不俗，多条线索平行发展，最后把看似不相干的人物交织在一起，爆发出激烈的戏剧冲突。可惜的是，这部剧第二季恰好赶上了2007年美国编剧协会大罢工，直接砍掉了一半集数，质量急转直下，从此一蹶不振。

接下来要谈的这部美剧是我看过的所有剧集里集数最多、同是也是重看次数最多的一部，那就是著名的《老友记》。我从高中看到大学，之后时不时地重看，去年还在Netflix上又看了一遍。情景喜剧是有固定套路的，《老友记》并没有脱离窠臼，它的优点就是在既有框架下把每一方面做到最好。《老友记》的笑点很密集，可以说集集有梗，除了后期有些疲软，十年里基本都保持了高水准。六位主角特色鲜明，性格各异，都非常讨喜。男角色中我偏好爱吐槽的钱德勒，女角色中我偏好有洁癖、控制欲强莫妮卡，这两人的恋爱故事也是我最喜欢的一段主线剧情。罗斯和瑞秋偏向于肥皂剧的男女主，两人的分分合合搞到最后很有些让人审美疲劳。菲比是超现实的角色，是用来给剧情添加异想天开的要素的。乔伊开始时是憨直，后来愈演愈烈，变的简直有些弱智了，令我不太喜欢。这么多年看下来，真的觉得其中的角色都是身边熟人了。靠着长期的重复强化来加深与观众间的联系，这正是电视剧的一个长处。

之后陆陆续续看了《丑女贝蒂》《绝望的主妇》等等，肥皂剧的性质比较强，充斥着复杂多变的爱恨情仇，洒起狗血来毫不吝啬，刻意制造一种卡通式的喜剧效果。虽然当初津津有味地一集接着一集看，现在却回想不起太多内容了。《实习医生格蕾》也是当时极热门的剧集，我比较喜欢第一季，实习医生高强度高压力的生活让苦读高中的我感同身受。后来情感戏越来越重，几乎变成了风流医生俏护士，就让我看不下去了。

考上大学之后，我的闲余时间多了，才真正开始大量观看美剧。

先聊一下《迷失》，这部剧与《越狱》《超能英雄》差不多同期，是我高中时代追剧的延续。《迷失》这部美剧比《越狱》投资更高，情节更复杂，更有电影味。情节如此复杂、规模如此庞大的幻想悬疑剧集，称得上是前无古人了。尽管我对《迷失》非常不以为然，还是要肯定其历史地位。夸完了就要开始批评了。我想着重谈一下《迷失》的缺点，因为我认为这是美剧一味追求商业效果、用虚假噱头吸引观众的典型例子。

一切分期连载式的作品，无论小说、影视、动漫，为了吸引读者／观众，创作者常用低劣的手法制造悬念，为了寻求一时的刺激效果而破坏作品的整体性。一集美剧不管多拖沓多无聊，结尾处一定要留条尾巴来吸引人去看下一集，每一季的结尾更是要设一个大悬念。要创作一个好故事是很困难的，完满地处理悬念更是需要丰富的想象力和出色的头脑。假如不给出解释，只是设置悬念，作品就成了没有技术含量的胡编乱造。比方说，一本侦探小说，写到一起玄乎其玄的杀人案件，完全是超乎想象的不可能犯罪，让人百思不得其解；可是结尾处给不出合理解答，或是用一些漏洞百出的理由塘塞过去，读者一定大呼上当。

《迷失》就是不断地设置悬念，从不给出正面解释，或者干脆用新悬念来回应旧悬念。在一开始的时候，《迷失》看上去像是一部冒险题材的作品。飞机失事坠落在荒岛上，幸存乘客努力在岛上生存，因为物资短缺、理念不同而出现各种冲突，这是典型的野外生存冒险故事。之后岛上开始出现各种奇异现象，明明是热带却出现北极熊；一股黑烟能幻化成人形；住在地下的人每隔一段时间就要在电脑上输入一组数字，否则就会有大灾难；岛上居然还有一群原住人，背后似乎有邪恶的目的和惊天的阴谋，等等。在这一阶段，《迷失》看上去像是一部科幻剧，甚至干脆出现了时空穿梭的情节。可这些奇奇怪怪的事情一直没有解释清楚，所有人都是云里雾里。在之后突然出现了一黑一白两个神话人物，原来一切都是在他们影响下善与恶的斗争，一下子变成奇幻剧了。最后结尾时连奇幻故事都没说圆，把重点放在感情戏上了，搞出一个情绪浓烈、「感人」的大结局，之前的所有悬念都不了了之。看完这部剧，我识别编剧鬼扯的能力有明显提高。一个坏故事的明线特征就是：不推进主线故事，靠引入新角色来发展情节。《迷失》的特色之一就是不断地回溯角色的背景故事。明明主场景在荒岛上，却把每个角色过去的经历都拍了一遍，主题不外乎是亲子关系、婚姻爱情、家庭冲突，可以说《迷失》有一半的内容其实是家庭伦理剧。《迷失》是群像剧，登场人物之多是惊人的。开场时人物就很多了，每一个季度又继续添加新人物。只要持续地添加人物，拍摄背景故事，这部剧可以一直拍下去。

无论何种形式的创作，其核心价值就是创造出新的东西。可是创新太难了，如果有固定的成功模式，何乐而不为呢。美国影视商业化到如此成熟的地步，以至于影视作品变成了一种可以批量生产的工业产品。《迷失》没有新主题新内容，只是靠技巧来新瓶装旧酒，把陈词滥调包装的光鲜动人。表面功夫做的再好，没有内涵始终太苍白。乍看惊艳，再看油腻。过于模式化几乎是所有美剧都难以回避的弱点。

吐槽完了《迷失》，接着谈我大学时的追剧经历。如果要用一个关键词来概括，就是有线台。虽然我也有看《傲骨贤妻》《生活大爆炸》《摩登家庭》《欢乐合唱团》这些公共台节目，但我看的最多、评价最高的几乎都是有线台自制的电视剧。美国的有线电视台，比如HBO、Showtime、AMC等等，都是收费观看的，靠优质节目吸引观众订阅。有线台的电视剧往往制作精良，而且限制更少，色情暴力无所顾忌，有更大的创作自由。美剧的观看经验多了，最后都会倾向于有线台。

首先是HBO。我看的第一部HBO出品的电视剧应该是《兄弟连》。不过这部是英美合拍，又是名导执导，并不是很有HBO特色，我是把它当成十个小时的电影来看的。随后看了《罗马》，这部历史剧是以戏说为主，战争场面一带而过，主要情节集中于阴谋和艳情。这样说似乎显得格调不高，但是由于精良的制作和出色的表演，整部戏是非常精彩的。

以上两部都比较短，真正体现HBO风格的是长篇剧集，《欲望都市》《六尺之下》《黑道家族》《火线》《权利的游戏》等等。

《欲望都市》采用女性视角，大胆直接地讨论都市生活中的情感问题，有时立意工整到像命题作文，把婚恋的方方面面都探讨一遍，巧妙地利用不同性格的主角来阐述多样的观点。这部电视剧改变了很多人的生活观念，由此可以理解到影视作品确实会对现实生活造成影响。

《六尺之下》选择了殡仪馆从业人员作为主角，切入点十分独特，主题却是很有现实感的，那就是中产阶级的精神空虚、家庭成员间的疏离隔膜。这种第一世界的烦恼我并没有多少切实感受，虽然拍的很好，人物心理描绘细致入微，我却无法投入，看完了只觉得压抑难受。

我一直持有一种观点，对一部作品的喜爱程度未必与作品本身的质量正相关。我乐于承认，很多艺术水准较低的作品给我带来不少娱乐，而技艺高超的作品却可能由于内容、主题的缘故让我难以欣赏。比方说我对黑帮题材不感冒，连马丁·斯科塞斯这样著名导演拍的黑帮电影都不大看得下去，《黑道家族》这种篇幅的电视剧就更让我吃不消了。虽然不得不承认《黑道家族》的剧本、表演都非常出色，我勉强看了三季就停下来了。

从纯粹艺术的角度，《火线》是几乎算是最令我叹服的一部美剧，可是看完两季之后就弃剧不看了。《火线》的好处在于反戏剧化，籍此强化作品的真实感。前面聊《迷失》的时候提到过，美剧拍的太精致了，太刻意了，故事的每一处高低起伏都是精心安排过的，把故事的吸引力、娱乐性最大化。这样并非不好，甚至可以说是技术成熟的体现，但是把所有故事都按照这个套路加工一遍，必然会导致千篇一律。因为手法上的雷同，把几部不同的美剧剪辑到一起可能都看不出剧本、摄影的差异来。与此形成对比的是，《火线》常常戛然而止，不用戏剧冲突收尾；主题也是复杂的，并不在每集突显一个中心思想。这不是说《火线》拍的粗糙，恰恰相反，《火线》下的功夫很深。一般的看法，下功夫就是从粗糙到精致。然而，从精致再去掉人工修饰、重回朴素自然，这是另一种境界。至于为什么我看不下去，纯粹是因为题材离我太遥远了。我自己的生活已经不容易，看电视是为了放松心情，让我在工作之余去关注巴尔的摩沉重的社会现实，实在太难为人了。

《权利的游戏》是近几年来最热门的美剧之一。在这部剧开播之前我早已经读完当时出版的四部原著小说。已经知道了故事的全部细节，再去看高度浓缩的电视剧版本，这让我很难保持客观中立的态度。在观看过程中，总觉得这里缺了点那里少了点，没有达到我心中期待的高度。其中有些演员表现非常好，最突出的就是小恶魔提利昂，真的把书中角色演活了。有的则偏程式化，演的很扁平，龙女丹妮就让我看的很腻味，连带着几乎讨厌起书中的角色来了。前三季基本上是忠实于原著的，在赶上原著进度之后编剧开始自主发挥，一下子就能感觉出美剧的陈词滥调了。原著具有历史般厚重感，人物命运无法预料这一点更增添了真实感。而脱离了原著的电视剧版则逐渐退化成普通的奇幻剧，战场厮杀、喷火巨龙，各种奇幻特效开始喧宾夺主。还有一个技术上的问题，原著人物众多，采用不断变换角色视角的写作手法。电视剧在长度受限的情况下也这么搞就很奇怪。一集就那么几十分钟，把分布在天南海北的主角们每个人都拍一遍，分摊到一个人身上就几分钟，不足以推进多少剧情。有时看完一集感觉好像什么事都没发生。后期为了尽快完结，剧情猪突猛进，故事逻辑、人物性格连贯性都弃之不顾，最后的结局简直是场灾难，回味极差。尽管我对这部剧的好感有限，但平心而论，改编长篇小说是非常困难的一件事，我觉得HBO已经做得很好了，起码证明了这是一件在商业上可行的事。等将来技术进步，摄制成本降低，很可能把更多经典长篇小说完整地呈现在荧屏上。

与精致、大气的HBO相比，Showtime就显得更通俗，走生猛浓烈的路线，怎么奔放怎么来。我比较喜欢的Showtime剧集有两部，《嗜血法医》和《国土安全》。

《嗜血法医》是部角度新颖的探案剧，主角本身是个心理失常的连环杀手，通过以暴制暴来控制自己持续不断的杀戮冲动。这种从杀手角度出发的故事，比一般的刑侦探案更刺激。一般探案剧中搜索证据、走访证人是最无聊的部分，在这部剧中变成了杀手之间的过招，一下子增添了戏剧性。观众会不自主地代入到主角身上，有时忽略了主角是变态杀手的事实，甚至希望主角的谋杀计划顺利进行。我最喜欢双面生活的描写，主角作为一个极特殊的人，却偏偏要伪装成最普通的人。现实中虽说没有这么夸张，每个人或多或少都有私下和公开场合的两面性，这种情节设计恰好搔到痒处。但是主角的罪行终将真相大白，怎样处理结局是件困难的事。很遗憾地，这部剧最终采用了很生硬的情节设计，最后一季是最差的一季。尽管如此，前几季的成就足以让这部剧在我心中占有特别的位置了。

《国土安全》是反恐题材，与老派的《反恐24小时》相比，提供了一种新的思路。主角不再是智勇双全的好莱坞式英雄，而是神经质、心理疾病缠身的女间谍；故事不再有鲜明的善恶对立，而是多方的利益冲突、尔虞我诈。《国土安全》还原了秘密行动中的灰色部分，从香车美女、火爆刺激的007变成灰暗压抑、充满内心挣扎的约翰·勒卡雷式故事。这部剧的缺点是水准起伏不定，第一季时故事最完整，点子最好；初始的故事告一段落后逐渐低潮，搞不清故事要何去何从；第四季主角去国外从事一线工作，故事节奏一下子加快，变的紧张刺激；随后两季又水准下跌，屡屡出现不合理的情节，甚至搞出美人计这种间谍剧的大俗套。最后两季质量有所提高，可是结尾比较平庸。

HBO和Showtime都是老牌有线台，AMC则是以黑马之姿，突然走上前台，连续推出《广告狂人》《绝命毒师》《行尸走肉》等热门美剧。

《广告狂人》的主题与《六尺之下》相类似，也是反映了富裕阶层精神空虚、人生无常，换言之是我不太感冒的内容。这部剧里的人物光鲜亮丽，成功富有，内心却干涸枯燥，整部剧没有一个角色令我喜欢。这部剧最吸引人的地方大概就是精心打造、层层美化的复古氛围，人物的一举一动、每句台词都有股特殊的气质。这股复古风走红时尚界，使得旧款西装、手表、眼镜都随之大卖。美国是一个历史很短的国家，美国人对待这部剧，可能就像是我们看古装剧的感觉吧。

《绝命毒师》是我心中最好的美剧，没有之一。前面提到美剧的常见缺点，最主要的是俗套和烂尾。而《绝命毒师》成功克服了这两点，一直保持住故事的张力，结构完整，收尾恰到好处。这是一个真正的好故事，不但第一次看时会被悬念吸引，即使知道全部剧情之后，重新回顾整部戏，依然觉得有趣。开场时主人公的形象就非常真实、接地气，就是一个普通中年人的样子。他是普通高中的化学老师，收入低，为了补贴家用还要到洗车店打工。他的大儿子有残疾，妻子怀上第二个孩子。这时他发现自己得了癌症，而且已经到了晚期，人生绝望莫过于此。于是他决定铤而走险去制毒，好在死之前给妻子孩子留下一笔钱。剧中详尽地展现了主人公由善至恶的转变过程，一步步突破心理界限，堕落到更深的邪恶。主人公第一次杀人时经历了复杂的内心挣扎，到后面心狠手辣，杀人已经没有了半点犹豫。这其中还充满黑色幽默，各种偶然事件显示出世界的无常。比如主人公放任配角的女友吸毒反胃噎死，她的父亲恰好是航空管理员，他因为女儿去世工作失常导致飞机坠落，而飞机的残片跌落到主人公家里，这段情节相当荒诞讽刺。主人公不仅要躲避法律制裁、面对家庭冲突，更可怕的敌人是与其存在竞争关系的各路毒枭。其中表面上文质彬彬、内心极为狠毒的炸鸡店老板给我留下了非常深刻的印象。主人公永远处在危机边缘，剧情一波未平一波又起，总是出人意料。就在最高潮的时候，故事干净利落地收尾了。除了部分集数有节奏过缓的毛病，整部剧几乎无懈可击。

《行尸走肉》是一部在开播之前就引起我关注的剧集。一方面我是僵尸题材的爱好者，不知在电子游戏里屠杀了多少僵尸；另一方面由于《绝命毒师》的高素质，我对AMC原创剧有很高的期待。这部剧并没有让我失望，第一季一开始就下血本打造出漫山遍野的僵尸海，感觉像是加长版的僵尸电影。第二季节奏突然变缓，在农场里拖戏拖了好久，让我几乎弃剧了。第三季引出总督这个大反派，把重点转移到人与人之间的冲突上，展现后启示录时代的众生相，一下子又好看起来。第四季解决总督之后，《行尸走肉》开始陷入情节上的循环：主角群遇到新团体——发生冲突——干掉坏人，吸收好人。如果把动作场面拍的紧张刺激些，这种套路化倒也未尝不可，更糟糕的是拖沓的情节、重复的内心描写，搞的越来越像末世家庭伦理剧，剧情一直在原地打转。《行尸走肉》缺乏有力的主线，不断重复套路，收视率逐年下跌，主要演员逐个离开剧组，最后惨淡收场。

出国之后，生活变得忙碌起来。加上之前看的太多，我对美剧的兴趣逐渐变淡。从客观的角度来讲，说现在是美剧的黄金时代也不为过。Netflix崛起，展开新的一波原创剧热潮。凯文·史派西、马修·麦康纳这样的好莱坞顶级巨星居然也开始演起电视剧来。可是真正能激起我兴趣的剧集却越来越少。

《真探》第一季是近几年罕有的给我惊艳之感的美剧。表面上看是司空见惯的凶杀刑侦题材，实质上却别具一格，带有克苏鲁神话的风味。不断交叉闪回的跳跃式叙事和两位主演令人赞叹的表演造成一种奇特的氛围，虽然没有直接呈现恐怖的画面，却给观众梦魇般的压力。看整部剧的过程像是在黑暗阴森、泥泞潮湿的隧道中前行，最终走到了洒满月光的宁静田野。第二季是与第一季无关的新故事，风格相似，主创人员也没有变更，却因为几个主角的蹩脚演出变得十分别扭、不堪卒视，每场戏都透着尴尬。这种风格极强的作品，一旦某个环节失误就容易破功，悲剧变闹剧，文艺变做作。

《纸牌屋》是一部阵容强大，非常博人眼球的电视剧。由于紧贴政治时事，影射现实，经常引起热议。可是打从一开始我就不太喜欢这部剧，因为这部剧用力过猛，不知节制，品味不够上乘。集集有爆点，集集有悬念，结果就是剧情失控，支离破碎，到最后主人公从老谋深算的政治家变成贪婪短视的无赖流氓。受凯文·史派西性丑闻的影响，男主角缺席最后一季，结尾简直不知所云。

另一部近来爆红的新剧让我怀疑自己是不是老了，那就是《怪奇物语》。《怪奇物语》整部剧没有任何新颖原创的部分，整个就是俗套大合集，说是八十年代科幻片的翻拍版都不为过。可是这样一部剧居然取得了惊人的成功，说明当下的年轻观众对老桥段不了解，或许根本没看过旧作，自然也就不会觉得俗套。潮流发展循环，我似乎已经不再属于年轻观众群了。

比起这些新剧，给我印象更深反而是早些年一些偏冷门的老剧，像是《废柴联盟》和《路易》。《废柴联盟》是带有后设风格的喜剧，充满各种典故，戏仿影视套路，可以说观剧经验越丰富越能从中得到乐趣。里面一些别出心裁的设计，比如整集变成动画，更是给人天马行空之感。《废柴联盟》的主创后来去拍动画《瑞克与莫蒂》，得益于动画在形式上的无所限制，更加放飞想象力，成就了一部当代动画经典。《路易》可以说是路易CK脱口秀的真人版，把脱口秀中的段子用电视剧的形式演绎出来，充分展现路易CK的独特幽默感。有时像是喜剧，有时又似乎是写实生活剧，偶尔又温情一把，形式和内容上都很特别。顺便一提，路易CK后来拍的《百年酒馆》水准更高，甚至让我开始觉得路易CK堪称艺术家了。不过《百年酒馆》离喜剧更远，不是太合我的口味。

以上就是我观看美剧的经历。十来年里看了上百部、数千集，算是对美剧有相当的了解了。从开始时的惊艳到后来的习以为常，现在能更理性地分析美剧的长短处。美剧在制作上的优势是毋庸置疑的，《权利的游戏》《行尸走肉》这样的大制作只有美国能拍的出来。看惯了制作精良的美剧，再去看华语剧、日韩剧，总能发觉寒酸、不到位的地方。另一方面，美剧过于商业化，创作受到掣肘，这方面的毛病前面已经多次提到过，就不再赘述了。

刨除掉制作优劣的比较，美剧仍有顾及不到的地方，无法取代各国的本土剧。在文化上，美国沉淀不足，拍不出或者至少很难拍出像样的文艺、历史题材电视剧，很难想象美国会拍出《红楼梦》和《傲慢与偏见》；在风格上，美剧太粗狂豪放、大开大合了，《东京爱情故事》《深夜食堂》也是美国人拍不出来的。

我近几年最喜欢的电视剧，像是《小海女》和《请回答1988》，都并非美剧。这其中大概有吃腻大鱼大肉后反而喜欢清淡小菜的缘故，也包含我对文化的一种反思。不管怎么说，多样性是人类文化丰富有趣的根源。美国因为经济、国力上的优势，向国外输出文化，导致当地文化萎靡，这并不是件好事。我希望各国的本土剧，尤其是我国华语剧，能够提升制作水平并保持自己独特的风格，拍出在各方面都不逊色于美剧的好片子来。影视创作蓬勃、多样，才是观众的幸运。

# 谈日剧

和电影相比，电视剧受成本的限制，制作水准要逊色不少。可是电视剧自有一番独特的魅力。电视剧的一个显而易见的优势是篇幅长，能叙述一个更漫长、更复杂的故事。与篇幅相伴而来的是风格上的差异。电影要在短时间内吸引住观众，内容必然更加精炼，戏剧冲突更强烈。电视剧则可以减慢节奏，内容更加生活化。就拿我在网飞上的观看记录来说，我花在电视剧上的时间远超出电影。有时忙碌了一天，晚上实在没有精力去消化一部内容激烈的电影了，这时就更倾向于看电视剧。一集集看下来，那些熟悉的角色们好似一群老友，给我一种舒心感。

我平时看剧以美剧居多，其次则是日剧。美剧制作精良，近年来愈发接近于电影。相比之下日剧的卖相稀松平常，演员的表演也常令人一言难尽，但在「舒心感」上却做的更好。具体缘由我也说不出个所以然来，也许是我对东亚文化的偏爱吧。美剧拍的再好，始终拍不出亚洲人细腻的小心思。

我看过的日剧不算太多，就我有限的经验来讲，我觉得日剧有下面几个特点：

一是大量的刑侦题材电视剧。刑侦题材在世界各地都是热门，在日本尤甚。日本推理小说发达，名家辈出，自然为电视剧提供了源源不断的素材。

二是漫画改编电视剧。日本漫画的影响力就不用多说了，我自己就是一个漫画迷。漫画常有夸张的喜剧表达方式，这一点在改编为电视剧之后也保留了下来，导致日剧在情节、表演上也常有夸张的倾向。

三是细腻的情感描绘。要论感受力的细致入微，恐怕没有比得过日本人的。这份内心的敏感用影像的方式表现出来，别有一番精致的趣味。

四是对小众文化、边缘人群的关注。日本享受了多年的富裕，有追求精神需求的余裕，可以凭着兴趣去尝试稀奇古怪的事物。这使得日本文化千奇百怪，对于影视作品自然也就更开放包容。

下面说说自己比较喜欢的几部日剧。

首先想要谈的是2003版的《白色巨塔》。这是我看过的所有日剧里水平最高的一部，无论从哪方面来评判都是部杰出的作品。原著小说我未曾拜读，听闻是日本当代文学名作，曾数次改编为影视剧，想必是水准极好的。有了小说的坚实基础，这部电视剧结构严谨，叙事有条不紊。《白色巨塔》揭露的医疗体制的扭曲腐败，放在当下依然具有现实意义。仔细深究一下，其中对于权力与欲望的探讨超出了对现实的简单批判，拥有动人心魄的力量。本剧主要角色都是由资深优秀演员饰演，日本演艺界的中流砥柱齐聚一堂。演技尤为令我赞叹的是饰演外科教授的石坂浩二，演出了一位「暴君」的复杂多样，而不是脸谱式的恶人；另外一位是饰演主角情人的黑木瞳，把这个角色演绎得坚强独立又富有女性的温柔。总而言之，《白色巨塔》是一部不可错过的好剧。

接下来想谈的是《古畑任三郎》。这是一部警探推理剧，在形式上模仿著名的《神探可伦坡》，每集都是固定的结构。开场时主角古畑任三郎会有一段独白，看似漫无边际，实际上和接下来的案件有关。然后是犯人作案的情形，每集饰演犯人的客串演员都是日本娱乐界的名人，不仅有著名演员，还有歌手、运动员等等。因为观众一开始就知道犯人的身份，故事的看点在于古畑任三郎是怎么发现犯人的破绽，双方的博弈造成紧张戏剧感。在结尾揭穿真相之前古畑任三郎还会对观众发出挑战，让观众更加投入。为了避免泄漏谜底，这里就不讨论具体的案件情节了，每集的水准都很不错就是了。《神探可伦坡》我也看过一些，与不修边幅的可伦坡相比，我更欣赏古畑任三郎的风度。尽管这个角色性格颇有些古怪，还喜欢捉弄愚笨的下属，但是本质上是一个充满智慧、有正义感、胸怀宽阔的人。饰演古畑任三郎的田村正和非常具有东方儒雅风度，是一位我很钦佩的演员。

另一部我非常喜欢的警探剧是《跳跃大搜查线》。一般的警探剧都追求刺激，总是拍些凶杀、枪战什么的。这部剧则一反其道，把警察拍成了普通的上班族。主角青岛俊作本来是个销售员，怀着正义理想半路出家当了刑警。没想到真到了警局，每天处理的都是些鸡毛蒜皮的小事，领导都是些胆小怕事、互相推诿责任的官僚。《跳跃大搜查线》采用警局基层小人物的视角，描写警局工作的琐碎生态，揭露腐败、不合理之处，当真别具一格。里面的角色个个都是活宝，整部剧的风格轻松幽默又引人深思。相比之下，后续的几部剧场版拍起了大场面，充满激烈的动作戏，反而削弱了自身的强项。当然了，电影为了吸引观众，这样做也是无可奈何。比较电视剧版与剧场版的异同，不难看出播放形式对影视内容造成的影响，更能理解电视剧与电影的差别。

爱情剧一直是电视剧的主流，日剧自不例外。比起《东京爱情故事》《第101次求婚》和《悠长假期》这些名作，我更喜欢另外两部风格独树一帜的电视剧。

其中一部是《不能结婚的男人》。身为爱情喜剧的男主角却声称不能结婚，这一设定从一开始就透漏出一股搞笑劲。男主年届四十依然单身，不但不为爱情忧虑，反而积极享受单身生活。他一个人吃烤肉，一个人听音乐，一个人看烟花，生活有滋有味。面对工作与生活中的三位单身女性，他毫不怜香惜玉，常说些不合时宜的难听话。整部剧就是讲他生活中的琐事，因为孤僻性格与周围人的各种小冲突。这样一个简单的故事拍出来却饶有趣味，足可见创作人员的功力。

另外一部是《最高的离婚》，可以说是从离婚开始的爱情故事，讲述两对情侣的情感冲突。本剧几乎完全靠对白支撑，台词写的又多又好。借剧中人之口，编剧表达了自己对婚姻的想法，有很多看似平淡浅显，却有深刻道理的“金句”。男一女一的吵架戏，由琐碎的事情开始最后吵到不可开交，非常具有真实感。男女主角的两封信都很感人，也是靠真实打动人。给我留下最深印象的还是这部剧靠着独白的手段，让四个主角分别讲述自己的想法，从多个角度讲述同一个故事。故事一开始，从男一的角度出发，观众会觉得女一邋遢懒惰，粗枝大叶，没有女人味，似乎离婚都是女一的错。之后从女一的角度阐述，发现男一性格别扭，不会关心人，对女一的爱没有回应，似乎男一才是离婚的罪魁祸首。这样反复调换视角，最后让观众发现，其实本剧中并没有单纯的反面人物，每个人都有自己的难处。另外这部戏算是轻喜剧，有很多搞笑的细节，比如说常出现两只卖萌的猫，还有主角们激烈争论时背景里路人们的行为举止，仔细看会发现原来路人其实也有一套剧情。这些幽默的细节减轻了这部戏的沉重感。这种离婚题材放在大陆来拍肯定就变成了苦情戏，就落入下乘了。

再谈谈两部不知该怎么归类的电视剧。先是《深夜食堂》。这部姑且可以算是美食题材，故事发生在一间只在深夜开门的奇特饭店。每集的标题都是这一集出现的食物，结尾时还会讲解烹饪方法。而实际上食物只是故事的引子，借此展示人间百态。剧中出现的人物大都属于边缘人群，其中有黑社会老大、同性恋酒吧老板、脱衣舞娘、色情片演员等等，还有更多身份不明的奇怪人物。大城市在繁华外表下有冷漠无情的一面，底层普通人的生活中免不了各式各样的苦恼。深夜里一份用心制作美食，给这些孤独挣扎的人带来温暖。这部电视剧既感人又刺激食欲，观看时一定要备上点吃的。

还有一部是《海女》。海女是日本、韩国等地一种古老的职业，是潜水捕捞海产的女性。女主角随母亲从东京回到故乡，这个天真善良、有些笨笨的女孩受到淳朴民风的感染，决定成为一名海女。后来情节一转，女主想要成为偶像，又重返东京。单看故事简介，《海女》不过是个追求梦想的俗套故事。其中的魅力都在于细节，一定要亲自观看才能体会。《海女》的编剧宫藤官九郎是出了名的鬼才，把简单的故事玩出了复杂的花样。《海女》对白好笑，人物有趣，怀旧梗层出不穷、顺手拈来。最让我喜欢的还是里面对故乡小村的描绘。远离大城市的喧嚣，村民都过着朴实而愉快的生活，当地的居民都像一家人一样，互相关怀照应，是温暖、舒适、富有人情味的地方。《海女》里那个美好的故乡，真是令人向往。

以上就是我对日剧的一些看法和体验。中日比邻而居，我从小对日本文化耳濡目染，看日剧时自有一种亲切感。正因为文化上的相似，有时我也会感慨，某某电视剧要是中国拍出来的该多好。由于种种原因，中国电视剧除了历史剧以外成就有限，历史剧又难以输出海外。如果将来有一天，一个普通日本人会写出一篇《谈中国电视剧》来，中国流行文化就真的崛起了。当抱怨自己的文化不被接受时，我也提醒自己要对外国文化保持开放的态度。电视剧虽有夸大之处，仍不妨成为了解外国文化的窗口，我想我会保持看日剧这个小爱好。

# 谈港剧

说起电视剧，我平时看得最多的是美剧，偶尔也看些日剧、韩剧和英剧。至于香港电视剧，我已经很久没有看过了。可是回想年少时，能让我废寝忘食地守在电视机前的都是港剧啊。

成长于八九十年代的人，多多少少都有些香港情结。八九十年代时，大陆刚开始改革开放，有了开眼看世界的机会。流行文化总是从发达地区流向欠发达地区，那时正是大陆与香港经济差距最大的时候，香港的流行文化自然像洪水一般涌入。金庸小说、双周一成、四大天王、TVB电视剧都成了一代人的回忆。

艺术水准姑且不论，单就娱乐性来讲，当年的香港电视剧完胜国产大陆剧。当国产影视还找不准定位的时候，香港早就建立起了完善的娱乐产业，影视制作、人才培养、宣传造势一应俱全。港剧分类清晰，精准针对目标观众，尤其擅长豪门剧、武侠剧、刑侦剧和职业剧。与同期的国产剧相比较，港剧中有时髦的人物、精彩的情节、激烈的动作、缠绵的爱情，难怪我当年会沉迷其中。

小时最爱看的是武侠剧。TVB把金庸每部小说都反复拍了数次，九十年代的版本构成了我对金庸的最初记忆。我看的第一部金庸剧是古天乐、李若彤版的《神雕侠侣》，当时我还在上小学。每晚等到新闻联播结束后看上一集《神雕侠侣》成了我珍贵的童年回忆。直到现在《神雕侠侣》也是我最喜欢的金庸作品。接下来看的是黄日华版的《天龙八部》。记得当时是春节期间，地方电视台三集连播，每天尽情看个痛快。吕颂贤版《笑傲江湖》和陈小春版《鹿鼎记》都是零零散散偶尔看几集，印象就比较浅了。吴启华版的《倚天屠龙记》播出较晚，当时我已经快上初中了，几乎没有完整看完过，我比较偏好马景涛版。除此之外，改编自古龙小说的《香帅传奇》《圆月弯刀》也给我留下一些印象。不过由于古龙小说风格独特，影视改编都对原著进行了大刀阔斧的修改，质量无法与金庸剧相比。

客观来说，TVB当年的武侠剧在制作上有很多不足。当时的电视剧普遍经费紧缺，布景寒酸。金庸小说波澜壮阔，场景横阔大江南北，而TVB硬生生把每一部都拍成了室内剧。TVB编剧词汇之贫乏也常被人取笑，《神雕侠侣》里古天乐张嘴闭嘴都是「混帐」「岂有此理」，令人哭笑不得。TVB武侠剧的背景音乐也很单调，多部电视剧反复重用那几首日本曲子。尽管如此，TVB拍出来的武侠剧却更有武侠味。后来大陆翻拍的数版金庸剧在投资上不知翻了多少倍，结果却不如人意。

依我看来，香港武侠剧的长处有两个方面：

一是武侠文化积淀。金庸、梁羽生都是香港作家，古龙的经典作品也都是在香港杂志连载。以邵氏电影为首的武侠片也是香港流行文化中的主流。此外还有黄玉郎、马荣成的武侠漫画。香港几代人对武侠文化耳濡目染，对武侠作品的理解和感情是远超出大陆影视人的。

二是出色的演员。香港是弹丸之地却人才济济。TVB的一大批演员，不敢说表演艺术如何精湛，但是能站在台前的无不经受过无数摸爬滚打的磨练。TVB演员的表演有套路化的嫌疑，喜怒哀乐都很夸张，但至少都很到位，要什么来什么。每次看TVB的金庸剧，我经常感慨所有角色无论大小无不尽心尽力，一些小配角的表演常令我惊艳。

推而广之，不止武侠剧，港剧的优势基本就在于通俗文化的积累和演员的勤勉。虽然港剧主题立意都很普通，人物故事也常陷入俗套，可是熟能生巧，拍出来的戏都很老成，没有大毛病。就比如师奶爱看的豪门剧，拍来拍去都是争夺家产、爱恨情仇，基本上就是为了满足普通人对富豪生活的幻想。不过拍得熟了，自成一种风格。如今大陆也开始拍什么富豪什么总裁，可是就少了港剧中的气派。可见师奶剧也不是那么容易拍的。

港剧还有一个特色就是人情味足，按照现在流行的说法就是接地气。比方说，同样是刑侦剧，与美剧中高大上的干练精英相比，港剧中的警察总是有一股市井气。无论剧情多么紧张，总少不了警察在吵吵闹闹的街市吃早点宵夜的情节。警察是一种职业，警察脱下警服也是个普通人，这种桥段拉近了角色与观众的距离。

话虽如此，俗套的生命力终究有限。比起常见的主流类型，我更喜欢两部剑走偏锋的电视剧。

一部是《男亲女爱》，这是我看过的最好的情景喜剧之一。情景喜剧成功与否，非常重要的一点就是人物设计。只要人物设计的好，人物间相互碰撞就会产生化学反应，各种笑料自然而然就爆发出来了。《男亲女爱》中大大小小的角色都非常有趣。男主角余乐天由黄子华饰演。黄子华是脱口秀大师，幽默感自成一派，表演夸张却不失分寸，嬉笑怒骂中藏着智慧。余乐天这个角色表面上好吃懒做、油嘴滑舌、贪财好色，实则心地善良，黄子华演起来得心应手。黄子华的表演太强势，对手接不住的话整部戏就会失去平衡。而扮演女主角毛小慧的郑裕玲恰好是一位演喜剧的大高手，锋芒毫不逊色。毛小慧这个角色既有女强人精明干练的一面，也有小女人斤斤计较的一面，人前一套，人后一套，两者的矛盾造成了笑点。配角们的表现也不遑多让，最突出的就是苑琼丹，她饰演的梅日仙内容非常丰富，花样层出不穷，有时简直盖过了主角。此外的奸人坚、詹士安、Apple等角色虽说难免有些脸谱化，发挥出的喜剧作用也都非常好。整部戏长达一百集，从头到尾几乎没有冷场，做到善始善终，这就更加难得了。

另外一部是《我和僵尸有个约会》。TVB在香港一家独大，几乎成了香港电视的代名词。常年受到冷落的亚视其实也有不少经典作品，《我和僵尸有个约会》就是其中的代表。这部电视剧故事奇特，天马行空，说是邪典作品也不为过。《我和僵尸有个约会》前后三部曲好似大杂烩，其中有身穿超短裙时尚靓丽的驱魔人，有不老不死的僵尸，有灵异鬼怪，有时空穿梭，有感人的爱情，有绚丽的打斗。我刚开始看时就觉得这部电视剧有浓浓的日本动漫味，看着看着发现了明目张胆的借鉴，比如照搬《乔乔奇妙冒险》中赌博的桥段，还有借用《星际牛仔》的插曲。《我和僵尸有个约会》还有一些稀奇古怪的点子，比如开酒吧的白素贞，电脑里的贞子，结局时打破第四道墙，真是难得编剧如此异想天开。三部相比较，第一部内容新颖，令我眼前一亮；第二部故事结构更复杂精彩，还有任达华的精彩演出；第三部拍摄期间主演万绮雯受伤，故事中女主长期缺席，导致剧情松散、逻辑混乱，好在最后还算是圆满收官。

前面提到的这些电视剧，距今至少有十多年了。比起曾经的火爆，港剧已经大幅度衰退。TVB的财政收入年年下滑，亚视更是惨到倒闭。说起港剧衰退的原因，不外乎内忧与外患。

说到内忧，港剧擅长的类型已经衰退了。港剧把一套旧花样翻来覆去拍了几十年，内容风格僵化，观众已经看腻了。娱乐业总是不进则退，不经过一番彻底的改革，港剧的前景只有越来越糟。更沉重的打击是人才流失，众多香港演员纷纷北上。而且香港演员青黄不接，欠缺新人，只能靠老一辈苦撑。

说到外患，现在网络发达，文化交流畅通，观众可以自由选择，想看什么看什么。面对美剧、韩剧、大陆剧的多重夹击，港剧实在无从招架。去年（2018）香港年度收视冠军是大陆剧《延禧攻略》，由此可见外来剧的强势。

这内忧外患，概括起来其实就是一个钱字。如今的香港已经没有了当年的经济优势，娱乐产业自然就衰落了。比如人才流失，TVB压榨演员是出了名的，TVB的演员去了大陆薪资可以翻数倍，长此以往TVB自然留不住人。再比如与外来剧的竞争，美剧制作经费已与电影无异，大陆剧的成本也动辄数亿，相比之下港剧一穷二白，巧妇难为无米之炊。

出于香港情结，我期待将来依然能够看到港味佳作。经济发展是大势所趋，普通人无能为力。作为观众我倒是有个小建议，既然成本有限，不妨考虑短小精悍的迷你剧。近年来的一些热门美剧，如《纸牌屋》《真探》《怪奇物语》，每季都是十集左右的长度。日剧、英剧也都历来比较简短。短剧风险降低，可以尝试更新颖的内容，说不定能为港剧带来一线转机。无论如何，希望香港影视能重新振作，再创辉煌。

# 卷五 思想杂谈 {-}

# 谈乐观的悲观主义

如果要用一个词来说明自己的性格，我会说自己是个乐观的悲观主义者。把乐观一词放在悲观主义者前面看似荒谬，其实乐观的态度和悲观的观点可以并行不悖。

罗素曾说乐观主义和悲观主义都是不科学的，乐观主义者以为宇宙的存在就是为了让我们高兴，悲观主义者则以为是为了让我们不高兴。然而很显然，当地球绕着太阳转时并没有考虑过我们高不高兴，乐观与悲观都是我们自顾自的想法罢了。

如果所有人都能做到不以物喜不以己悲，那么罗素说得没错，乐观和悲观都要不得。可惜人并不是那么客观理性的动物。晴天还是阴天，午餐吃了什么，路上有没有堵车，昨晚睡没睡好……这些小事都能影响人的心情。

对于一个普通人来说，把让我们高兴的事和难过的事分开来数一数，我想大体上服从正态分布，恐怕好事还要多一些。可是坏事的杀伤力要比好事大得多。假设有人每个月都有一周生病，尽管按数量上讲还是健康的日子多，我们也会觉得他是个倒霉的病秧子；平时吃得饱饱的，突然遭遇饥荒饿上一阵，这饥饿绝对让人终生难忘。

或许有人会说这是因为我们对痛苦关注过多，应该把注意力放在积极的事情上。但我认为关注痛苦乃是人之常情。随着人生经验的增加，我越来越发觉生命的脆弱，命运只要轻轻一推就能把最强壮的人击倒。

痛苦是一道预警。如果一个人失去了痛觉，一定常常受伤；如果一个人从不居安思危，面临挫折必然会更加手足无措。

人生在世，生老病死悲欢离合都是逃不过的，人性的贪婪、嫉妒、仇恨、愚蠢也是躲不掉的。如果有人只看得见人生中的美好，要么是因为太幸运，要么是因为太无知。

我称自己为悲观主义者，正是出于这一方面的考量：人生中存在各式各样的不幸，难免有一天会落在自己头上；我倾向于对事情做出最坏的打算，而不是天真地期待一切都顺遂人意。我以为这是最理性的选择。

人生的好坏并非我所能把握，但应对的态度则是我自己选择的。当我看到事情坏的一面，我不会仅仅为此哀叹抱怨，而是想办法去解决。我很少会沉溺于消极的情绪中，我知道那根本于事无补。在更多的情况下，我早已提前做好了准备，再糟糕的情况也有相应的对策。从这个角度讲，我同时也是乐观的。

当我审视自己的人生经历，不难理解为什么我会形成这样的性格。我自幼喜欢读书，比同龄人成熟的早些，在家里也未曾受过长辈的娇惯，十二三岁就开始承受严酷的学业压力。天真无知的童年时代转瞬即逝，我早早地就接触到了现实。我很早就知道了生活中的无奈，学会了牺牲眼下的自由快乐从而换取未来的收获。

性格是一个人的特色，难以用好坏来评价。当我回首过往，我自觉从这乐观的悲观主义中获益匪浅，人生的每一步都走得扎扎实实。与此同时，我也看到自己有时会过于小心谨慎，厌恶风险，做人不够洒脱。有得必有失，有失必有得，这不是我能左右的。

罗曼·罗兰曾说过，真正的英雄主义是在看清了生活的真相之后，依然热爱生活。我不敢自诩看清了所有真相，但我对生活有着深沉理性的爱，所以我甘心做一个乐观的悲观主义者。

# 谈出世与入世

中国自古以来就有出世与入世的说法。世既是俗世，出世是脱离俗世的束缚，入世则是投身于俗世。我国传统文化中的儒释道三教，佛教和道教都有讲出世的道理，儒家则讲入世。所以国人对这些说法是不陌生的，再不济至少听说过「看破红尘」「四大皆空」。

我以为所有人都需要有一点儿出世的想法。我这样说并不是劝人出家做和尚去，而是以出世作为一剂思想的解药。

人生在世，脑子里有各式各样的观念，这些观念影响了我们对世界的看法，驱使着我们的一举一动。有些观念简单的显而易见，像是「饿了要吃饭」「下雨要打伞」；有些观念则要复杂些，甚至非得通过系统学习才能搞明白，像是牛顿运动定律和进化论。

我不打算讨论具体观念的正误。我只想指出，观念一旦在脑中扎了根就很难再清除掉。正因如此，我们应该严格审视脑海中的观念，不能毫无保留地把所有观念都纳入常识。一件事是对的，只因为它是对的，而不是因为社会习见或约定俗成。

在不同程度上，我们都是些井底之蛙，局限于自己所处的时代与社会环境。我国经历过社会制度的剧变，国人应该对封建社会愚昧偏见造成的悲剧并不陌生。当我们为古人叹息时，不妨想想将来的人又会如何看我们。如果我们接受了出世的想法，在思想上脱离俗世的束缚，也就更容易客观地看问题。

身为凡夫俗子，当我们每天为柴米油盐而奔波烦恼时，打开思维枷锁并不是件容易事。每当我在俗世泥沼中难以自拔时，我总会提醒自己两个事实：

第一，人是渺小的。说到底人不过是地球上的渺小生物，而地球又不过是宇宙中的一粒尘埃。正如苏轼在《前赤壁赋》中写道，「寄蜉蝣于天地，渺沧海之一粟」。

第二，人终有一死。我不相信什么天堂地狱、来生转世，人一旦死了就什么都没有了。名也好，利也罢，人死了什么都带不走，到头来一场空。

看清了这两个事实，很多虚妄的迷惑就不攻自破了。人的一生转瞬即逝，如果把人生都用在了争名逐利、虚荣炫耀甚至于自我放纵、互相残害，生命就白白浪费了。

说完了出世，反过来讲，人也需要有入世的态度。

人不是生活在真空中的，人类的生存需要互相依靠，不可能不沾染尘埃。一个人的一举一动都会对他人造成影响，难以独善其身。除非彻底远离人世，只要身在社会中，就要遵循社会的规则。

再者，任何思想都不能走极端，如果一味追求出世，最后很容易陷到虚无主义中去，对现实毫不关注，以为一切都是空虚、任何事都没有意义。而我认为，正是因为人世短暂无常才更要珍惜，如果我所做的事能为自己、为他人带来一点正面的影响，能让世上多一点快乐少一些痛苦，终归是有意义的。

入世是人的本能，我就不细细讨论了。随着年龄与经验的增长，我越来越觉得最难得的是把握思想的平衡。出世与入世，正如理性与感性、自信与谦虚、责任与自由一样，不能单纯地说某一方好某一方坏，而是要在两者之间找到恰当的折衷。当我们不自觉地过于偏向于一方时，就要提醒自己摆正观点。如果能随心所欲却从不逾矩，那就是真正修养到家了。

# 谈宗教信仰

人虽然自诩理性，所作所为却多是天性使然，并不是深思熟虑的结果。就拿宗教信仰这件事来讲，这很大程度上依赖于生长环境，而不是理性思考。一个人来自沙特阿拉伯，几乎可以确定是伊斯兰教徒；一个希腊人，十之八九是基督徒；换成是印度人，则多半会信仰印度教。我是中国汉族人，成为无神论者，也是很自然的事。

中国近两千年来以儒家思想为主流。虽有「儒教」的称呼和儒释道三教的说法，我不认为儒家是一门宗教。儒家思想讲的是道德伦理和治国方针，是一套切实可行、讲求实际的思想方法，对来世、鬼神根本不关心。孔子说「子不语怪力乱神」，又说「未能事人，焉能事鬼」，至多算是不可知论者。再有，宗教都有排他性，未曾听说有身属多教的。中国历朝历代独尊儒术，却不干扰信佛信道，这更证明了儒家不是宗教。儒家思想深入国人骨髓，我天生的思想基调就是入世的。信不信神，于我来讲，从来不是要紧事。

新中国成立之后，我国的主流正统思想变为马克思唯物辩证主义。如果说儒家只是把鬼神之事置之一旁，中国特色的马克思主义则是针锋相对，破除一切封建迷信。在我自小接受的思想教育中，连唯心主义都被坚决认定为错误，更不用提什么有神论了。

前面两点还只是大的思想背景，对我影响更直接的是长达二十年的现代科学教育。一切宗教都或多或少涉及超自然的内容，与我学习到的、工作生活中实践到的完全相抵触。宗教惯有的权威式的、不容置疑式的说法也与科学的怀疑、探索精神相违背。这更坚定了我无神论的理念。

以上种种，并不试图探讨对错，只是检明我思想的来源。中国的生长环境（主流思想和教育）使我成为了无神论者，假使我出生在沙特阿拉伯、希腊、印度，我的想法很可能会截然不同。只因为出生地点这种偶然的事情，就决定了自己一生的信仰，这不是非常荒谬可笑的吗？

信仰是精神生活中的头等大事。一个人的信仰决定了，或至少影响了他对人生的看法：人为何诞生，活着为了什么，人死后会怎样。正因为其重要性，我们要无比谨慎小心，不要误入歧途。人是很容易犯错误的。一生当中，哪怕一次也好，要质疑一下自己惯常的思维，审视自己思想的正误。这就像去医院体检一样，是明智而有益的。有人说不要质疑信仰，这种说法错的不能再错了。烈火出真金，如果信仰是正确的，自能抵得住所有质疑；如果发现是错误的，可以及时修正，亡羊补牢。

所以，我尝试抛开成见，仔细思考一下信仰问题。我要质疑自己的无神论观点，首先就是寻找证据，看看有没有谁能证明神真的存在。历史上有各种各样的手段用来证明神的存在，总结起来可以分为三类：奇迹，理性和情感。

第一类证明，最有煽动性也是最不靠谱的，就是神明显灵的奇迹。什么医治百病，死者复活，前世记忆等等。无论是历史悠久的主流宗教，还是花样百出的新兴宗教，都喜欢搞这一套，然后宣称这证明了神存在。这类奇迹，要么只有文字记载，要么是口耳相传，没有哪个有确实的证据，多数压根就是骗人的把戏。即便通过多方见证、科学的检测，证明了这奇迹真的存在，也不能证明神的存在，因为奇迹与神之间没有确实的因果关系。如果一个人会飞，他自称是神的儿子所以会飞，然后你就相信了神的存在；那么同样的，一个女人会哺乳，她自称是神为她创造了乳房，一样可以说服你相信神的存在。这类证明既违背科学，又缺乏逻辑，完全不可信。

第二类证明，是采用形而上学的方法，试图通过理性思考得出神存在的结论。想出这类证明的基本都是有基督教信仰的神学家和哲学家，下面我也就直接用「上帝」这个词来替代神。

先说本体论的证明。这个证明早在中世纪就有人提出，近现代又有各种大同小异的版本，大概的意思是：

上帝是最伟大的。

实际存在的比不存在的更伟大。

所以上帝存在。

这个证明最大的问题就是何为「伟大」。基督教的哲学家总是采取一种主观的态度来假想上帝，说上帝是至善至美的。「善」和「美」都是主观的想法，有恶才有善，有丑才有美，何来至善至美。如果我们相信，善和美是客观绝对的，上帝就是最完美的那一个，那么，恶与丑是从何而来呢？疾病，屠杀，灾荒，这些都是既不善也不美，全知全能至善至美的上帝为什么要创造这些丑恶？有些人搬出魔鬼的说法，说这些都是魔鬼的错，那上帝为什么允许魔鬼的存在呢？

就算把上面的矛盾搁置一旁，姑且认为人类智慧有限，理解不了上帝的伟大，这证明中的第二个前提也是有问题的。为什么实际存在的比不存在的更伟大？举例来说，现实存在的等边三角形难免会有边长的误差，我完全可以在脑海中想象一个完美的、最伟大的等边三角形，比任何一个实际存在的等边三角形都更精确符合数学上的定义。我看不出来一个实际存在的等边三角形，怎么就比脑海中的三角形更伟大了。如果你说，脑海中的等边三角形，也是客观存在的，那上帝也不过是词典中的一行定义罢了。

再有一个证明是最初因。有人认为，一切事物都有起因，一直追溯上去，最初的起因就是上帝。这个证明有很多毛病。首先，经过哲学与科学的研究，因果关系很可能只是人类的一种思维方式，没理由说世间万物都有起因。再有，假设万物确实都有起因，那上帝的起因是什么呢？上帝创造万物，那又是谁创造的上帝呢？最后，就算这个证明成立，也只能说明有一个最初因存在，这个最初因不等同与上帝，反倒更接近于宇宙诞生时的大爆炸。基督教中对上帝是有丰富的描述的，我看不出怎么通过宇宙大爆炸推导出圣经中的上帝。

还有一个类似的证明，说运动的事物总是被推动的，一定有一个最初的第一推动力。这个说法在物理学上就是错误的，运动的原因不是推动，而且物质间自然存在相互作用，比如万有引力。最后，同上一条证明相同，即使证明成立也只能说明物理现象，不能证明上帝存在。

再提一个证明，是自然法则。这个说法试图把科学与宗教相融合，说上帝设定各种自然法则，像是牛顿力学定律，以此规定世界运转。这个版本的上帝好像是个钟表匠，细心设计各个部件，让宇宙井然有序地运行。这个说法的错误在于，有规律，不等于一定有一个规律制造者。就比如说一些数学和逻辑上的定律，像是矛盾律（一个事物不能在同一方面即是又不是），这些都是靠思维就能得出来的，不需要一位上帝去特意安排。我们总结出的自然法则，是对自然现象的归纳总结，并不能反过来约束自然现象，牛顿力学定律在微观和高速情况下不成立就是一个很好的例子。最后，仍旧与之前的说法类似，这证明即便成立，也最多只能说明宇宙运行存在一定规律罢了。

在我看来，以上的种种说法最大的错误还是认识论上的。我相信知识是从实践中得来，单凭逻辑规律就认定一样事物必然存在是不可能的。这种纯粹靠着演绎推理的手段来证明神存在，等于是说一个人即使目不能视耳不能听，只要心念一动就明白了应该信仰上帝。我无法相信这世上有哪个人是预先想出了这些奇奇怪怪的证明，随后才说服自己成了基督徒。

第三类证明，是从自身的体验出发，以情动人。要么是经历过生死巨变，要么是被自然的庄严所震撼，又或者只是幻觉和精神错乱，有人从中得到了宗教体验，然后就信了神。这种说法是率真的，我相信很多人就是为此而信教。同时也很容易看出来，这种说法是不理智的。没错，人类是十分渺小，遇到天灾人祸更发觉自身的脆弱无助。但是，相信有一个神在天上保佑我们只是一种逃避，不能解决任何问题。

情感体验因人而异，有人出自内心感受信了基督教，有人出自内心感受信了佛教，有人出自内心感受信了无神论，到底谁对谁错呢？这种说法把宗教信仰变成了与穿什么衣服、晚餐吃什么相类似的问题，仅凭个人喜好，无对无错；我觉得这是对人生的不负责。说到底，这种以情动人的手段只能感动缺乏理性、意志薄弱的人。

分析了上面的种种说法之后，可以得出结论，并没有一个靠谱的证据能说服我相信神的存在。反过来讲，能不能证明神不存在呢？很遗憾地，答案也是否定的。我相信人类的智慧是有限的，宇宙时空无边无际，万事皆有可能，我无法妄自尊大地宣称不存在比人类高等的存在。尽管如此，我不是不可知论者，而是坚定地认为神不存在。理由很简单：不能证明存在，也不能证明不存在的事物，根本没有探讨的价值，更别提干涉我的人生了。

有一个著名的例子，叫做「罗素的茶壶」。哲学家罗素说，如果声称地球和火星之间存在一个茶壶，只是因为太小了，用我们最强大的望远镜也观测不到，我们是不能证明这茶壶不存在的；如果仅仅是因为我们不能否定，就把这茶壶像宗教一样灌输到人们的观念中，是完全荒谬的。还有一些出于讽刺目的虚构出来的宗教，比如信仰「隐形粉红独角兽」，声称存在一个不可见的、同时又是粉红色的超自然生物。因为不可见，所以不能证明不存在；基于宗教信念，认为它是粉红色的；这并不比基督教的三位一体更荒唐。还有一个叫做「飞天面条神教」，声称世间万物是一个面条形状的怪物创造的，还编造了一套模仿圣经的福音书和诫条。这些好笑的例子都说明了一个道理：逻辑上可能的东西无穷无尽，没理由因此就把这些事物认真对待。

从辨伪存真的角度，对宗教的探讨可以到此结束了。从实用主义的角度，还应该研究一下宗教的实际作用，信仰宗教会带来什么样的影响。

在人类历史上，宗教向来是科学的主要敌人。基督教会迫害异端，封禁科学书籍，将布鲁诺处以火刑，软禁伽利略，这都是极其愚昧、丑恶的罪行。有人声称宗教与科学并无对立关系；如果只是单纯地相信有一个超自然的存在，如自然神论、泛神论那样，的确和科学并无冲突。科学的应用范围是有限的，研究的是具体的现象、可验证的事实，超出范围时科学保持缄默。但是宗教从来不是这样单纯的，各种宗教总是从神的概念出发，引申出一整套关于世界的说法。当宗教坚持认为太阳绕着地球转，地球只有五千年历史时，宗教与科学之间就存在鲜明的对立关系了。面对这样的对立，我真诚、坚定地选择科学。在多年的学习、工作中，我深刻理解到科学的局限性，科学理论很多时候是阶段性的归纳总结而不是绝对的真理。尽管如此，科学仍是人类手中最强大、最实用的工具。没有科学，人类只能像野兽一样生存，在残酷的自然中饥寒交迫，文明将会是遥不可及的空中楼阁。既然宗教与科学相抵触，我找不到任何理由抛弃有用的科学，转而去相信不可靠的宗教。有人喜欢举例说很多著名科学家也有宗教信仰，试图以此反驳宗教与科学之间存在冲突，这是不加深思熟虑的看法。宗教的影响力是如此广泛，在相当长的一段历史时期，可以说文明社会中的人都信仰某一宗教，饱受宗教迫害的布鲁诺、伽利略都是天主教徒。如我一开始所说，这是环境造成的，并不是理性的结果。随着宗教在世俗生活中地位降低，在现代社会中，只有很小比例的科学家笃信宗教。最根本的，一个科学家的宗教信仰，即便他伟大如牛顿，也只代表了他个人的选择，不等同于科学的选择。

宗教与道德之间存在着错综复杂的关系。道德是不是从宗教中来？陀思妥耶夫斯基的小说中常有这样的人物，因为人世间丑陋的罪恶而对信仰产生疑惑，不明白为什么神会允许这样的罪恶存在；同时又在想，如果没有了神，人是不是就可以为所欲为。作为中国人，这个问题对我来讲是很容易回答的：道德与宗教是独立的，没有宗教一样可以构建出道德体系，甚至可以说是更高等的道德体系。依赖于宗教的道德，像是无知的、需要管教的小孩，遵循道德是出于外在的推力，做好事是为了神的奖赏，不做坏事是因为畏惧神的惩罚。而中国的传统道德观，遵循道德是出于内在的动力，做好事因为它是好的，不做坏事因为它是坏的，不需要用天堂来诱惑人、用地狱来吓唬人。再有，道德和法律、政治体制一样，都需要不断改善提高来应对不断变化的现实生活，好的道德绝不是一成不变的。宗教的教旨，究其本质，是不容置疑、不容改变的，否则就意味着神的话不真实、不唯一，可以随意篡改诠释。为了适应社会，宗教会违背自己原来的说法，进行宗教改革。然而即使是最有活力的宗教，比如基督教，宗教改革的步伐也远远赶不上现实生活的变化速度。如果我选择信仰宗教，也就意味着我要用几百年、上千年前的道德观来生活，这于我是完全不能接受的。最后，我相信道德是律己的，而不是律他的。宗教因为坚守自己固化的道德观，所以热衷于对他人进行道德审判。在历史上，宗教狂热或是其它僵化的、独断专行的道德观总是带来残忍的后果，这完全是站在了善的对立面。

宗教能给人带来心灵慰藉。很多人在经受巨大的痛苦时，用宗教来抚慰自己。各种宗教都有来世的说法，劝说信徒痛苦是暂时的，死后会永远幸福。佛教很专注于这一点，演化出一套逻辑通顺、很有说服力的理论。佛教从因果报应讲起，说今世的痛苦是弥补前世的罪孽，换来来世的幸福。这套奖惩的说法是违背我的道德观的，我相信道德是主观的、非绝对的，没有、也不需要一个神来主持公道。就算我麻痹自己，相信真的有什么超自然的存在，在冥冥之中评判一切，那评判结果也来的太迟了。我今生的苦难是切实的，如何让我接受下辈子才能挽回。就像遇到一个饥饿的人，你告诉他饿死以后就能在天堂里天天吃大餐了，这对他有什么助益呢？佛教又说生老病死都是苦，劝人舍弃欲望，想必成佛最快的方法变成植物人。这种回避痛苦的想法，同时也把快乐铲除了。我宁愿生活中有苦辣酸甜的滋味，不愿生活变成虚空。我愿积极面对痛苦，努力消除痛苦的根源，让人类不再受病痛折磨，让社会更加公正平等，而不是默默忍受，期待来世的天堂地狱、因果报应。那些不能避免的痛苦，像是与至亲至爱的生死相别，我也努力坦然接受事实，继续将来的人生，而不是用精神鸦片来镇压内心的感受。

前面的讨论是从我个人的角度出发，最后再说说宗教对社会的影响。我的想法是，宗教对人类社会的一点点好处，已经被宗教的坏处抵消了，我希望宗教与世俗生活分离，最好在将来彻底消失掉。宗教的一点点好处是在道德与心灵慰藉上的。尽管我自己不需要宗教的指导，明白宗教式道德的副作用，但是我知道，对于很多人，宗教是学习道德和填补心灵空缺的主要途径。对于一个野蛮部落，说服他们相信神的惩罚要比劝说他们一心向善容易多了。但我相信这是暂时的，随着人类文明的进步，我们越来越不需要宗教的教鞭。宗教的坏处则明显多了，反科学，僵化的道德观，前面已经讨论过了；更可怕的是制造思想冲突。宗教是排他的，唯我独尊的，世界上有多少宗教，就意味着有多少冲突。历史上的宗教战争，当代的恐怖袭击，背后都有宗教在作祟。衡量一下利弊，道理不言自明。

除了坚定自己的信念，我能做的事是有限的。我知道劝说他人退教和拉拢他人信教一样令人讨厌，成效甚少。对于成年人，我尊重每一位的信仰。但至少留给孩子一片清白，不要人为地扎下宗教的根基，让他们长大后再自由选择。我天真而又热诚地希望，就像其它一切阻碍人类前进的陋习一样，宗教也终将被人类摈弃。

# 谈道德

群居动物为了集体的利益，需要约束个体的行为。动物是依靠本能来控制个体，比如激素、分泌物等生物信号；人类则是以宗教、道德、法律来制定行为的标准。

当今世界中多数人口是信奉宗教的，每种宗教都有一套行为规范。有的只提供了大致的原则，有的则对生活起居的细枝末节都有具体规定。我是无神论者，在我看来宗教并不是生活的可靠依据，这里就不多论述了。

道德同样提供了一套行为的准则，比宗教更贴近现实，更加尊重情理。道德是自然产生的，能在社会中广泛推行的道德必然符合了社会的需求。举例来讲，个体间不相互损害是集体稳定存在的前提。无论何种文明，最基本的道德戒条往往是相似的，比如不能伤人、不能盗窃、遵守信用等等。这些基本的原则可以用一句话来概括，便是「己所不欲勿施于人」。这些道德戒条起到了维护社会稳定的作用，是有客观基础的。

但是并非所有道德准则都是合理的。比如今时今日仍广泛存在的对女性的压迫，在很多地区女性得不到教育，在家相夫教子才是她们的义务，追求个人自由反而被认为是不道德的。稍微涉猎人类学和民俗学后，我认为现存的道德至少在初始阶段是符合某一时期的社会现实的，比如男女间的不平等是由于男性在体力劳动上的生理优势。相对于社会的进步，道德的发展太缓慢了。甚至于，一旦某种道德观念成为了文化传统的一部分，无论对错从此就再也难以根除。这样一来，必然会产生脱离现实的道德观。

即便是处于一个理想化的社会中，道德能够持续地自我修正，道德作为行为准则仍有严重的缺点。这缺点就是并不存在一种普世的道德观。在一种道德体系下被判断为正确的行为，换到另外一种道德体系可能就被判定为错误，比如迄今仍有广泛争议的同性恋婚姻和堕胎。读一读伦理学的著作就会发现，哪怕是在实事求是、严谨求证的学者之间，很多重要的道德问题也无法达成共识。我越来越坚信，道德是一种主观意见，没有绝对正确一说。道德是达成某种社会效果的实践，要追求什么样的效果、要通过怎样的途径来实现，这些问题不仅复杂而且包含了众多的利益冲突。许多著名道德悖论，比如电车难题（要不要牺牲一个人来拯救五个人），根本没有正确答案，只有基于不同立场、原则的个人观点。

拿一把不准的尺子去测量，结果必然也不准。事实上，在现代文明社会中，道德已经让位给法律了，法律才是评判行为正误的公认标准。法律是纯粹人为制定的，力求公平公正、精准具体。与定义模糊的道德不同，法律的制定和执行都是有规矩可循的。法律可以视为道德伦理的升华，选出其中最合理、最具普遍性的部分，予以明文规定。法律的自我修正也远比道德活跃，每部成功的法律都是千锤百炼下产生的。

既然法律相较于道德有如此多的优点，随着人类社会的发展，有朝一日能不能排除掉道德的影响，完全以法律来规范行为呢？在遥远的将来，或许存在着这样的可能性，眼下则是不太可能的。人类的行为太复杂了，想制定、推行一套无所不包的法律太困难了，有必要存在「己所不欲勿施于人」这样模糊却应用广泛的道德指导。而且法律的成本太高了，不可能用法律监管生活中的所有细节。试想一下，总不能借块橡皮都要签订法律合同吧。在法律顾及不到的地方，是道德在发挥作用，道德对于法律起到重要的补充作用。

经过以上的讨论，可以总结我的道德观了。我不相信存在绝对的道德；道德不是一成不变的，需要自我演化；道德天生是多元的；评判正误的首要标准是法律而非道德。如果承认了以上几点，不难得出另外一个结论：道德是不是用来律人的，而是用来律己的。

道德不应该是攻击性的，不应该以道德来约束他人。既然道德是相对的、多元的，我就不能用自己的道德观去抨击他人的道德观。用道德去约束他人根本无法实施，如果一个人根本不在意道德，我用道德来谴责他又有何用呢？如果一个人的行为恶劣，造成不良影响，应该让法律去制裁他。如果法律没有正确的应对方式，那就去完善法律。又或许，这「恶劣」与「不良」只是我的主观想法，根本不需要法律制裁。法律不能也没必要面面俱到，是要给人留下自主空间的。

道德是靠律己来发挥作用的。受道德观念的影响，我评断哪些事情是应该做的，哪些事情是不能做的，以此调控自己的行为。

也许有人会质疑，只靠自我监督，怎么能确保可靠性呢？不进行自我监督的人是不是就能为所欲为了呢？以道德来律己确实是一种不那么可靠的约束方式，千古无完人，道德修养再高的人也难免一时失足。完全没有道德观念的人也不可能为所欲为，因为还有法律的管束。

这种不靠谱的律己手段，却能够持续地发挥作用，乐观地说，或许是因为人有同理心，有向善的倾向。更实际地说，这应该是出于博弈上的考量。个人是集体的一份子，每个人都主动地去维护集体的利益，才能更好地去追求个人的利益。至于要做到何种程度，就看个人的理解了。通过自己的思考，而不是教条地、盲目地遵循道德，才能真正让道德发挥正面的作用。

# 谈哲学问题

哲学向来是与普罗大众有距离的。即便是受过当今高等教育的人士，若非个人喜好或是工作学习中有相关需求，对哲学的了解恐怕也相当有限。我出于对知识的好奇，从小就对哲学有些兴趣，曾读过一些经典著作，大学时选修过哲学课程，算是有过一番肤浅的接触。可实事求是地讲，我从哲学中所得的困惑远多于解答，不敢说有多深的理解。

哲学没有一个标准的定义，一个人如何解释哲学的内涵取决于他的哲学观点。翻翻哲学史，物理、逻辑、政治、伦理都包含在内。古时的哲人贤者几乎都是十项全能，研究内容无所不包。我以为纯粹意义上的哲学就是研究（除去数学之外）仅凭理性思考就能得出结论的问题。但凡是研究外物、需要用事实验证的，都另外自成一套学科。在这篇文章里我打算整理下自己的想法，讨论几个在我看来最为重要的哲学问题。

## 第一个问题：物质的存在

物质存在吗？乍看起来这个问题的答案显而易见，物质当然存在。当我们观察一个物体，看到它的颜色、形状，触摸到它的表面，我们由此确定它是存在的，因为它看得见摸得着。可是仔细想想，这看得见摸得着指的都是我们的主观感受。我们有了一些感官体验，而不是直接体会到一个物体的存在。事实上，我们默认了这些感官体验是由某个物体的存在而造成的：因为桌子存在，所以我们看见了桌子。这个默认的想法并没有足够的证据支持。就像在科幻电影和思想实验中那样，我们完全可以想象自身的所有感官体验都是虚假的模拟信号，自己其实生活在虚构的世界里。除了自我以外，其它所有一切可能都不真的存在。

围绕这个问题产生了很多种不同的说法，有极端地肯定或否定物质存在的，有认为物质存在但精神才是本原、精神先于物质的，当然也有认为物质先于精神的。我认为物质存在，而且反对精神物质的二元论，在我看来精神也是一种物质。

我无法找到确信无疑的理由去证明物质的存在，同时也没有办法证明物质不存在。物质的存在对于我来说是一种信仰。一个简单的理由是，外部世界不以我的个人意志为转移，我不能操纵太阳升降、不能让河水倒流。无论以何种形式，必然有我之外的存在。物质的存在为这一切提供了简单合理的解释，比充满假设非物质世界更加可信，所以我愿意接受物质的存在。

关于物质与精神的先后，我能想象不包含精神的物质，却无法想象没有物质载体的精神（即使是纯粹抽象的概念，总要存在于人的脑海中或是记录于书本中。否则就如同一首没有被写出来的绝世好诗，说它存在有什么意义呢？），所以物质才是本原。至于为什么有人认为精神为先，这就引出下面的另一个问题。

## 第二个问题：共相的存在

想一下「桌子」的概念，再观察一张具体的「桌子」。虽然同样使用了「桌子」一词，含义却有所区别，前者是抽象的概念，后者则是切实存在于时空中的事物。像「桌子」这样代表一类事物的抽象概念，就是共相。「红色」、「三角形」等等也都是共相。既然这些共相不是存在于现实时空中的物质，那就当然是精神的。事物有寿命，抽象的概念却是长存的。即使我们摧毁掉现实中的所有的桌子，也不能毁掉桌子的概念。这样看来，共相是超越具体事物的存在，是精神先于物质的明证。还有更夸张一些的说法，认为共相的存在才是真实永恒的，现实世界不过是共相的投影。

对于以上的观点，持认同和反对态度的哲学家几乎一样多，在漫长的时间里展开了激烈的论辩。我是属于反对的那一派。在我看来，共相不过是一些人造的观念罢了。

比方说桌子，桌子是人发明创造出来的，没有人就没有桌子这个概念。桌子这个共相甚至不先于人类这个物种，当然更别提物质了。所有人造物的共相都可以用这个说法来反驳。

自然产生的、非人造的共相又如何呢？一朵开在田野里的红花当然不是人类意识的产物，但是「红」和「花」这两个概念都是人造的。世上本没有红的概念，也没有花的概念，是人创造出了这些说法。人眼可见的、波长在某一范围内的光被称为红色，植物的某个器官被称作花。人类自己自然认为这些说法天经地义，其实不过是些虚构的想法。举例来说，英语国家在翻译中国农历羊年时遇到了难题，因为英语中有「山羊」和「绵羊」，却没有作为两者统称的「羊」这个词。这样看来，对于中国哲学家，「羊」是个共相；对于不懂中文的英国哲学家，「羊」不是个共相。这实在太滑稽了。

仔细考察人类对天文地理自然万物的种种分类，会发现这些归纳抽象是相当含糊、不精确的。人工智能的一个重要课题就是分类问题，让计算机程序去辨别一张图案是猫还是狗，不同照片中的人脸是不是同一个人。计算机的运算能力远超过人脑，之所以难以处理这些问题，其实是因为这些分类并没有精确的标准，只是人脑的产物，等同于是让计算机去揣摩人的思维方式。

我以为支持共相是绝对存在的哲学家都犯了一个先入为主的错误，把人类的智能看的太高了，以至于认为人类智能的特性就是所有智能的通性，把人类自己的偏见当成天经地义。有位古代哲学家曾引导不懂数学的人通过推理得出三角形内角和为180度，并以此为证，认为真理是绝对的，所有人通过理性思考都能抵达相同的真理。现代数学水平比古时高出太多，我们知道非欧几何中三角形内角和未必是180度。我们认定这个结论不过是因为生活在三维空间，思维受到了局限。对于人工智能的研究已经给我们带来了很多启发，假若有朝一日能遇到外星文明，更加会颠覆我们的思路。我们习惯说东南西北，会不会有某种文明用三个方向甲乙丙来定位呢？我们讲时间上的先后，会不会有某种文明将所有时间一视同仁、不分先后呢？

在我看来，共相是人类归纳总结出来的知识。知识作为一种信息，本质上也是物质的。信息必须以物质为载体进行存储和传播，是对物质状态的描述，更进一步地说信息就是物质的一种属性。所以对我来说，没有作为精神的共相，共相根本不能当成精神先于物质的凭证。

## 第三个问题：知识的来源

我以为，人的知识大体可以分为三类：第一是通过我们的感官直接获得的知识，比如说看到草是绿的天是蓝的；第二类是我们在直观感受的基础上总结出来的知识，比方说太阳昼升夜降、人类终有一死；第三类是抽象的逻辑、数学知识，比如一加一等于二。

关于第一类知识，我们如何确定直观感受是可靠的呢？我们所见所闻到底是包含了外部世界的客观信息还是虚妄的幻象？这个问题已经在物质的存在那一部分讨论过了。我的结论是要相信自己的所见所闻，这是我的基本信仰，否则无法理智地生活。

关于第二类知识，有人提出了强而有力的质疑，认为归纳法不能提供确信无疑的知识。归纳法是用已知的经验去猜测未知的经验。比方说，我见过的所有天鹅都是白色的，于是我得出结论说天鹅都是白色的。而实际上存在黑天鹅，我的结论是错误的。难题在于，我们无法避免黑天鹅存在的可能性。所有通过经验总结出来的知识都可能存在错误。

我认为归纳法的弱点是无法弥补的，但这并不说明依据归纳法得出来的知识就不可信。我过去见过的所有天鹅都是白色的，在没见到黑天鹅之前，要我猜测未知天鹅的颜色，最理性的猜测就是白色。归纳法并不提供绝对的真理，而是给出概率最大的建议。如果新的经验反驳了猜测，我们大可提出新的设想。事实上，科学就是这样发展起来的。

关于第三类知识，这些知识是不是来自于经验？像一加一等于二这个例子，我们可以说是从经验中提炼出来的，比如一个苹果再加上一个苹果等于两个苹果。但是一旦有了数字和加法的概念，二加二等于四和四加四等于八就不再依赖于经验了。在经验之前，我们的脑海中是否已经预先存在着一些逻辑、数学的真理？否则逻辑与数学是如何从经验中产生的？

我以为这个问题是可以依靠科学来解决的。关于人类的理性，哲学家们过份沉溺于凭空设想，却没有真正的观察实验。借助于生理研究和计算机技术，我们对智能会有更深的认识。假设有朝一日我们建立出一个模拟人脑的模型，就可以用实验检测：只输入经验数据而不提供先验知识，是否有无法解决的问题。

近年著名的阿尔法围棋项目就是一个很好的例子。阿尔法围棋是一个围棋软件。在此之前，设计围棋软件的主流思路都是加入人类的围棋知识，设定好不同情形下的处理方法，再把这些先验知识应用到具体的棋局中。这类软件的水平有限，至多相当于较强的业余选手。阿尔法围棋则是纯粹依赖于经验，仅凭棋谱来训练，没有加入任何先验知识，反而取得了突破进展，围棋水平超过了最强的人类选手，并随后在国际象棋和日本将棋中取得了同样的成功。这个项目能否推广到更多的领域还有待验证，目前的结果已经足够鼓舞人心。

即便最终证明了先验知识对于智能必不可少，我也坚持认为经验的作用要远超过理性。理性或许为处理经验提供了前提，但是只有借助于经验我们才能理解外部世界，才能获取新的知识。将一个人类婴儿剥除五感，他绝对无法借助自身的理性（假设这理性存在）成为一个有智慧的人。

综合以上论述，我认为经验是人类最重要的、非常可能是唯一的知识来源。

## 第四个问题：哲学的用处

文章开始处我提到哲学是门曲高和寡的学科。哲学问题的抽象复杂是让人畏而远之的原因之一。但是哲学再难也未必难得过自然科学，不愿迎难而上还是由于缺乏足够的动力。生有涯而知无涯，要人耗费时间在哲学上，总得有个理由。那么，哲学的用处是什么呢？

第一点，哲学问题重要吗？前面我探讨了三个著名的哲学问题，就我个人而言，我觉得这些问题有重要的学术价值，是对人的理性的反思。如果没有人去思考、去追问这些问题，意味着人类缺少对自身智慧的自觉。但对个人而言，即使从未思考过这些问题对生活也不会造成任何影响。哪怕是哲学家，在脱离学术讨论的环境之外，没有谁真的会逐一检验自身的经验与信念、按照自己的哲学观点来生活。不过几乎所有高深的学问都是如此，没理由以此来苛求哲学。

第二点，假设我们已经承认哲学问题的重要性，那么哲学研究能提供多少确定的知识呢？单纯考虑研究课题与目标，占星术的重要性不逊于任何学问；可是占星术得不出任何令人信服的结论，所以不是一门成功的学科。很遗憾地，哲学上确定的结论并不比占星术多。其它的学科都是直接从问题着手，学哲学却一定要学哲学史，哲学就是一大堆观点的集合。无论任何哲学问题，几乎都存在着完全对立的说法，经过千百年的争论也无法互相说服。一个哲学家所持有的观点，很大程度上取决于他的个人特质，而不是什么确信无疑的精确证明。我自己就能清楚地意识到，我所认同的哲学观点与我的个人经历有关，我接受的长达二十年的科学教育让我倾向于唯物主义与经验主义。我认为用自己的智慧来分析自己的智慧是件有局限的事，哲学问题没有答案是因为超出了人的能力范围，想在哲学中寻求真理是徒劳的。

第三点，假设一个人对哲学有莫大的信心，不仅认同哲学问题的重要性而且对自己的观点确信无疑，认定自己掌握了真理；那么，这哲学真理能不能应用到其它领域呢？历史上很多著名哲学家都以哲学为核心，用自己心中的哲学真理去指导天文地理道德伦理人文政治所有学科，建立一套无所不包的思想体系。这种做法的信誉度已经破产了，现在几乎没有哪个学者会认真考虑这样做。哲学观点的正确性已经是严重存疑的，在不稳固的基础上建立高楼大夏必定会是摇摇欲坠。无论是研究世界的组成还是如何建立更好的社会，都需要现实中的观察和实验。认为仅凭思考就能得出宇宙真理是种虚妄的想法。

所以，如果一定要追问哲学的用处，我只能得出消极的结论：哲学没有什么用处。哲学是思维的奢侈品而非必需品。甚至可以说，哲学只是西方文化的特殊产物。（举例说，中国有没有哲学是有争议的话题。中国最有代表性的儒家思想弱于思辨，缺少西方哲学中的抽象理性思考，在我看来比起哲学更像是一套宗教式的生活准则。）

如果允许我感性一点，我还有另外一个答案：哲学是一条朝向真理、却看不到尽头的路，人的智慧只能照亮脚下，也许永远无法抵达终点。但是，求之不得与无所追求是不同的。知其不可而为之，不也是一种浪漫吗？爱智慧，既是哲学最初的名字，也是对哲学最好的总结。

# 谈科学与实用主义

我们生活在科学时代。无论你对科学持有怎样的态度，都无法否认科学的威力。不用去想太深奥复杂的科学知识、太遥远的人造卫星和原子弹，就观察一下你的身边吧：化纤衣物、牙膏、防晒霜、止痛片、隐形眼镜、自来水、塑料袋、电视、计算机、智能手机、无线网络、冰箱、洗衣机、空调、汽车……这些我们习以为常的日常事物，在一百多年前、甚至短短几十年前都并不存在。甚至看似非人造的自然事物，比如说一颗水果，能送到你的手上也要靠农药、化肥、灌溉机器、冷藏、海陆空运等多方面的科学技术。

从鸦片战争开始，中国遭受列强轮番入侵、殖民。这是中华文明几千年来最严酷、最重大的转折点。与蛮族战斗时，即使败了总还保有文明的自尊，而这次连自信心都丢失了，经过漫长的岁月才重新崛起。科技发展决定了国家实力，「落后就要挨打」，经历过百年屈辱，中国人对此有着深刻认识。

科学的是非功过太难评说，在这篇文章里我无意探讨太宏大的命题。我感兴趣的是：科学与其它学问有什么不同，为什么有这样大的威力呢？科学方法是不是比其它学问的研究方法更正确呢？

看一看科学研究的步骤吧。首先是提出问题，这自不用多说；然后是观察现象，提出解释问题的假说；接下来测试假说，根据测试结果来确认、修改或否定假说；如此循环，直到假说通过检验，成为一种科学理论。

科学方法的核心在于观测和检验。对于受过教育的现代人，这方法似乎是不言自明的。而实际上，这是人类思想史上的伟大创举，直到十六世纪才由伽利略引入到自然科学中。在现代科学出现之前，无论东西方，理论先行才是主流。

有一个关于亚里士多德的典故：他认为女人的牙齿比男人少。尽管他结了两次婚，却从没有想过去数一数自己的老婆到底有几颗牙。因为像亚里士多德这样的哲学家认为，真理是从理性思考中得来的，理论大于经验事实，不屑于去观察世界。基于同样的道理，亚里士多德认为重的物体比轻的物体下落更快，却没想过要扔两个不同重量的物体试一试倒底哪个快。

王阳明曾经对着竹子冥思苦想七天七夜，不但没领悟出什么道理，反而着凉生了场病。经过这场失败，他开创了心学，强调「心即是理」，只要思考内心就能发现至高真理了。他没想过，是不是自己「格竹」的方法错了。要研究竹子，可以从很多方向着手：竹子如何生长？如何繁衍？生活在什么样的环境？有多长的寿命？能长多高？有多少种类？什么颜色？有多硬？有多厚？有什么用途？一个种竹子的农民，论「学问」肯定比不上王阳明；可谈起竹子来，他绝对比王阳明懂的多。

如此种种，令我不由得猜测，恐怕人天生就是主观的、自大的，以为自己所信的就是正确的；经历专门的学习和训练，人才能懂得实事求是。依靠形而上学建立起来的古代物理学说充满庄严宏伟的美感，众多行星像守护天使一样围绕地球进行美妙的圆周运动，组成世界的元素均匀对称地分布，宇宙和谐完美永恒不变。欣赏这些诗歌一样的奇妙理论时，仿佛能听见交响乐在耳边轰隆作响。然而宇宙中并没有交响音乐，执着于自身美学观点的学说必然是充满主观错误的。人类作为已知的唯一高等智慧生物，容易傲慢自大，把自己的理性放在至高无上的位置上。历史上两个重要的科学发现应该使我们摆脱这种错觉。其一是日心说，表明地球并不处于宇宙中心。事实上，现如今我们已经知道地球处在银河系的偏僻角落，而银河系又只是无数星系中的普通一员。其二是进化论，表明人类是由低等生物进化而来，并不是神按照自己的样子创造出来的天选之子。人类是浩瀚无垠的宇宙中的一粒小小尘埃，人类的存在转瞬即逝，没有理由妄自尊大。通过实践才能获得真理，实事求是就是科学强大威力的根源。

科学自身同样不能免于考察。所有对科学的诘难中，有两样最切中要害，最值得反思。

第一个是对归纳法的质疑。归纳法是科学研究的根基，科学家通过观察个别现象，进而归纳出普遍的规律。然而，要如何通过「特殊」推导出「一般」呢？举个例子，假设我们观察到的天鹅都是白色的，然后推论所有的天鹅都是白色的；然而存在黑天鹅，证明我们的推论错了。问题在于，我们不可能检验全世界从过去到未来所有天鹅的颜色，我们也就永远无法证明自己的推论百分之一百正确，谁能保证绝对不会存在蓝天鹅、粉天鹅呢？同样的道理，我们要如何证明自然科学中的定律一直有效呢？

我的回答是：不能。归纳法的有效性只能是先验的，无法证明。事实上，哪怕是最成功的科学理论也难免出错，牛顿的力学理论就被相对论和量子力学推翻了。波普尔更进一步指出，能够被证明错误的理论才是科学，科学本身就是在猜想与反驳中逐步发展的。如果科学会出错，为什么还要相信科学呢？因为科学是基于已知信息的最合理的解释。比方说，经过无数人、无数次的观察，太阳每次都是从东方升起；如果要预测太阳明天从哪个方向升起，尽管无法完全排除太阳从西方升起的可能性，还是猜测从东方升起更合理。不同科学理论的可信度也是不同的，要看经过了何种程度的检验。科学不是完美的，但仍然是认识自然最有力的工具。

第二个问题：无法观测的事物存在吗？在现代科学理论中，很多事物都是无法直接观测的，比如夸克和引力。它们是真实存在的实体，抑或仅仅是科学推论呢？换言之，科学理论是不是描述了客观事实呢？要知道，有些曾在科学中被认为真实存在的事物，比如热素和以太，现在已经被否定了。

我认为科学理论的意义在于解释事实和预测现象。至于理论中提出的事物是否真实存在，如果无法检测，那就是一个没有意义的问题。

科学是有力的工具，但有其适用范围，像形而上学、伦理学等领域就无法用科学处理。那么，有没有将科学实践精神应用到更广泛领域的思想呢？我以为实用主义就是这样的一种思想。

我所理解的实用主义就是注重实际效果。理论的价值在于实践，知识是行动的工具。如果一个理论能解释经验事实，能指导我们行动，能取得好的实际效果，那这就是一个好的理论。如果一个理论对我们的认知和行为没有任何影响，那么这个理论就是虚无的空谈。只有能付诸实行的理论才有价值，也只有实践才能判定理论的真伪。实用主义是简单而有效的思维准则，扫除思想上的含混不明，对现实造成切实的影响。

比如说，实用主义可以用来厘清哲学问题。当处理哲学问题时，从结果出发，搞清楚到底要表达什么意思，争论的要点是什么。像「白马非马」这个问题，公孙龙认为白马有白和马这两种特征，而马的概念不包括颜色，黑马是马却不是白马，所以白马和马是不同的，白马不是马。从实用主义的角度来看，这是个简单的问题或者说根本不是个问题。当我们在日常语言中说「白马是马」时，我们的意思是白马是马的一种；当公孙龙说「白马不是马」时，他的意思是「白马」与「马」这两个词不等价，「白马」是「马」的特例。两者间根本不存在矛盾，只是表述两个不同的意思罢了。再比如说「假如一棵树在森林里倒下而没有人在附近听见，它有没有发出声音？」，只要秉持实用主义的观点，问题的答案清楚明白。当一棵树倒下，会碰撞地面产生声波，并在空气中传播，这是一个事实。如果把声音定义为「声波在介质中传播的现象」，那么倒下的树确实发出了声音；如果认为「声波在介质中传播并被人或动物的听觉器官感受到」才叫声音，那不妨说倒下的树没有发出声音。无论采取哪种观点，并没有改变树倒下这一事实，只是采取不同的方式描述罢了，这之间并不存在矛盾。我甚至可以大胆地说，绝大多数的哲学问题都不是真正的问题，只是说明了人类语言的模糊与多义。

再比如实用主义在伦理学上的应用。在我看来，并不存在绝对的道德真理。一方面，人是群居动物；另一方面，人是自私的，彼此之间存在冲突。道德的意义就是约束个体的行为，让社群更加和谐稳定。什么样的道德是好的，在于道德造成的实际效果。在不同的文明里，最基本的道德观念是近似的，因为这些道德是最有效的。当社会结构演化时，道德也应该随之演化。

实用主义在宗教、政治、生活等方方面面都有实际的应用，这里就不一一探讨了。万变不离其宗，总之就是注重事实，注重结果。有了清楚的目的地才能去选择道路，否则注定南辕北辙。

综上所述，科学与实用主义就是我最根本的信仰、最基础的思维宗旨。这两者本质上是相通的，都源自于经验主义。能用科学解决的，我就相信科学；不能用科学解决的，就用实用主义来处理。我的基本思想都能以此推演出来，这就是对我的思想原则最好的概括。

# 谈人生意义

人活着为了什么？这是人生最基本、最重要的问题了。假如说只有一个问题值得人去思考，这个问题一定是关于人生意义的，其它问题都不过是对它的阐释和注解。可是，从古至今许许多多的人，由生到死却从来没有思考过这个问题。首先，这是因为理性并非人类的第一天性。人不是经过一番缜密思考，得出了人生的种种好处，才生而为人的。人的出生不是自己决定的，生长环境不是自己选择的。人的生存欲望是先天的本能，要饮食，要呼吸，要繁衍，和动物没什么两样。直到理性觉醒，对自身以及宇宙万物有了好奇心，有了思考的原动力，人才体现出高于动物的一面。人先是活着，其后才为活着找理由。然而，一个成年的、受过教育的文明人，绝不至于没有思考的能力，为什么仍有些人对人生问题漠不关心呢？因为人是群居生物，社会这个有机体已经为人做好了种种决定，使人陷入随波逐流的状态。社会人的思想观念，言行举止，品味喜好，无不受社会潮流的影响，极少有人能特立独行。在现代工业社会里，人彻底变成庞大机器中的微小零件，只要按着既定规划做机械运动就好了。在这种环境下，思考是不必要的，甚至是不被鼓励的。我不愿轻易随波逐流、浑浑噩噩地活着，我不希望在晚年时为虚度人生而悔恨，所以我一定要想清楚人生的意义，弄明白自己到底要怎样活着。

我的第一个想法是，这个问题有没有绝对意义上的正确答案？也就是说，无论何时何地何人，放之四海而皆准的唯一解答。我试着从宗教、道德、哲学和科学这四种最主流的途径来寻找答案。这四项彼此交织重叠，并不是互相独立的。我在这里是试图推己及人，覆盖所有的人群。放眼世界，八成以上的人是宗教信徒，宗教在信徒人生中占据主导地位。无宗教信仰的人群中，很大一部分属于东亚文化圈，道德礼法取代了宗教信仰的作用。彻底的无神论者，则是以哲学与科学作为思想武器。

宗教为人生的所有问题提供了一劳永逸的解答。如果宗教是可信的，那么关于人生意义的思考就可以到此为止了，已经抵达了终点。宗教种类繁多，无法一一详加探讨。粗略地概括一下，宗教都持有一种有神论的观点，相信有一个或多个超自然的存在，也即是神。神是完美无缺的，神是一切的原因。神创造了世界也创造了人类，人生的意义就是按照神的意旨来生活，得到神的恩宠。宗教对人的生活方式有一套具体的说法，有的宗教是简单的几个戒条，有的则对生活的诸多细节面面俱到，吃喝拉撒都要管。问题在于，宗教并不可信。我是坚定的无神论者，不相信神的存在。宗教里关于神的说法都是无凭无据的，而且多与确定的科学事实相违背，我没有理由把自己的人生寄托在虚无缥缈的神身上。宗教以神为理由，武断地为人生下结论。一旦有了对神的质疑，把这个凭空宣称绝对正确的前提搁置一旁，就会发现宗教对于人生的说法虽有可取之处，却并不十分高明。一套只许相信不许质疑、诉诸权威而非理性思考的说法，必然缺乏逻辑，难以服人。

道德是衡量行为正确与否的一套准则。如果说人要「正确地」活着，那么人生意义就是做一个符合道德的人。首要的问题就是，这个意义太弱了。人的行为，有一部分可以区分对错，更多的是无对无错。穿什么衣服，吃什么饭，选择什么专业，从事什么工作，这些选择都难以从道德角度来评判。在明确的对与明确的错之外，人又要怎样生活呢？再有，道德像是交通守则，开车时要遵守，确实有重要的作用；可是开车时为了抵达目的地，不是为了遵守交通法则。返回到一开始思考问题的初衷，我是要寻找人生意义的绝对解答，可道德是绝对的吗？抛除掉以宗教为借口的道德，单独审视道德本身，我认为道德是一种人造的、意在维护人类族群整体利益的社会契约。作为群居生物，为了集体的利益，就要在族群内部互助互利，避免互相伤害。道德这一社会契约是所有人都默认遵守的，虽然对个体的约束力有强弱之分，但在影响力和持续力上，可以说是超过任何法律的，而且不需要额外的监管、执行成本。道德是社会稳定的基石，是一套强而有力的工具。通过理性思考建立起来的道德体系，应该是针对当前社会的最优解。社会是多样的，持续变化的，道德必然也要随之演变。通过比较古代与现代，不同文明之间的道德观，很显然能够看出道德是相对的。而一个相对的东西，必然不能导出绝对的答案。

哲学是纯粹的理性思考，爱思考的人一定会喜欢哲学。哲学中的每一个有价值的观点都经受过无数人长久的思索辨析、维护与攻讦，即便是最细枝末节之处也要讨论的清清楚楚。依照哲学自身以理服人的本质，它所提供的答案应该是最能被我接受的了。哲学中关于人生意义的答案，不是太少，而是太多，让人眼花缭乱难以分辨。众说纷纭，谁的说法才是正确的呢？一个令人失望的事实是，经过了无数智者两千多年来的思考探索，哲学中居然没有什么观点是被公认为真理的。世界的本源是精神还是物质？共相是不是一种客观存在？知识来自于理性还是经验？在这些最基本的哲学问题上，哲学家们都不能达成一致，甚至持有完全对立的观点。这些哲学家是人类中的最精英，有着伟大的智慧，我实在无法说谁对谁错。到最后，我得出的结论是：一个人所持有的哲学观点（没有明显逻辑错误的、有意义的观点），很大程度上是由他/她的性格、气质所决定的。在纯粹思维的层面上，那些争辩千年的对立观点，并没有哪一个优于对方。哲学著作往往是洋洋洒洒的鸿篇巨著，在很长的一段时期里，哲学家的癖好就是破坏前人的思想，创造自己的一套无所不包、关于世间万物的哲学体系。在基础理论不牢靠的情况下，要我如何相信那些构筑在空洞地基上的宏大体系呢？越是雄伟堂皇的形而上学，越有可能一钱不值。而且，根据我个人的性格气质，我倾向于经验主义的观点，我越来越认同因果关系、归纳法可能只是人的一种思维方式，哲学问题可能只是语言问题，非经验的理性思考或许根本得不出关于外部世界的真理。我说「可能」「或许」，因为具体到理论细节上，经验主义（和理性主义一样）存在着各种各样的漏洞，我的认同只是我的一种偏好。依循这种哲学观点，人生只是发生了，没有一个先天的原因。寻找意义是人的思维方式造成的，并没有说一定要有个目的才能使得一样东西存在，人生没有意义。我想通过哲学寻找人生意义，得出的结论则是否定了人生意义。

在做出最终决定之前，再来谈一下科学。宗教、道德和哲学都有不确定的、令人狐疑的地方，而科学却是最靠得住的。科学最大的好处不是正确，而是对正确的追求。科学包括了理论和实践，不仅是给出一套观点，而且主动地用事实来考验。一套能被接受的科学观点，一定符合已知的客观事实。一旦发现错误，科学是不惮于自我修正的，这修正恰巧促成了科学的进步。这种明确的可验证性，使得科学成为了人类最实用、最具威力的工具。可惜的是，科学的应用范围是有限的（对比一下，最靠不住的宗教，反而能应用到几乎所有方面，是包治百病的灵丹妙药）。能用科学来解决的问题，一定是能精确描述，能客观验证的，人生意义并不符合这一范畴。

通过种种思考，我无法找出一个确定无误的人生意义。如果把意义理解为目的，我更是否定了人生意义的存在。就像一开始所提到的，人并不是带着一个目的降生在世上的。退一步说，假设人生存在一个绝对的意义，只是因为我个人的局限和偏见无法找到。即使这样，我也要拒绝这个先天的意义，因为这否定了我的自由意志。比方说，茶壶是用来泡茶的，人类发明茶壶就是为了这个目的，这就是茶壶的存在意义。可我偏偏要用茶壶养花，又有什么不妥呢？再假如说，人类是天神或是高次元生物这类超自然存在基于高深莫测的理由创造出来的，我是否一定要去揣摩这理由呢？比起这预先设定好的理由，我更愿意按自己的想法活着。没有目的，反而给了人生最大的自由。除了目的，意义还可以被理解为价值。如果说人生意义不是指达成某个预定的目的，而是实现自我认同的某种价值，那么我相信人生意义是存在的。和绝对的通解相比，这是相对的特殊解，每个人可以依照价值观去追求不同的价值实现，每个人也就拥有各自不同的人生意义。因为缺乏普遍性，缺乏评判标准，这种人生意义是没有正确答案的。我认同一种人生意义，不是陈述一个事实，只是抒发一种意见。我辨析自己的人生意义，同时也就是去理解自己的思想与心理。

于是，问题由「人活着为了什么」，变成了「我活着为了什么」。我从自身角度出发，重新思考人生意义的问题。

我活着，本质来说，是出于对死的恐惧和对生的欲望。对死的恐惧，除去无条件的生物本能，很大程度上是害怕痛苦，以及未知的死后世界。这些恐惧都是可以克服的，所以世上从来不缺不怕死的人。对死的恐惧是消极的，构不成什么意义。再来看对生的欲望，排除掉求生本能，我想要活着是因为人生中有许多快乐，让我眷恋人世。人生中快乐多于痛苦，活着的好处多于坏处，所以我要活着。反过来说，如果不幸陷入万难之境，比如病魔缠身回天乏术，日日夜夜处在痛苦之中，死亡就成了最好的救赎。各国文明中的地狱冥府，最可怕的都是永世折磨，真正死了倒一了百了。死亡，只要不是来的太早，其实是人生的一件礼物。总之，只要一件事是可以评判好坏的，合理的选择就是趋利避害，选择好的拒绝坏的。所以，活着就是为了快乐。将快乐与痛苦的差距拉到最大，就是最大化发挥人生的价值。

人生的快乐有好多种，肉体的精神的，内在的外部的，不一而同。呼吸新鲜的空气，吃下美味的食物，感受美丽的自然，自由地奔跑，欣赏艺术，全都是做人的乐趣。这些快乐很多时候都被忽视了，因为人偏要去关注痛苦。有言道，人生不如意十之八九；我却认为，人生如意十之八九，只是身在福中不知福。人生病了，才知道健康的好处；衰老了，才明白出青春的宝贵；被限制了，才懂得自由的重要。而一个健康、年轻、自由的人，却要抱怨人生痛苦无聊，这不是暴殄天物吗。要享受快乐，首先就是要珍惜体会自己已有的种种好处。快乐与痛苦是相对的，没有绝对快乐。可以说，没有痛苦，就是快乐。

由以上讨论可以看出，快乐与否，很大程度上取决于自己的心态。人的内心容易受到歪曲，很难对事物进行客观评判。一个无财富的人，中彩票得了几百万，觉得自己是个富豪；一个亿万富翁，生意失败只剩下几百万，倒会觉得自己穷困潦倒。人的欲望是无穷无尽的，越攀越高。由俭入奢易，由奢入俭难，长此以往，总有一天会把自己所拥有的美好事物都看得一文不值。穷奢极欲是快乐人生最大的敌人。要悬崖勒马，就要懂得节制，控制自己感受快乐的心理阈值。知足者常乐，学会知足不是件容易的事。从生活中一点一滴做起，节制自己的欲念，维持自己的敏锐度，不要让自己对快乐麻木不仁。

放纵欲望，会享受到猛烈却短暂的快乐；自我节制，则会享受到徐缓却长久的快乐。对于人生中的快乐，我追求的是最大化总和，而不是若干个极端的峰值。要我去形容理想中的人生，我的答案不会是气势恢宏、跌宕起伏，而是平淡幸福、漫长平稳。

人生充满未知，怎样才能取得稳定持久的快乐呢？追求来自自身的快乐，追求精神的快乐。

来自外界的快乐是可变的，来自自身的快乐则是持久的。外界是不可控的，人不能强求外界时时符合自己的心意，却能调整自己的内心。一个人追求虚荣，希望自己是人群中的焦点，受到外界的颂扬和喜爱，这种来自外界的快乐必然是难以持久的。能得到显赫名声的总是极少数人，世上无数伟大的学者、艺术家生前默默无名，甚至度过卑贱的一生。而且世人总是喜新厌旧，注意力不持久的，那些曾经集万千宠爱于一身的明星，也会随即被人遗忘。对名声的贪心、求之不得的沮丧、从高峰跌入低谷的强烈反差，都只会给人带来痛苦。与之相对，来自自身的快乐是我自己可以掌控的，别人可以不爱我，却没有人能阻止我爱自己。爱自己，接受自己，这几乎是所有心理问题的解药。任凭外界沧海桑田，人的内心是最坚不可摧的堡垒。来自外界的快乐始终是无根浮萍，来自自身的快乐才是扎根于心灵土壤中的树木。做一个内心强大的人，就是让自己内心长出一棵枝繁叶茂的参天大树。

物质的快乐是有限的，精神的快乐是持久的。首先，肉体享受的快乐，金钱购买来的快乐，会使人陷入欲望的泥沼。人的体力和金钱是有限的，欲望却永无止境越演越烈，沉溺其中早晚会给身心带来损害。与之相对，人的精神世界是无穷无尽的。思考问题，学习知识，欣赏艺术，发明创造，这些都是没有极限的。再有，人的肉体会衰老，迟早有一天美酒佳人都成了无用之物，也不能再依靠挥霍精力得到快乐。人的智力却是越用越强，智慧会随着年龄积累。最后，追求精神世界，提高智慧，还会提高人对快乐的感受力。比起丰富的精神世界，肉体的快乐是种类稀少单调重复的。有了思想与智慧，人才能懂得天地万物演化的道理，超越时间与空间的界限。只懂得肉体快乐的人，无异于睁眼的盲人，面对人类文明最伟大的成就都会无动于衷，精神干瘪与昆虫无异。

种种快乐是相辅相成的，我推崇其中一种，并不是否定另外一种。我追求自我与精神，却不赞同遗世独立或是苦行僧式的生活。完全剥离外界与物质，就走向了另一个极端，同样有害于身心。生活的基础需求是排在第一位的。面对饥寒交迫的人，再高深的思想、再美好的艺术也无能无力。我喜欢现代科技文明、城市建设所带来的便利，我庆幸自己有稳定的收入、不用为了生存而苦命挣扎。外界与物质构成的基础，可以使我更好地追求自我与精神。重要之处是掌握分寸尺度，达到内与外、精神与物质的和谐平衡。

人生的意义是享受快乐。为了实现快乐的最大化，要以外界与物质的快乐为基础，追求自我与精神的快乐。单就结论而言，很有些陈词滥调，不是吗？在文章开头，我提到很多人没有思考过人生意义的问题；而那些思考过人生意义的人，得出的结论总可以归类为某种已有的流行观点。说人生是为神，为道德，为爱，为自我实现，为生命繁衍，为贡献社会，为人类进化，都不是什么新颖的意见。探索人生的意义，是加深对自己的了解，明白自己到底想要什么，具体的答案反倒不是最重要的。思考自己活着为了什么，以此规划自己的人生。时光一去不复返，人生不能重来，越早认清目标，就越少走弯路。人不能停止思考，对人生的理解也是不断变化的，明天的自己也许会否定今天的观点。到了中年、晚年，我的想法或许截然相反。就像对真理、对完美境界的追求一样，即便求之不得，也要努力向其靠近。人生是一个动态的过程，需要不断地自我提高、自我修正。无论最终如何，尽力而为，就可以说是最好的结果。人生意义有千百种不同的答案，唯一不变的是对人生意义的追求。

# 后记 {-}

这部文集动笔于2017年一月上旬，2018年二月中旬春节过后完成初稿。之后陆续发表于博客和社交网站，一边发表一边修改，同时增添了几篇新文章。由于工作繁忙，我只能在晚上和周末找时间写。写作只是茶余饭后的业余爱好，忙完正事后还要打起精神来琢磨文字并不是件容易的事，难免一拖再拖。好在不论快慢终究还是写完了。

关于写作动机，《我为什么写作》这一篇已经写得很清楚了，这里不再赘述。想要额外指出的一点是，随着年龄增长，越发觉得时不我待。写一本书是我的夙愿，赶在而立之年完成更增添了一份纪念意义。

这本书的首要目标是记录人生，不求文字动人但求言之有物。叙述经历、描写心态，我切记客观如实；文艺评论、思想阐述，我力求清楚明白。我的文字是直来直去的，开门见山，不用曲笔。我追求平易近人，能用日常语言表达的就坚决不用生僻词汇。

本书写作的过程也是一个自省的过程。通过对记忆与思绪的清理分析，加深了我对自己的了解。过去种种无论好坏都已成了过去，我已经准备好重新出发。